import { readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import { build, type Plugin } from "esbuild";
import { isMainModule } from "@iterate-com/shared/dev/is-main-module";
import { createCli } from "trpc-cli";

/** The SDK modules (and zod, which the SDK bundles) the platform injects as `./processor.js` into
 *  every loaded isolate, so a loaded bundle carries none of them. */
export const injectedSdk: Plugin = {
  name: "injected-sdk",
  setup(builder) {
    builder.onResolve({ filter: /^(zod|iterate\/(sdk|stream\/processor|stream\/run))$/ }, () => ({
      path: "./processor.js",
      external: true,
    }));
  },
};

/** `withItx` alone (the SDK's sdk/record-pipelined-steps.ts, ~1.5 KB minified) as the AI transport's
 *  own `with-itx.js` (runtime/ai-transport-source.ts). The transport is a loaded worker of its own,
 *  cold per agent: shipping `withItx` with it keeps the whole SDK off the model call's path, and
 *  keeps it linking whatever `./processor.js` the platform injects, whichever app deployed first.
 *  apps/os bundles the same file for an `itx.run` script (scripts/build.ts `withItxModule`). */
async function buildWithItxModule(): Promise<string> {
  const sdk = path.dirname(createRequire(import.meta.url).resolve("iterate/sdk"));
  const result = await build({
    entryPoints: [path.join(sdk, "record-pipelined-steps.ts")],
    bundle: true,
    format: "esm",
    platform: "neutral",
    target: "es2022",
    minify: true,
    write: false,
  });
  return (
    "// Generated by pnpm --dir apps/agents runtime:build from the SDK's sdk/record-pipelined-steps.ts. Do not edit.\n" +
    `export const WITH_ITX_MODULE = ${JSON.stringify(result.outputFiles[0]!.text)};\n`
  );
}

/** The committed template asset is rebuilt from this app's runtime. The platform's SDK is injected. */
export async function buildAgentRuntime(): Promise<string> {
  const result = await build({
    absWorkingDir: new URL("..", import.meta.url).pathname,
    entryPoints: [new URL("../runtime/index.ts", import.meta.url).pathname],
    bundle: true,
    format: "esm",
    platform: "neutral",
    target: "es2022",
    write: false,
    external: ["cloudflare:workers"],
    plugins: [injectedSdk],
  });
  return (
    "// Generated by pnpm --dir apps/agents runtime:build. Do not edit.\n" +
    result.outputFiles[0]!.text
  );
}

/** Rebuilds runtime/with-itx-module.ts and configs/with-agents/agents.js from this app's runtime,
 *  or with --check fails when either committed file is stale. */
export default async function buildRuntime(
  options: {
    /** Compare with the committed files instead of writing them. */
    check?: boolean;
  } = {},
) {
  // with-itx-module.ts first: the runtime bundle embeds it.
  const outputs: [string, () => Promise<string>][] = [
    [new URL("../runtime/with-itx-module.ts", import.meta.url).pathname, buildWithItxModule],
    [
      new URL("../../../configs/with-agents/agents.js", import.meta.url).pathname,
      buildAgentRuntime,
    ],
  ];
  for (const [file, generate] of outputs) {
    const source = await generate();
    if (options.check) {
      if ((await readFile(file, "utf8")) !== source)
        throw new Error(
          `${path.basename(file)} is stale. Run pnpm --dir apps/agents runtime:build`,
        );
    } else {
      await writeFile(file, source);
    }
  }
}

if (isMainModule(import.meta.url)) void createCli({ ...import.meta, name: "build-runtime" }).run();
