// Generated by `sqlfu generate`. Do not edit.

export * from "./count-all-projects.sql.ts";
export * from "./delete-project.sql.ts";
export * from "./get-itx-context-by-id.sql.ts";
export * from "./get-project-by-custom-hostname.sql.ts";
export * from "./get-project-by-custom-hostname-any-organization.sql.ts";
export * from "./get-project-by-id.sql.ts";
export * from "./get-project-by-slug.sql.ts";
export * from "./insert-itx-context.sql.ts";
export * from "./insert-project.sql.ts";
export * from "./list-all-projects.sql.ts";
export * from "./list-projects-by-slug.sql.ts";
export * from "./update-project-config.sql.ts";

export const sqlfuQuerySources = [
  {
    sqlFile: "count-all-projects.sql",
    generatedFile: "count-all-projects.sql.ts",
    sourceSql: "select count(*) as total\nfrom projects;\n",
  },
  {
    sqlFile: "delete-project.sql",
    generatedFile: "delete-project.sql.ts",
    sourceSql: "delete from projects\nwhere id = :id;\n",
  },
  {
    sqlFile: "get-itx-context-by-id.sql",
    generatedFile: "get-itx-context-by-id.sql.ts",
    sourceSql: "select id, project_id, journal_path\nfrom itx_contexts\nwhere id = :id\nlimit 1;\n",
  },
  {
    sqlFile: "get-project-by-custom-hostname.sql",
    generatedFile: "get-project-by-custom-hostname.sql.ts",
    sourceSql:
      "select id, slug, custom_hostname, created_at, updated_at\nfrom projects\nwhere custom_hostname = :customHostname\nlimit 1;\n",
  },
  {
    sqlFile: "get-project-by-custom-hostname-any-organization.sql",
    generatedFile: "get-project-by-custom-hostname-any-organization.sql.ts",
    sourceSql:
      "select id, slug, custom_hostname, created_at, updated_at\nfrom projects\nwhere custom_hostname = :customHostname\nlimit 1;\n",
  },
  {
    sqlFile: "get-project-by-id.sql",
    generatedFile: "get-project-by-id.sql.ts",
    sourceSql:
      "select id, slug, custom_hostname, created_at, updated_at\nfrom projects\nwhere id = :id\nlimit 1;\n",
  },
  {
    sqlFile: "get-project-by-slug.sql",
    generatedFile: "get-project-by-slug.sql.ts",
    sourceSql:
      "select id, slug, custom_hostname, created_at, updated_at\nfrom projects\nwhere slug = :slug\nlimit 1;\n",
  },
  {
    sqlFile: "insert-itx-context.sql",
    generatedFile: "insert-itx-context.sql.ts",
    sourceSql:
      "insert into itx_contexts (id, project_id, journal_path)\nvalues (:id, :projectId, :journalPath)\non conflict (id) do nothing;\n",
  },
  {
    sqlFile: "insert-project.sql",
    generatedFile: "insert-project.sql.ts",
    sourceSql:
      "insert into projects (id, slug)\nvalues (:id, :slug)\nreturning id, slug, custom_hostname, created_at, updated_at;\n",
  },
  {
    sqlFile: "list-all-projects.sql",
    generatedFile: "list-all-projects.sql.ts",
    sourceSql:
      "select id, slug, custom_hostname, created_at, updated_at\nfrom projects\norder by created_at desc\nlimit :limit\noffset :offset;\n",
  },
  {
    sqlFile: "list-projects-by-slug.sql",
    generatedFile: "list-projects-by-slug.sql.ts",
    sourceSql:
      "select id, slug, custom_hostname, created_at, updated_at\nfrom projects\nwhere slug = :slug\norder by created_at asc\nlimit 2;\n",
  },
  {
    sqlFile: "update-project-config.sql",
    generatedFile: "update-project-config.sql.ts",
    sourceSql:
      "update projects\nset custom_hostname = :customHostname,\n    updated_at = strftime('%Y-%m-%d %H:%M:%S', 'now')\nwhere id = :id;\n",
  },
];
