// Generated by `sqlfu generate`. Do not edit.
// Row types for every table and view in your project's schema.

export type ItxContextsRow = {
  id: string;
  project_id: string;
  journal_path: string;
  created_at: string;
};

export type ProjectsRow = {
  id: string;
  slug: string;
  custom_hostname: string | null;
  created_at: string;
  updated_at: string;
};
