/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as PosthogProxySplatRouteImport } from './routes/posthog-proxy.$'
import { Route as ApiPtyRouteImport } from './routes/api.pty'
import { Route as ApiOrpcWsRouteImport } from './routes/api.orpc-ws'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AppTerminalRouteImport } from './routes/_app/terminal'
import { Route as AppRoutesRouteImport } from './routes/_app/routes'
import { Route as AppDocsRouteImport } from './routes/_app/docs'
import { Route as AppDbRouteImport } from './routes/_app/db'
import { Route as AppConfigRouteImport } from './routes/_app/config'
import { Route as AppCaddyRouteImport } from './routes/_app/caddy'
import { Route as AppRoutesIndexRouteImport } from './routes/_app/routes/index'
import { Route as ApiOrpcSplatRouteImport } from './routes/api.orpc.$'
import { Route as AppRoutesSlugRouteImport } from './routes/_app/routes/$slug'
import { Route as AppRoutesSlugIndexRouteImport } from './routes/_app/routes/$slug/index'
import { Route as AppRoutesSlugDocsRouteImport } from './routes/_app/routes/$slug/docs'
import { Route as AppRoutesSlugDbRouteImport } from './routes/_app/routes/$slug/db'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PosthogProxySplatRoute = PosthogProxySplatRouteImport.update({
  id: '/posthog-proxy/$',
  path: '/posthog-proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPtyRoute = ApiPtyRouteImport.update({
  id: '/api/pty',
  path: '/api/pty',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrpcWsRoute = ApiOrpcWsRouteImport.update({
  id: '/api/orpc-ws',
  path: '/api/orpc-ws',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTerminalRoute = AppTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutesRoute = AppRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppDbRoute = AppDbRouteImport.update({
  id: '/db',
  path: '/db',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigRoute = AppConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppRoute,
} as any)
const AppCaddyRoute = AppCaddyRouteImport.update({
  id: '/caddy',
  path: '/caddy',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutesIndexRoute = AppRoutesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoutesRoute,
} as any)
const ApiOrpcSplatRoute = ApiOrpcSplatRouteImport.update({
  id: '/api/orpc/$',
  path: '/api/orpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoutesSlugRoute = AppRoutesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppRoutesRoute,
} as any)
const AppRoutesSlugIndexRoute = AppRoutesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoutesSlugRoute,
} as any)
const AppRoutesSlugDocsRoute = AppRoutesSlugDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoutesSlugRoute,
} as any)
const AppRoutesSlugDbRoute = AppRoutesSlugDbRouteImport.update({
  id: '/db',
  path: '/db',
  getParentRoute: () => AppRoutesSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/caddy': typeof AppCaddyRoute
  '/config': typeof AppConfigRoute
  '/db': typeof AppDbRoute
  '/docs': typeof AppDocsRoute
  '/routes': typeof AppRoutesRouteWithChildren
  '/terminal': typeof AppTerminalRoute
  '/api/$': typeof ApiSplatRoute
  '/api/orpc-ws': typeof ApiOrpcWsRoute
  '/api/pty': typeof ApiPtyRoute
  '/posthog-proxy/$': typeof PosthogProxySplatRoute
  '/routes/$slug': typeof AppRoutesSlugRouteWithChildren
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/routes/': typeof AppRoutesIndexRoute
  '/routes/$slug/db': typeof AppRoutesSlugDbRoute
  '/routes/$slug/docs': typeof AppRoutesSlugDocsRoute
  '/routes/$slug/': typeof AppRoutesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/caddy': typeof AppCaddyRoute
  '/config': typeof AppConfigRoute
  '/db': typeof AppDbRoute
  '/docs': typeof AppDocsRoute
  '/terminal': typeof AppTerminalRoute
  '/api/$': typeof ApiSplatRoute
  '/api/orpc-ws': typeof ApiOrpcWsRoute
  '/api/pty': typeof ApiPtyRoute
  '/posthog-proxy/$': typeof PosthogProxySplatRoute
  '/': typeof AppIndexRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/routes': typeof AppRoutesIndexRoute
  '/routes/$slug/db': typeof AppRoutesSlugDbRoute
  '/routes/$slug/docs': typeof AppRoutesSlugDocsRoute
  '/routes/$slug': typeof AppRoutesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/caddy': typeof AppCaddyRoute
  '/_app/config': typeof AppConfigRoute
  '/_app/db': typeof AppDbRoute
  '/_app/docs': typeof AppDocsRoute
  '/_app/routes': typeof AppRoutesRouteWithChildren
  '/_app/terminal': typeof AppTerminalRoute
  '/api/$': typeof ApiSplatRoute
  '/api/orpc-ws': typeof ApiOrpcWsRoute
  '/api/pty': typeof ApiPtyRoute
  '/posthog-proxy/$': typeof PosthogProxySplatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/routes/$slug': typeof AppRoutesSlugRouteWithChildren
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/_app/routes/': typeof AppRoutesIndexRoute
  '/_app/routes/$slug/db': typeof AppRoutesSlugDbRoute
  '/_app/routes/$slug/docs': typeof AppRoutesSlugDocsRoute
  '/_app/routes/$slug/': typeof AppRoutesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/caddy'
    | '/config'
    | '/db'
    | '/docs'
    | '/routes'
    | '/terminal'
    | '/api/$'
    | '/api/orpc-ws'
    | '/api/pty'
    | '/posthog-proxy/$'
    | '/routes/$slug'
    | '/api/orpc/$'
    | '/routes/'
    | '/routes/$slug/db'
    | '/routes/$slug/docs'
    | '/routes/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/caddy'
    | '/config'
    | '/db'
    | '/docs'
    | '/terminal'
    | '/api/$'
    | '/api/orpc-ws'
    | '/api/pty'
    | '/posthog-proxy/$'
    | '/'
    | '/api/orpc/$'
    | '/routes'
    | '/routes/$slug/db'
    | '/routes/$slug/docs'
    | '/routes/$slug'
  id:
    | '__root__'
    | '/_app'
    | '/_app/caddy'
    | '/_app/config'
    | '/_app/db'
    | '/_app/docs'
    | '/_app/routes'
    | '/_app/terminal'
    | '/api/$'
    | '/api/orpc-ws'
    | '/api/pty'
    | '/posthog-proxy/$'
    | '/_app/'
    | '/_app/routes/$slug'
    | '/api/orpc/$'
    | '/_app/routes/'
    | '/_app/routes/$slug/db'
    | '/_app/routes/$slug/docs'
    | '/_app/routes/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiOrpcWsRoute: typeof ApiOrpcWsRoute
  ApiPtyRoute: typeof ApiPtyRoute
  PosthogProxySplatRoute: typeof PosthogProxySplatRoute
  ApiOrpcSplatRoute: typeof ApiOrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/posthog-proxy/$': {
      id: '/posthog-proxy/$'
      path: '/posthog-proxy/$'
      fullPath: '/posthog-proxy/$'
      preLoaderRoute: typeof PosthogProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pty': {
      id: '/api/pty'
      path: '/api/pty'
      fullPath: '/api/pty'
      preLoaderRoute: typeof ApiPtyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orpc-ws': {
      id: '/api/orpc-ws'
      path: '/api/orpc-ws'
      fullPath: '/api/orpc-ws'
      preLoaderRoute: typeof ApiOrpcWsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/terminal': {
      id: '/_app/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof AppTerminalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routes': {
      id: '/_app/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof AppRoutesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/docs': {
      id: '/_app/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/db': {
      id: '/_app/db'
      path: '/db'
      fullPath: '/db'
      preLoaderRoute: typeof AppDbRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config': {
      id: '/_app/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AppConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/caddy': {
      id: '/_app/caddy'
      path: '/caddy'
      fullPath: '/caddy'
      preLoaderRoute: typeof AppCaddyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routes/': {
      id: '/_app/routes/'
      path: '/'
      fullPath: '/routes/'
      preLoaderRoute: typeof AppRoutesIndexRouteImport
      parentRoute: typeof AppRoutesRoute
    }
    '/api/orpc/$': {
      id: '/api/orpc/$'
      path: '/api/orpc/$'
      fullPath: '/api/orpc/$'
      preLoaderRoute: typeof ApiOrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/routes/$slug': {
      id: '/_app/routes/$slug'
      path: '/$slug'
      fullPath: '/routes/$slug'
      preLoaderRoute: typeof AppRoutesSlugRouteImport
      parentRoute: typeof AppRoutesRoute
    }
    '/_app/routes/$slug/': {
      id: '/_app/routes/$slug/'
      path: '/'
      fullPath: '/routes/$slug/'
      preLoaderRoute: typeof AppRoutesSlugIndexRouteImport
      parentRoute: typeof AppRoutesSlugRoute
    }
    '/_app/routes/$slug/docs': {
      id: '/_app/routes/$slug/docs'
      path: '/docs'
      fullPath: '/routes/$slug/docs'
      preLoaderRoute: typeof AppRoutesSlugDocsRouteImport
      parentRoute: typeof AppRoutesSlugRoute
    }
    '/_app/routes/$slug/db': {
      id: '/_app/routes/$slug/db'
      path: '/db'
      fullPath: '/routes/$slug/db'
      preLoaderRoute: typeof AppRoutesSlugDbRouteImport
      parentRoute: typeof AppRoutesSlugRoute
    }
  }
}

interface AppRoutesSlugRouteChildren {
  AppRoutesSlugDbRoute: typeof AppRoutesSlugDbRoute
  AppRoutesSlugDocsRoute: typeof AppRoutesSlugDocsRoute
  AppRoutesSlugIndexRoute: typeof AppRoutesSlugIndexRoute
}

const AppRoutesSlugRouteChildren: AppRoutesSlugRouteChildren = {
  AppRoutesSlugDbRoute: AppRoutesSlugDbRoute,
  AppRoutesSlugDocsRoute: AppRoutesSlugDocsRoute,
  AppRoutesSlugIndexRoute: AppRoutesSlugIndexRoute,
}

const AppRoutesSlugRouteWithChildren = AppRoutesSlugRoute._addFileChildren(
  AppRoutesSlugRouteChildren,
)

interface AppRoutesRouteChildren {
  AppRoutesSlugRoute: typeof AppRoutesSlugRouteWithChildren
  AppRoutesIndexRoute: typeof AppRoutesIndexRoute
}

const AppRoutesRouteChildren: AppRoutesRouteChildren = {
  AppRoutesSlugRoute: AppRoutesSlugRouteWithChildren,
  AppRoutesIndexRoute: AppRoutesIndexRoute,
}

const AppRoutesRouteWithChildren = AppRoutesRoute._addFileChildren(
  AppRoutesRouteChildren,
)

interface AppRouteChildren {
  AppCaddyRoute: typeof AppCaddyRoute
  AppConfigRoute: typeof AppConfigRoute
  AppDbRoute: typeof AppDbRoute
  AppDocsRoute: typeof AppDocsRoute
  AppRoutesRoute: typeof AppRoutesRouteWithChildren
  AppTerminalRoute: typeof AppTerminalRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCaddyRoute: AppCaddyRoute,
  AppConfigRoute: AppConfigRoute,
  AppDbRoute: AppDbRoute,
  AppDocsRoute: AppDocsRoute,
  AppRoutesRoute: AppRoutesRouteWithChildren,
  AppTerminalRoute: AppTerminalRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiOrpcWsRoute: ApiOrpcWsRoute,
  ApiPtyRoute: ApiPtyRoute,
  PosthogProxySplatRoute: PosthogProxySplatRoute,
  ApiOrpcSplatRoute: ApiOrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
