#!/bin/bash
# Archil persistent volume mount — managed by pidnap.
# Mounts the project's Archil disk at ~ so the entire home directory
# persists across machine reprovisioning.
#
# First boot (empty disk): copies dotfiles from image, clones iterate repo, pnpm install.
# Subsequent boots: archil already has everything from a previous machine's session.
#
# Env vars (from process env, set by Fly from project env vars):
#   ARCHIL_DISK_NAME   — disk ID (e.g. dsk-0000000000003139)
#   ARCHIL_MOUNT_TOKEN — auth token for mount
#   ARCHIL_REGION      — region (e.g. us-east-1, auto-prefixed to aws-us-east-1)
#   GIT_SHA            — image git sha, used to clone the correct version on first boot
set -euo pipefail

MOUNT_POINT="/home/iterate"
STAGING="/mnt/archil-staging"
ITERATE_REPO="${ITERATE_REPO:-${MOUNT_POINT}/src/github.com/iterate/iterate}"

# Source env vars from .env files if not already set via process env
if [[ -z "${ARCHIL_DISK_NAME:-}" ]] && [[ -f "${MOUNT_POINT}/.iterate/.env" ]]; then
  eval "$(grep -E '^(ARCHIL_DISK_NAME|ARCHIL_MOUNT_TOKEN|ARCHIL_REGION)=' "${MOUNT_POINT}/.iterate/.env")"
fi

if [[ -z "${ARCHIL_DISK_NAME:-}" ]]; then
  echo "[archil] No ARCHIL_DISK_NAME set, skipping mount"
  exec sleep infinity
fi

# Already mounted? Sleep to keep process alive.
if grep -q "archil" /proc/mounts 2>/dev/null; then
  echo "[archil] Already mounted"
  # Ensure bind mount is in place (may have been lost on restart)
  if ! mountpoint -q "${MOUNT_POINT}" 2>/dev/null; then
    echo "[archil] Re-establishing bind mount ${STAGING} -> ${MOUNT_POINT}"
    sudo mount --bind "$STAGING" "$MOUNT_POINT"
    touch /tmp/archil-home-ready
  fi
  exec sleep infinity
fi

# Archil CLI expects provider-prefixed region (e.g. aws-us-east-1)
ARCHIL_CLI_REGION="${ARCHIL_REGION:-us-east-1}"
case "${ARCHIL_CLI_REGION}" in
  aws-*|gcp-*) ;; # already prefixed
  *) ARCHIL_CLI_REGION="aws-${ARCHIL_CLI_REGION}" ;;
esac

export ARCHIL_MOUNT_TOKEN="${ARCHIL_MOUNT_TOKEN:-}"

echo "[archil] Mounting disk ${ARCHIL_DISK_NAME} at ${STAGING} -> ${MOUNT_POINT} (region: ${ARCHIL_CLI_REGION})"

# Snapshot essential dotfiles from image BEFORE mount hides them.
# Only copy small config files — skip large tool caches (.cache, .npm, go/, .bun, etc.)
# which will be regenerated by pnpm install and tool usage.
if [[ ! -d /tmp/home-seed ]]; then
  mkdir -p /tmp/home-seed/.iterate
  for f in .bashrc .bash_logout .profile .gitconfig .npmrc .claude.json; do
    [[ -f "${MOUNT_POINT}/$f" ]] && cp "${MOUNT_POINT}/$f" /tmp/home-seed/
  done
  # Copy mitmproxy certs (needed for egress proxy)
  [[ -d "${MOUNT_POINT}/.mitmproxy" ]] && cp -a "${MOUNT_POINT}/.mitmproxy" /tmp/home-seed/
  # Copy .iterate dir (contains bin wrappers etc.)
  [[ -d "${MOUNT_POINT}/.iterate/bin" ]] && cp -a "${MOUNT_POINT}/.iterate" /tmp/home-seed/
  # Copy .config (opencode, claude settings etc.)
  [[ -d "${MOUNT_POINT}/.config" ]] && cp -a "${MOUNT_POINT}/.config" /tmp/home-seed/
  echo "[archil] Saved dotfiles snapshot"
fi

# Archil FUSE (libfuse2) refuses to mount on a non-empty directory.
# Mount to an empty staging dir first, then bind-mount over ~.
sudo mkdir -p "$STAGING"

# Post-mount tasks run in background since --no-fork blocks the main thread.
(
  # Wait for archil to mount at the staging dir
  while ! grep -q "$STAGING" /proc/mounts 2>/dev/null; do sleep 1; done
  echo "[archil] Archil mounted at ${STAGING}"

  sudo chown iterate:iterate "$STAGING"

  # First boot: if the disk has no .bashrc, it's a fresh/empty disk.
  if [[ ! -f "${STAGING}/.bashrc" ]]; then
    echo "[archil] First boot — setting up persistent home directory"

    # 1. Seed dotfiles/configs from image snapshot
    if [[ -d /tmp/home-seed ]]; then
      cp -a /tmp/home-seed/. "${STAGING}/"
      echo "[archil] Dotfiles seeded"
    fi

    # 2. Clone iterate repo and install deps
    REPO_DIR="${STAGING}/src/github.com/iterate/iterate"
    mkdir -p "$(dirname "$REPO_DIR")"

    REPO_URL="${ITERATE_REPO_URL:-https://github.com/nichochar/iterate.git}"
    REPO_REF="${GIT_SHA:-main}"

    # Wait for egress proxy (port 8888) — .gitconfig routes through it
    echo "[archil] Waiting for egress proxy on port 8888..."
    for i in $(seq 1 60); do
      if nc -z 127.0.0.1 8888 2>/dev/null; then
        echo "[archil] Egress proxy ready"
        break
      fi
      sleep 1
    done

    echo "[archil] Cloning ${REPO_URL} @ ${REPO_REF}"
    git clone --depth 1 --branch main "$REPO_URL" "$REPO_DIR" 2>&1 || {
      # If branch clone fails, try cloning then checking out the sha
      rm -rf "$REPO_DIR"
      git clone "$REPO_URL" "$REPO_DIR" 2>&1
    }

    # Checkout the specific sha if it's not 'main' or 'unknown'
    if [[ "$REPO_REF" != "main" ]] && [[ "$REPO_REF" != "unknown" ]]; then
      cd "$REPO_DIR"
      git fetch origin "$REPO_REF" 2>/dev/null || true
      git checkout "$REPO_REF" 2>/dev/null || echo "[archil] Warning: could not checkout ${REPO_REF}, staying on main"
    fi

    # 3. Install dependencies
    echo "[archil] Installing dependencies (pnpm install)"
    cd "$REPO_DIR"
    pnpm install --frozen-lockfile 2>&1

    # 4. Run post-sync steps (builds daemon frontend, runs migrations, etc.)
    echo "[archil] Running post-sync steps"
    bash "$REPO_DIR/sandbox/after-repo-sync-steps.sh" 2>&1

    # 5. Init git repo for tools that need it
    git add . 2>/dev/null || true
    git commit -m "archil first boot" 2>/dev/null || true

    echo "[archil] First boot setup complete"
  else
    echo "[archil] Existing home directory found, skipping setup"
  fi

  # Bind-mount the staging dir over ~ so all processes see the persistent disk at ~
  echo "[archil] Bind-mounting ${STAGING} over ${MOUNT_POINT}"
  sudo mount --bind "$STAGING" "$MOUNT_POINT"

  # Signal that the home directory is ready for other processes
  touch /tmp/archil-home-ready
  echo "[archil] Home directory ready"
) &

# --force: claim ownership even if stale delegation exists from a previous machine.
# --no-fork: keep archil in foreground so pidnap can manage the process lifecycle.
# --log-dir: log to file for debugging.
sudo --preserve-env=ARCHIL_MOUNT_TOKEN archil mount "${ARCHIL_DISK_NAME}" "${STAGING}" \
  --region "${ARCHIL_CLI_REGION}" \
  --force \
  --no-fork \
  --log-dir /var/log/archil

# If archil mount exits, this script exits and pidnap will restart it.
