// Auto-generated by scripts/generate-queries.ts from sql/queries.sql. Do not edit manually.

import type { D1Database, D1PreparedStatement } from '@cloudflare/workers-types';

export type SelectRouteCandidatesByRootHostsParams = {
	exactRootHost: string;
	dunderRootHost: string | null;
	subhostRootHost: string | null;
}

export type SelectRouteCandidatesByRootHostsResult = {
	id: string;
	rootHost: string;
	targetUrl: string;
	metadataJson: string;
	createdAt: string;
	updatedAt: string;
}

export function selectRouteCandidatesByRootHostsStmt(db: D1Database, params: SelectRouteCandidatesByRootHostsParams): D1PreparedStatement {
	const sql = `
	-- Each stored root_host is the canonical deployment ingress host and maps to
	-- the deployment env var ITERATE_INGRESS_HOST.
	--
	-- The worker derives alternate public host forms from
	-- ITERATE_INGRESS_ROUTING_TYPE without storing extra rows:
	--   1. exact root host:      root.example.com
	--   2. dunder-prefix host:   service__root.example.com
	--   3. subdomain-host form:  service.root.example.com
	--
	-- The resolver computes up to three candidate root hosts in TypeScript, then
	-- does exact equality checks here so the lookup stays simple and deterministic.
	SELECT
	  id,
	  root_host AS rootHost,
	  target_url AS targetUrl,
	  metadata_json AS metadataJson,
	  created_at AS createdAt,
	  updated_at AS updatedAt
	FROM ingress_proxy_route
	WHERE
	  root_host = ?
	  OR (? IS NOT NULL AND root_host = ?)
	  OR (? IS NOT NULL AND root_host = ?)
	ORDER BY
	  CASE
	    WHEN root_host = ? THEN 0
	    WHEN ? IS NOT NULL AND root_host = ? THEN 1
	    WHEN ? IS NOT NULL AND root_host = ? THEN 2
	    ELSE 3
	  END ASC,
	  length(root_host) DESC,
	  root_host ASC
	LIMIT 10
	
	`
	return db.prepare(sql)
		.bind(params.exactRootHost, params.dunderRootHost, params.dunderRootHost, params.subhostRootHost, params.subhostRootHost, params.exactRootHost, params.dunderRootHost, params.dunderRootHost, params.subhostRootHost, params.subhostRootHost)
		;
}

export async function selectRouteCandidatesByRootHosts(db: D1Database, params: SelectRouteCandidatesByRootHostsParams): Promise<SelectRouteCandidatesByRootHostsResult[]> {
	return selectRouteCandidatesByRootHostsStmt(db, params)
		.raw({ columnNames: false })
		.then(rows => rows.map(row => mapArrayToSelectRouteCandidatesByRootHostsResult(row)));
}

function mapArrayToSelectRouteCandidatesByRootHostsResult(data: any) {
	const result: SelectRouteCandidatesByRootHostsResult = {
		id: data[0],
		rootHost: data[1],
		targetUrl: data[2],
		metadataJson: data[3],
		createdAt: data[4],
		updatedAt: data[5]
	}
	return result;
}

export type SelectRouteByRootHostParams = {
	rootHost: string;
}

export type SelectRouteByRootHostResult = {
	id: string;
	rootHost: string;
	targetUrl: string;
	metadataJson: string;
	createdAt: string;
	updatedAt: string;
}

export function selectRouteByRootHostStmt(db: D1Database, params: SelectRouteByRootHostParams): D1PreparedStatement {
	const sql = `
	-- Reads the canonical row for a deployment ingress host.
	SELECT
	  id,
	  root_host AS rootHost,
	  target_url AS targetUrl,
	  metadata_json AS metadataJson,
	  created_at AS createdAt,
	  updated_at AS updatedAt
	FROM ingress_proxy_route
	WHERE root_host = ?
	
	`
	return db.prepare(sql)
		.bind(params.rootHost)
		;
}

export async function selectRouteByRootHost(db: D1Database, params: SelectRouteByRootHostParams): Promise<SelectRouteByRootHostResult[]> {
	return selectRouteByRootHostStmt(db, params)
		.raw({ columnNames: false })
		.then(rows => rows.map(row => mapArrayToSelectRouteByRootHostResult(row)));
}

function mapArrayToSelectRouteByRootHostResult(data: any) {
	const result: SelectRouteByRootHostResult = {
		id: data[0],
		rootHost: data[1],
		targetUrl: data[2],
		metadataJson: data[3],
		createdAt: data[4],
		updatedAt: data[5]
	}
	return result;
}

export type SelectRoutesPageParams = {
	limit: number;
	offset: number;
}

export type SelectRoutesPageResult = {
	id: string;
	rootHost: string;
	targetUrl: string;
	metadataJson: string;
	createdAt: string;
	updatedAt: string;
}

export function selectRoutesPageStmt(db: D1Database, params: SelectRoutesPageParams): D1PreparedStatement {
	const sql = `
	SELECT
	  id,
	  root_host AS rootHost,
	  target_url AS targetUrl,
	  metadata_json AS metadataJson,
	  created_at AS createdAt,
	  updated_at AS updatedAt
	FROM ingress_proxy_route
	ORDER BY created_at DESC, root_host ASC
	LIMIT ? OFFSET ?
	
	`
	return db.prepare(sql)
		.bind(params.limit, params.offset)
		;
}

export async function selectRoutesPage(db: D1Database, params: SelectRoutesPageParams): Promise<SelectRoutesPageResult[]> {
	return selectRoutesPageStmt(db, params)
		.raw({ columnNames: false })
		.then(rows => rows.map(row => mapArrayToSelectRoutesPageResult(row)));
}

function mapArrayToSelectRoutesPageResult(data: any) {
	const result: SelectRoutesPageResult = {
		id: data[0],
		rootHost: data[1],
		targetUrl: data[2],
		metadataJson: data[3],
		createdAt: data[4],
		updatedAt: data[5]
	}
	return result;
}

export type CountRoutesResult = {
	total: number;
}

export function countRoutesStmt(db: D1Database): D1PreparedStatement {
	const sql = `
	SELECT count(*) AS total
	FROM ingress_proxy_route
	
	`
	return db.prepare(sql)
		;
}

export async function countRoutes(db: D1Database): Promise<CountRoutesResult | null> {
	return countRoutesStmt(db)
		.raw({ columnNames: false })
		.then(rows => rows.length > 0 ? mapArrayToCountRoutesResult(rows[0]) : null);
}

function mapArrayToCountRoutesResult(data: any) {
	const result: CountRoutesResult = {
		total: data[0]
	}
	return result;
}

export type UpsertRouteByRootHostParams = {
	id: string;
	rootHost: string;
	targetUrl: string;
	metadataJson: string;
}

export type UpsertRouteByRootHostResult = {
	changes: number;
	last_row_id: number;
}

export function upsertRouteByRootHostStmt(db: D1Database, params: UpsertRouteByRootHostParams): D1PreparedStatement {
	const sql = `
	-- One row per ITERATE_INGRESS_HOST. Re-registering the same root host updates
	-- the target and metadata in place while preserving the original stable id.
	INSERT INTO ingress_proxy_route (id, root_host, target_url, metadata_json)
	VALUES (?, ?, ?, ?)
	ON CONFLICT(root_host) DO UPDATE SET
	  target_url = excluded.target_url,
	  metadata_json = excluded.metadata_json,
	  updated_at = CURRENT_TIMESTAMP
	
	`
	return db.prepare(sql)
		.bind(params.id, params.rootHost, params.targetUrl, params.metadataJson)
		;
}

export async function upsertRouteByRootHost(db: D1Database, params: UpsertRouteByRootHostParams): Promise<UpsertRouteByRootHostResult> {
	return upsertRouteByRootHostStmt(db, params)
		.run()
		.then(res => res.meta);
}

export type DeleteRouteByRootHostParams = {
	rootHost: string;
}

export type DeleteRouteByRootHostResult = {
	changes: number;
}

export function deleteRouteByRootHostStmt(db: D1Database, params: DeleteRouteByRootHostParams): D1PreparedStatement {
	const sql = `
	-- Deleting the canonical root row removes all public host shapes derived from
	-- ITERATE_INGRESS_HOST and ITERATE_INGRESS_ROUTING_TYPE.
	DELETE FROM ingress_proxy_route
	WHERE root_host = ?
	
	`
	return db.prepare(sql)
		.bind(params.rootHost)
		;
}

export async function deleteRouteByRootHost(db: D1Database, params: DeleteRouteByRootHostParams): Promise<DeleteRouteByRootHostResult> {
	return deleteRouteByRootHostStmt(db, params)
		.run()
		.then(res => res.meta);
}
