/**
 * Generates apps/streams-example-app/wrangler.jsonc (gitignored) from the
 * root envs.ts.
 *
 * Nobody edits or commits the output: vite.config.ts regenerates it before
 * every dev/build, deploys therefore always see a fresh one, and
 * `pnpm gen:wrangler` refreshes it by hand for ad-hoc wrangler commands.
 *
 * The top-level config is local dev; each deployed environment gets an env
 * block expanded from its streamsExampleEnvs entry. The app is workers.dev
 * only: no routes, no DNS, no resources, no secrets. Its one binding is the
 * same-script STREAM Durable Object — the app re-exports apps/os's
 * StreamDurableObject from its own worker entry (src/worker.ts) via the `~`
 * alias, so the class lives in this script.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { streamsExampleEnvs, type StreamsExampleEnv } from "../../../envs.ts";

const CONFIG_PATH = fileURLToPath(new URL("../wrangler.jsonc", import.meta.url));

const OBSERVABILITY = {
  enabled: true,
  head_sampling_rate: 1,
  logs: { enabled: true, head_sampling_rate: 1, persist: true, invocation_logs: true },
  traces: { enabled: true, persist: true, head_sampling_rate: 1 },
};

/** Binding config identical across local dev and every deployed env. */
function workerBindings() {
  return {
    durable_objects: {
      bindings: [{ name: "STREAM", class_name: "StreamDurableObject" }],
    },
    observability: OBSERVABILITY,
  };
}

function envBlock(env: StreamsExampleEnv) {
  return {
    name: env.workerName,
    account_id: env.cloudflareAccountId,
    // The env's only public URL is its workers.dev origin (envs.ts baseUrl).
    workers_dev: true,
    ...workerBindings(),
  };
}

const config = {
  $schema: "node_modules/wrangler/config-schema.json",
  name: "streams-example-app-dev",
  main: "./src/worker.ts",
  compatibility_date: "2026-06-17",
  compatibility_flags: ["nodejs_compat", "nodejs_compat_populate_process_env"],
  // No `assets` here: the vite plugin injects the client build's assets
  // config into the OUTPUT wrangler.json (dist/…) that deploys actually use.
  migrations: [{ tag: "v1", new_sqlite_classes: ["StreamDurableObject"] }],
  ...workerBindings(),
  env: Object.fromEntries(
    Object.entries(streamsExampleEnvs).map(([name, env]) => [name, envBlock(env)]),
  ),
};

/**
 * Write wrangler.jsonc (gitignored) if its content changed. Called by
 * vite.config.ts before the cloudflare plugin reads the file — so `vite dev`
 * and `vite build` can never see a stale config — and runnable directly via
 * `pnpm gen:wrangler` for ad-hoc wrangler commands.
 */
export function writeWranglerConfig() {
  const header = `// GENERATED by scripts/generate-wrangler-config.ts — gitignored, do not edit.
//
// This is apps/streams-example-app's wrangler config, expanded from the root envs.ts
// (the typed map of every deployed environment). The top-level block is
// local dev; each "env" block below is one deployed environment, selected
// at build time via CLOUDFLARE_ENV (deploy.ts does this for you).
//
// Regenerate:      pnpm gen:wrangler   (vite dev/build do it automatically)
// Change an env:   edit envs.ts, not this file
// How it all fits: docs/devops-cloudflare-doppler.md
`;
  const rendered = header + JSON.stringify(config, null, 2) + "\n";
  const current = (() => {
    try {
      return readFileSync(CONFIG_PATH, "utf8");
    } catch {
      return null;
    }
  })();
  if (current !== rendered) writeFileSync(CONFIG_PATH, rendered);
  return CONFIG_PATH;
}

// Runs only when invoked directly — deploy.ts and vite.config.ts import
// from this module without triggering a write.
if (process.argv[1]?.endsWith("generate-wrangler-config.ts")) {
  console.log(`Wrote ${writeWranglerConfig()}`);
}
