/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppRoutesRouteImport } from './routes/_app/routes'
import { Route as AppDocsRouteImport } from './routes/_app/docs'
import { Route as AppDbRouteImport } from './routes/_app/db'
import { Route as AppConfigRouteImport } from './routes/_app/config'
import { Route as AppCaddyRouteImport } from './routes/_app/caddy'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutesRoute = AppRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppDbRoute = AppDbRouteImport.update({
  id: '/db',
  path: '/db',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigRoute = AppConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppRoute,
} as any)
const AppCaddyRoute = AppCaddyRouteImport.update({
  id: '/caddy',
  path: '/caddy',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/caddy': typeof AppCaddyRoute
  '/config': typeof AppConfigRoute
  '/db': typeof AppDbRoute
  '/docs': typeof AppDocsRoute
  '/routes': typeof AppRoutesRoute
}
export interface FileRoutesByTo {
  '/caddy': typeof AppCaddyRoute
  '/config': typeof AppConfigRoute
  '/db': typeof AppDbRoute
  '/docs': typeof AppDocsRoute
  '/routes': typeof AppRoutesRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/caddy': typeof AppCaddyRoute
  '/_app/config': typeof AppConfigRoute
  '/_app/db': typeof AppDbRoute
  '/_app/docs': typeof AppDocsRoute
  '/_app/routes': typeof AppRoutesRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/caddy' | '/config' | '/db' | '/docs' | '/routes'
  fileRoutesByTo: FileRoutesByTo
  to: '/caddy' | '/config' | '/db' | '/docs' | '/routes' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/caddy'
    | '/_app/config'
    | '/_app/db'
    | '/_app/docs'
    | '/_app/routes'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routes': {
      id: '/_app/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof AppRoutesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/docs': {
      id: '/_app/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/db': {
      id: '/_app/db'
      path: '/db'
      fullPath: '/db'
      preLoaderRoute: typeof AppDbRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config': {
      id: '/_app/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AppConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/caddy': {
      id: '/_app/caddy'
      path: '/caddy'
      fullPath: '/caddy'
      preLoaderRoute: typeof AppCaddyRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCaddyRoute: typeof AppCaddyRoute
  AppConfigRoute: typeof AppConfigRoute
  AppDbRoute: typeof AppDbRoute
  AppDocsRoute: typeof AppDocsRoute
  AppRoutesRoute: typeof AppRoutesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCaddyRoute: AppCaddyRoute,
  AppConfigRoute: AppConfigRoute,
  AppDbRoute: AppDbRoute,
  AppDocsRoute: AppDocsRoute,
  AppRoutesRoute: AppRoutesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
