// Generated by `sqlfu generate`. Do not edit.

export * from "./queries.sql.ts";

export const sqlfuQuerySources = [
  {
    sqlFile: "queries.sql",
    generatedFile: "queries.sql.ts",
    sourceSql:
      "-- Control-plane directory queries — the single source of vanilla SQL for the control plane.\n-- sqlfu best practice: one named query per statement (`/** @name x */`), `:named` bind params, explicit\n-- column lists (no SELECT *). `sqlfu generate` types these into sql/.generated/. Schema: ../definitions.sql.\n\n-- ── Users ────────────────────────────────────────────────────────────────────────────────────────────\n\n/** @name upsertUser */\nINSERT INTO users (id, email) VALUES (:id, :email)\nON CONFLICT(id) DO UPDATE SET email = excluded.email\nRETURNING id, email;\n\n-- ── Orgs + membership (access to a project = membership in its org) ───────────────────────────────────\n\n/** @name createOrg */\nINSERT INTO orgs (id, name) VALUES (:id, :name)\nRETURNING id, name;\n\n/** @name addOrgMember */\nINSERT INTO org_members (org_id, user_id, role) VALUES (:orgId, :userId, :role)\nON CONFLICT(org_id, user_id) DO NOTHING;\n\n/** @name listOrgsForUser */\nSELECT o.id, o.name, m.role\nFROM orgs o\nJOIN org_members m ON m.org_id = o.id\nWHERE m.user_id = :userId\nORDER BY o.name ASC;\n\n-- ── Projects (the id is ONE DNS-safe name — the directory row, the DO, and the host label) ──────────\n\n/** @name createProject */\nINSERT INTO projects (id, org_id) VALUES (:id, :orgId)\nON CONFLICT DO NOTHING;\n\n/** @name getProject */\nSELECT id, org_id FROM projects WHERE id = :id;\n\n/** @name listProjectsForUser */\nSELECT p.id, p.org_id, m.role\nFROM projects p\nJOIN org_members m ON m.org_id = p.org_id\nWHERE m.user_id = :userId\nORDER BY p.id ASC;\n",
  },
];
