// Generated by `sqlfu generate`. Do not edit.
// Row types for every table and view in your project's schema.

export type OrgMembersRow = {
  org_id: string;
  user_id: string;
  role: string;
  created_at: string;
};

export type OrgsRow = {
  id: string;
  name: string;
  created_at: string;
};

export type ProjectsRow = {
  id: string;
  org_id: string;
  created_at: string;
};

export type UsersRow = {
  id: string;
  email: string;
  created_at: string;
};
