packages:
  - apps/*
  - packages/*
  - estates/*
  - estates/*/apps/*
  - vibe-rules
  - e2e
  - .github/ts-workflows
  # DEPRECATED: apps/os is deprecated in favor of apps/os2. These paths are kept for backwards compatibility.
  - apps/os/backend/sandbox/scripts
  - apps/os/build-manager

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - drizzle-kit
  - miniflare
  - wrangler
  - '@cloudflare/sandbox'
  - alchemy
  - '@mmkal/jsonata'
  - '@mmkal/json-schema-to-typescript'
  - '@mariozechner/pi-ai'
  - '@mariozechner/pi-coding-agent'
  - '@mariozechner/pi-agent-core'
  - '@mariozechner/pi-tui'

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - workerd

overrides:
  # x402,viem are optional peer dependencies of agents sdk, which is source of lot of unnecessary/deprecated packages, removing them is fine
  'agents>x402': '-'
  'agents>viem': '-'
  'quicktype-core>readable-stream': 'npm:vite-compatible-readable-stream@3.6.1'
  'better-sqlite3': 'npm:libsql@0.5.22'
