packages:
  - apps/*
  - packages/*
  - estates/*
  - estates/*/apps/*
  - vibe-rules
  - .github/ts-workflows

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - drizzle-kit
  - miniflare
  - wrangler
  - '@cloudflare/sandbox'
  - alchemy
  - '@mmkal/jsonata'

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - workerd
