packages:
  - apps/*
  - packages/*
  - estates/*
  - estates/*/apps/*
  - vibe-rules
  - .github/ts-workflows
  - apps/os/backend/sandbox/scripts
  - apps/os/build-manager

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - drizzle-kit
  - miniflare
  - wrangler
  - '@cloudflare/sandbox'
  - alchemy
  - '@mmkal/jsonata'
  - '@mmkal/json-schema-to-typescript'
  - '@mariozechner/pi-ai'
  - '@mariozechner/pi-coding-agent'
  - '@mariozechner/pi-agent-core'
  - '@mariozechner/pi-tui'

onlyBuiltDependencies: node-pty

overrides:
  agents>viem: '-'
  agents>x402: '-'
  better-sqlite3: npm:libsql@0.5.22
  quicktype-core>readable-stream: npm:vite-compatible-readable-stream@3.6.1
