packages:
  - apps/*
  - packages/*
  - estates/*
  - estates/*/apps/*
  - vibe-rules
  - .github/ts-workflows

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - drizzle-kit
  - miniflare
  - wrangler
  - '@cloudflare/sandbox'
  - alchemy
  - '@mmkal/jsonata'

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - workerd

autoInstallPeers: false

overrides:
  # x402,viem are optional peer dependencies of agents sdk, which is source of lot of unnecessary/deprecated packages, removing them is fine
  'agents>x402': '-'
  'agents>viem': '-'
