/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/root.tsx'
import { Route as loginRouteImport } from './routes/login.tsx'
import { Route as authRequiredDotlayoutRouteImport } from './routes/auth-required.layout.tsx'
import { Route as newOrganizationRouteImport } from './routes/new-organization.tsx'
import { Route as adminLayoutRouteImport } from './routes/admin/layout.tsx'
import { Route as orgLayoutRouteImport } from './routes/org/layout.tsx'
import { Route as indexRouteImport } from './routes/index.tsx'
import { Route as adminIndexRouteImport } from './routes/admin/index.tsx'
import { Route as orgIndexRouteImport } from './routes/org/index.tsx'
import { Route as adminTrpcToolsRouteImport } from './routes/admin/trpc-tools.tsx'
import { Route as adminSessionInfoRouteImport } from './routes/admin/session-info.tsx'
import { Route as orgTeamRouteImport } from './routes/org/team.tsx'
import { Route as orgSettingsRouteImport } from './routes/org/settings.tsx'
import { Route as orgConnectorsRouteImport } from './routes/org/connectors.tsx'
import { Route as orgProjectLayoutRouteImport } from './routes/org/project/layout.tsx'
import { Route as orgProjectIndexRouteImport } from './routes/org/project/index.tsx'

const loginRoute = loginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authRequiredDotlayoutRoute = authRequiredDotlayoutRouteImport.update({
  id: '/_auth.layout',
  getParentRoute: () => rootRouteImport,
} as any)
const newOrganizationRoute = newOrganizationRouteImport.update({
  id: '/new-organization',
  path: '/new-organization',
  getParentRoute: () => authRequiredDotlayoutRoute,
} as any)
const adminLayoutRoute = adminLayoutRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => authRequiredDotlayoutRoute,
} as any)
const orgLayoutRoute = orgLayoutRouteImport.update({
  id: '/$organizationSlug',
  path: '/$organizationSlug',
  getParentRoute: () => authRequiredDotlayoutRoute,
} as any)
const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authRequiredDotlayoutRoute,
} as any)
const adminIndexRoute = adminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => adminLayoutRoute,
} as any)
const orgIndexRoute = orgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => orgLayoutRoute,
} as any)
const adminTrpcToolsRoute = adminTrpcToolsRouteImport.update({
  id: '/trpc-tools',
  path: '/trpc-tools',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminSessionInfoRoute = adminSessionInfoRouteImport.update({
  id: '/session-info',
  path: '/session-info',
  getParentRoute: () => adminLayoutRoute,
} as any)
const orgTeamRoute = orgTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => orgLayoutRoute,
} as any)
const orgSettingsRoute = orgSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => orgLayoutRoute,
} as any)
const orgConnectorsRoute = orgConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => orgLayoutRoute,
} as any)
const orgProjectLayoutRoute = orgProjectLayoutRouteImport.update({
  id: '/$projectSlug',
  path: '/$projectSlug',
  getParentRoute: () => orgLayoutRoute,
} as any)
const orgProjectIndexRoute = orgProjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => orgProjectLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof loginRoute
  '/': typeof indexRoute
  '/$organizationSlug': typeof orgLayoutRouteWithChildren
  '/admin': typeof adminLayoutRouteWithChildren
  '/new-organization': typeof newOrganizationRoute
  '/$organizationSlug/$projectSlug': typeof orgProjectLayoutRouteWithChildren
  '/$organizationSlug/connectors': typeof orgConnectorsRoute
  '/$organizationSlug/settings': typeof orgSettingsRoute
  '/$organizationSlug/team': typeof orgTeamRoute
  '/admin/session-info': typeof adminSessionInfoRoute
  '/admin/trpc-tools': typeof adminTrpcToolsRoute
  '/$organizationSlug/': typeof orgIndexRoute
  '/admin/': typeof adminIndexRoute
  '/$organizationSlug/$projectSlug/': typeof orgProjectIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof loginRoute
  '/': typeof indexRoute
  '/new-organization': typeof newOrganizationRoute
  '/$organizationSlug/connectors': typeof orgConnectorsRoute
  '/$organizationSlug/settings': typeof orgSettingsRoute
  '/$organizationSlug/team': typeof orgTeamRoute
  '/admin/session-info': typeof adminSessionInfoRoute
  '/admin/trpc-tools': typeof adminTrpcToolsRoute
  '/$organizationSlug': typeof orgIndexRoute
  '/admin': typeof adminIndexRoute
  '/$organizationSlug/$projectSlug': typeof orgProjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth.layout': typeof authRequiredDotlayoutRouteWithChildren
  '/login': typeof loginRoute
  '/_auth.layout/': typeof indexRoute
  '/_auth.layout/$organizationSlug': typeof orgLayoutRouteWithChildren
  '/_auth.layout/admin': typeof adminLayoutRouteWithChildren
  '/_auth.layout/new-organization': typeof newOrganizationRoute
  '/_auth.layout/$organizationSlug/$projectSlug': typeof orgProjectLayoutRouteWithChildren
  '/_auth.layout/$organizationSlug/connectors': typeof orgConnectorsRoute
  '/_auth.layout/$organizationSlug/settings': typeof orgSettingsRoute
  '/_auth.layout/$organizationSlug/team': typeof orgTeamRoute
  '/_auth.layout/admin/session-info': typeof adminSessionInfoRoute
  '/_auth.layout/admin/trpc-tools': typeof adminTrpcToolsRoute
  '/_auth.layout/$organizationSlug/': typeof orgIndexRoute
  '/_auth.layout/admin/': typeof adminIndexRoute
  '/_auth.layout/$organizationSlug/$projectSlug/': typeof orgProjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/$organizationSlug'
    | '/admin'
    | '/new-organization'
    | '/$organizationSlug/$projectSlug'
    | '/$organizationSlug/connectors'
    | '/$organizationSlug/settings'
    | '/$organizationSlug/team'
    | '/admin/session-info'
    | '/admin/trpc-tools'
    | '/$organizationSlug/'
    | '/admin/'
    | '/$organizationSlug/$projectSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/new-organization'
    | '/$organizationSlug/connectors'
    | '/$organizationSlug/settings'
    | '/$organizationSlug/team'
    | '/admin/session-info'
    | '/admin/trpc-tools'
    | '/$organizationSlug'
    | '/admin'
    | '/$organizationSlug/$projectSlug'
  id:
    | '__root__'
    | '/_auth.layout'
    | '/login'
    | '/_auth.layout/'
    | '/_auth.layout/$organizationSlug'
    | '/_auth.layout/admin'
    | '/_auth.layout/new-organization'
    | '/_auth.layout/$organizationSlug/$projectSlug'
    | '/_auth.layout/$organizationSlug/connectors'
    | '/_auth.layout/$organizationSlug/settings'
    | '/_auth.layout/$organizationSlug/team'
    | '/_auth.layout/admin/session-info'
    | '/_auth.layout/admin/trpc-tools'
    | '/_auth.layout/$organizationSlug/'
    | '/_auth.layout/admin/'
    | '/_auth.layout/$organizationSlug/$projectSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRequiredDotlayoutRoute: typeof authRequiredDotlayoutRouteWithChildren
  loginRoute: typeof loginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof loginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth.layout': {
      id: '/_auth.layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRequiredDotlayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth.layout/new-organization': {
      id: '/_auth.layout/new-organization'
      path: '/new-organization'
      fullPath: '/new-organization'
      preLoaderRoute: typeof newOrganizationRouteImport
      parentRoute: typeof authRequiredDotlayoutRoute
    }
    '/_auth.layout/admin': {
      id: '/_auth.layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof adminLayoutRouteImport
      parentRoute: typeof authRequiredDotlayoutRoute
    }
    '/_auth.layout/$organizationSlug': {
      id: '/_auth.layout/$organizationSlug'
      path: '/$organizationSlug'
      fullPath: '/$organizationSlug'
      preLoaderRoute: typeof orgLayoutRouteImport
      parentRoute: typeof authRequiredDotlayoutRoute
    }
    '/_auth.layout/': {
      id: '/_auth.layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexRouteImport
      parentRoute: typeof authRequiredDotlayoutRoute
    }
    '/_auth.layout/admin/': {
      id: '/_auth.layout/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof adminIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/_auth.layout/$organizationSlug/': {
      id: '/_auth.layout/$organizationSlug/'
      path: '/'
      fullPath: '/$organizationSlug/'
      preLoaderRoute: typeof orgIndexRouteImport
      parentRoute: typeof orgLayoutRoute
    }
    '/_auth.layout/admin/trpc-tools': {
      id: '/_auth.layout/admin/trpc-tools'
      path: '/trpc-tools'
      fullPath: '/admin/trpc-tools'
      preLoaderRoute: typeof adminTrpcToolsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/_auth.layout/admin/session-info': {
      id: '/_auth.layout/admin/session-info'
      path: '/session-info'
      fullPath: '/admin/session-info'
      preLoaderRoute: typeof adminSessionInfoRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/_auth.layout/$organizationSlug/team': {
      id: '/_auth.layout/$organizationSlug/team'
      path: '/team'
      fullPath: '/$organizationSlug/team'
      preLoaderRoute: typeof orgTeamRouteImport
      parentRoute: typeof orgLayoutRoute
    }
    '/_auth.layout/$organizationSlug/settings': {
      id: '/_auth.layout/$organizationSlug/settings'
      path: '/settings'
      fullPath: '/$organizationSlug/settings'
      preLoaderRoute: typeof orgSettingsRouteImport
      parentRoute: typeof orgLayoutRoute
    }
    '/_auth.layout/$organizationSlug/connectors': {
      id: '/_auth.layout/$organizationSlug/connectors'
      path: '/connectors'
      fullPath: '/$organizationSlug/connectors'
      preLoaderRoute: typeof orgConnectorsRouteImport
      parentRoute: typeof orgLayoutRoute
    }
    '/_auth.layout/$organizationSlug/$projectSlug': {
      id: '/_auth.layout/$organizationSlug/$projectSlug'
      path: '/$projectSlug'
      fullPath: '/$organizationSlug/$projectSlug'
      preLoaderRoute: typeof orgProjectLayoutRouteImport
      parentRoute: typeof orgLayoutRoute
    }
    '/_auth.layout/$organizationSlug/$projectSlug/': {
      id: '/_auth.layout/$organizationSlug/$projectSlug/'
      path: '/'
      fullPath: '/$organizationSlug/$projectSlug/'
      preLoaderRoute: typeof orgProjectIndexRouteImport
      parentRoute: typeof orgProjectLayoutRoute
    }
  }
}

interface orgProjectLayoutRouteChildren {
  orgProjectIndexRoute: typeof orgProjectIndexRoute
}

const orgProjectLayoutRouteChildren: orgProjectLayoutRouteChildren = {
  orgProjectIndexRoute: orgProjectIndexRoute,
}

const orgProjectLayoutRouteWithChildren =
  orgProjectLayoutRoute._addFileChildren(orgProjectLayoutRouteChildren)

interface orgLayoutRouteChildren {
  orgProjectLayoutRoute: typeof orgProjectLayoutRouteWithChildren
  orgConnectorsRoute: typeof orgConnectorsRoute
  orgSettingsRoute: typeof orgSettingsRoute
  orgTeamRoute: typeof orgTeamRoute
  orgIndexRoute: typeof orgIndexRoute
}

const orgLayoutRouteChildren: orgLayoutRouteChildren = {
  orgProjectLayoutRoute: orgProjectLayoutRouteWithChildren,
  orgConnectorsRoute: orgConnectorsRoute,
  orgSettingsRoute: orgSettingsRoute,
  orgTeamRoute: orgTeamRoute,
  orgIndexRoute: orgIndexRoute,
}

const orgLayoutRouteWithChildren = orgLayoutRoute._addFileChildren(
  orgLayoutRouteChildren,
)

interface adminLayoutRouteChildren {
  adminSessionInfoRoute: typeof adminSessionInfoRoute
  adminTrpcToolsRoute: typeof adminTrpcToolsRoute
  adminIndexRoute: typeof adminIndexRoute
}

const adminLayoutRouteChildren: adminLayoutRouteChildren = {
  adminSessionInfoRoute: adminSessionInfoRoute,
  adminTrpcToolsRoute: adminTrpcToolsRoute,
  adminIndexRoute: adminIndexRoute,
}

const adminLayoutRouteWithChildren = adminLayoutRoute._addFileChildren(
  adminLayoutRouteChildren,
)

interface authRequiredDotlayoutRouteChildren {
  indexRoute: typeof indexRoute
  orgLayoutRoute: typeof orgLayoutRouteWithChildren
  adminLayoutRoute: typeof adminLayoutRouteWithChildren
  newOrganizationRoute: typeof newOrganizationRoute
}

const authRequiredDotlayoutRouteChildren: authRequiredDotlayoutRouteChildren = {
  indexRoute: indexRoute,
  orgLayoutRoute: orgLayoutRouteWithChildren,
  adminLayoutRoute: adminLayoutRouteWithChildren,
  newOrganizationRoute: newOrganizationRoute,
}

const authRequiredDotlayoutRouteWithChildren =
  authRequiredDotlayoutRoute._addFileChildren(
    authRequiredDotlayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  authRequiredDotlayoutRoute: authRequiredDotlayoutRouteWithChildren,
  loginRoute: loginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
