/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/root.tsx'
import { Route as loginRouteImport } from './routes/login.tsx'
import { Route as authRequiredDotlayoutRouteImport } from './routes/auth-required.layout.tsx'
import { Route as newOrganizationRouteImport } from './routes/new-organization.tsx'
import { Route as indexRouteImport } from './routes/index.tsx'
import { Route as userSettingsRouteImport } from './routes/user/settings.tsx'
import { Route as adminLayoutRouteImport } from './routes/admin/layout.tsx'
import { Route as orgLayoutRouteImport } from './routes/org/layout.tsx'
import { Route as adminIndexRouteImport } from './routes/admin/index.tsx'
import { Route as orgIndexRouteImport } from './routes/org/index.tsx'
import { Route as adminTrpcToolsRouteImport } from './routes/admin/trpc-tools.tsx'
import { Route as adminSessionInfoRouteImport } from './routes/admin/session-info.tsx'
import { Route as orgTeamRouteImport } from './routes/org/team.tsx'
import { Route as orgSettingsRouteImport } from './routes/org/settings.tsx'
import { Route as orgProjectLayoutRouteImport } from './routes/org/project/layout.tsx'
import { Route as orgProjectIndexRouteImport } from './routes/org/project/index.tsx'
import { Route as orgProjectConnectorsRouteImport } from './routes/org/project/connectors.tsx'

const AuthRequiredDotlayoutRouteImport = createFileRoute(
  '/_auth-required.layout/_',
)()
const AuthRequiredDotlayoutOrganizationSlugRouteImport = createFileRoute(
  '/_auth-required.layout/_/$organizationSlug/_',
)()

const loginRoute = loginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authRequiredDotlayoutRoute = authRequiredDotlayoutRouteImport.update({
  id: '/_auth-required.layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRequiredDotlayoutRoute = AuthRequiredDotlayoutRouteImport.update({
  id: '/_',
  getParentRoute: () => authRequiredDotlayoutRoute,
} as any)
const newOrganizationRoute = newOrganizationRouteImport.update({
  id: '/new-organization',
  path: '/new-organization',
  getParentRoute: () => authRequiredDotlayoutRoute,
} as any)
const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authRequiredDotlayoutRoute,
} as any)
const userSettingsRoute = userSettingsRouteImport.update({
  id: '/user/settings',
  path: '/user/settings',
  getParentRoute: () => authRequiredDotlayoutRoute,
} as any)
const adminLayoutRoute = adminLayoutRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRequiredDotlayoutRoute,
} as any)
const orgLayoutRoute = orgLayoutRouteImport.update({
  id: '/$organizationSlug',
  path: '/$organizationSlug',
  getParentRoute: () => AuthRequiredDotlayoutRoute,
} as any)
const AuthRequiredDotlayoutOrganizationSlugRoute =
  AuthRequiredDotlayoutOrganizationSlugRouteImport.update({
    id: '/_',
    getParentRoute: () => orgLayoutRoute,
  } as any)
const adminIndexRoute = adminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => adminLayoutRoute,
} as any)
const orgIndexRoute = orgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => orgLayoutRoute,
} as any)
const adminTrpcToolsRoute = adminTrpcToolsRouteImport.update({
  id: '/trpc-tools',
  path: '/trpc-tools',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminSessionInfoRoute = adminSessionInfoRouteImport.update({
  id: '/session-info',
  path: '/session-info',
  getParentRoute: () => adminLayoutRoute,
} as any)
const orgTeamRoute = orgTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => orgLayoutRoute,
} as any)
const orgSettingsRoute = orgSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => orgLayoutRoute,
} as any)
const orgProjectLayoutRoute = orgProjectLayoutRouteImport.update({
  id: '/$projectSlug',
  path: '/$projectSlug',
  getParentRoute: () => AuthRequiredDotlayoutOrganizationSlugRoute,
} as any)
const orgProjectIndexRoute = orgProjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => orgProjectLayoutRoute,
} as any)
const orgProjectConnectorsRoute = orgProjectConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => orgProjectLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof loginRoute
  '/': typeof indexRoute
  '/new-organization': typeof newOrganizationRoute
  '/$organizationSlug': typeof AuthRequiredDotlayoutOrganizationSlugRouteWithChildren
  '/admin': typeof adminLayoutRouteWithChildren
  '/user/settings': typeof userSettingsRoute
  '/$organizationSlug/settings': typeof orgSettingsRoute
  '/$organizationSlug/team': typeof orgTeamRoute
  '/admin/session-info': typeof adminSessionInfoRoute
  '/admin/trpc-tools': typeof adminTrpcToolsRoute
  '/$organizationSlug/': typeof orgIndexRoute
  '/admin/': typeof adminIndexRoute
  '/$organizationSlug/$projectSlug': typeof orgProjectLayoutRouteWithChildren
  '/$organizationSlug/$projectSlug/connectors': typeof orgProjectConnectorsRoute
  '/$organizationSlug/$projectSlug/': typeof orgProjectIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof loginRoute
  '/': typeof indexRoute
  '/new-organization': typeof newOrganizationRoute
  '/user/settings': typeof userSettingsRoute
  '/$organizationSlug/settings': typeof orgSettingsRoute
  '/$organizationSlug/team': typeof orgTeamRoute
  '/admin/session-info': typeof adminSessionInfoRoute
  '/admin/trpc-tools': typeof adminTrpcToolsRoute
  '/$organizationSlug': typeof AuthRequiredDotlayoutOrganizationSlugRouteWithChildren
  '/admin': typeof adminIndexRoute
  '/$organizationSlug/$projectSlug/connectors': typeof orgProjectConnectorsRoute
  '/$organizationSlug/$projectSlug': typeof orgProjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth-required.layout': typeof authRequiredDotlayoutRouteWithChildren
  '/login': typeof loginRoute
  '/_auth-required.layout/': typeof indexRoute
  '/_auth-required.layout/new-organization': typeof newOrganizationRoute
  '/_auth-required.layout/_': typeof AuthRequiredDotlayoutRouteWithChildren
  '/_auth-required.layout/_/$organizationSlug': typeof orgLayoutRouteWithChildren
  '/_auth-required.layout/_/admin': typeof adminLayoutRouteWithChildren
  '/_auth-required.layout/user/settings': typeof userSettingsRoute
  '/_auth-required.layout/_/$organizationSlug/settings': typeof orgSettingsRoute
  '/_auth-required.layout/_/$organizationSlug/team': typeof orgTeamRoute
  '/_auth-required.layout/_/admin/session-info': typeof adminSessionInfoRoute
  '/_auth-required.layout/_/admin/trpc-tools': typeof adminTrpcToolsRoute
  '/_auth-required.layout/_/$organizationSlug/': typeof orgIndexRoute
  '/_auth-required.layout/_/admin/': typeof adminIndexRoute
  '/_auth-required.layout/_/$organizationSlug/_': typeof AuthRequiredDotlayoutOrganizationSlugRouteWithChildren
  '/_auth-required.layout/_/$organizationSlug/_/$projectSlug': typeof orgProjectLayoutRouteWithChildren
  '/_auth-required.layout/_/$organizationSlug/_/$projectSlug/connectors': typeof orgProjectConnectorsRoute
  '/_auth-required.layout/_/$organizationSlug/_/$projectSlug/': typeof orgProjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/new-organization'
    | '/$organizationSlug'
    | '/admin'
    | '/user/settings'
    | '/$organizationSlug/settings'
    | '/$organizationSlug/team'
    | '/admin/session-info'
    | '/admin/trpc-tools'
    | '/$organizationSlug/'
    | '/admin/'
    | '/$organizationSlug/$projectSlug'
    | '/$organizationSlug/$projectSlug/connectors'
    | '/$organizationSlug/$projectSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/new-organization'
    | '/user/settings'
    | '/$organizationSlug/settings'
    | '/$organizationSlug/team'
    | '/admin/session-info'
    | '/admin/trpc-tools'
    | '/$organizationSlug'
    | '/admin'
    | '/$organizationSlug/$projectSlug/connectors'
    | '/$organizationSlug/$projectSlug'
  id:
    | '__root__'
    | '/_auth-required.layout'
    | '/login'
    | '/_auth-required.layout/'
    | '/_auth-required.layout/new-organization'
    | '/_auth-required.layout/_'
    | '/_auth-required.layout/_/$organizationSlug'
    | '/_auth-required.layout/_/admin'
    | '/_auth-required.layout/user/settings'
    | '/_auth-required.layout/_/$organizationSlug/settings'
    | '/_auth-required.layout/_/$organizationSlug/team'
    | '/_auth-required.layout/_/admin/session-info'
    | '/_auth-required.layout/_/admin/trpc-tools'
    | '/_auth-required.layout/_/$organizationSlug/'
    | '/_auth-required.layout/_/admin/'
    | '/_auth-required.layout/_/$organizationSlug/_'
    | '/_auth-required.layout/_/$organizationSlug/_/$projectSlug'
    | '/_auth-required.layout/_/$organizationSlug/_/$projectSlug/connectors'
    | '/_auth-required.layout/_/$organizationSlug/_/$projectSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRequiredDotlayoutRoute: typeof authRequiredDotlayoutRouteWithChildren
  loginRoute: typeof loginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof loginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-required.layout': {
      id: '/_auth-required.layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRequiredDotlayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-required.layout/_': {
      id: '/_auth-required.layout/_'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRequiredDotlayoutRouteImport
      parentRoute: typeof authRequiredDotlayoutRoute
    }
    '/_auth-required.layout/new-organization': {
      id: '/_auth-required.layout/new-organization'
      path: '/new-organization'
      fullPath: '/new-organization'
      preLoaderRoute: typeof newOrganizationRouteImport
      parentRoute: typeof authRequiredDotlayoutRoute
    }
    '/_auth-required.layout/': {
      id: '/_auth-required.layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexRouteImport
      parentRoute: typeof authRequiredDotlayoutRoute
    }
    '/_auth-required.layout/user/settings': {
      id: '/_auth-required.layout/user/settings'
      path: '/user/settings'
      fullPath: '/user/settings'
      preLoaderRoute: typeof userSettingsRouteImport
      parentRoute: typeof authRequiredDotlayoutRoute
    }
    '/_auth-required.layout/_/admin': {
      id: '/_auth-required.layout/_/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof adminLayoutRouteImport
      parentRoute: typeof AuthRequiredDotlayoutRoute
    }
    '/_auth-required.layout/_/$organizationSlug': {
      id: '/_auth-required.layout/_/$organizationSlug'
      path: '/$organizationSlug'
      fullPath: '/$organizationSlug'
      preLoaderRoute: typeof orgLayoutRouteImport
      parentRoute: typeof AuthRequiredDotlayoutRoute
    }
    '/_auth-required.layout/_/$organizationSlug/_': {
      id: '/_auth-required.layout/_/$organizationSlug/_'
      path: ''
      fullPath: '/$organizationSlug'
      preLoaderRoute: typeof AuthRequiredDotlayoutOrganizationSlugRouteImport
      parentRoute: typeof orgLayoutRoute
    }
    '/_auth-required.layout/_/admin/': {
      id: '/_auth-required.layout/_/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof adminIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/_auth-required.layout/_/$organizationSlug/': {
      id: '/_auth-required.layout/_/$organizationSlug/'
      path: '/'
      fullPath: '/$organizationSlug/'
      preLoaderRoute: typeof orgIndexRouteImport
      parentRoute: typeof orgLayoutRoute
    }
    '/_auth-required.layout/_/admin/trpc-tools': {
      id: '/_auth-required.layout/_/admin/trpc-tools'
      path: '/trpc-tools'
      fullPath: '/admin/trpc-tools'
      preLoaderRoute: typeof adminTrpcToolsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/_auth-required.layout/_/admin/session-info': {
      id: '/_auth-required.layout/_/admin/session-info'
      path: '/session-info'
      fullPath: '/admin/session-info'
      preLoaderRoute: typeof adminSessionInfoRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/_auth-required.layout/_/$organizationSlug/team': {
      id: '/_auth-required.layout/_/$organizationSlug/team'
      path: '/team'
      fullPath: '/$organizationSlug/team'
      preLoaderRoute: typeof orgTeamRouteImport
      parentRoute: typeof orgLayoutRoute
    }
    '/_auth-required.layout/_/$organizationSlug/settings': {
      id: '/_auth-required.layout/_/$organizationSlug/settings'
      path: '/settings'
      fullPath: '/$organizationSlug/settings'
      preLoaderRoute: typeof orgSettingsRouteImport
      parentRoute: typeof orgLayoutRoute
    }
    '/_auth-required.layout/_/$organizationSlug/_/$projectSlug': {
      id: '/_auth-required.layout/_/$organizationSlug/_/$projectSlug'
      path: '/$projectSlug'
      fullPath: '/$organizationSlug/$projectSlug'
      preLoaderRoute: typeof orgProjectLayoutRouteImport
      parentRoute: typeof AuthRequiredDotlayoutOrganizationSlugRoute
    }
    '/_auth-required.layout/_/$organizationSlug/_/$projectSlug/': {
      id: '/_auth-required.layout/_/$organizationSlug/_/$projectSlug/'
      path: '/'
      fullPath: '/$organizationSlug/$projectSlug/'
      preLoaderRoute: typeof orgProjectIndexRouteImport
      parentRoute: typeof orgProjectLayoutRoute
    }
    '/_auth-required.layout/_/$organizationSlug/_/$projectSlug/connectors': {
      id: '/_auth-required.layout/_/$organizationSlug/_/$projectSlug/connectors'
      path: '/connectors'
      fullPath: '/$organizationSlug/$projectSlug/connectors'
      preLoaderRoute: typeof orgProjectConnectorsRouteImport
      parentRoute: typeof orgProjectLayoutRoute
    }
  }
}

interface orgProjectLayoutRouteChildren {
  orgProjectConnectorsRoute: typeof orgProjectConnectorsRoute
  orgProjectIndexRoute: typeof orgProjectIndexRoute
}

const orgProjectLayoutRouteChildren: orgProjectLayoutRouteChildren = {
  orgProjectConnectorsRoute: orgProjectConnectorsRoute,
  orgProjectIndexRoute: orgProjectIndexRoute,
}

const orgProjectLayoutRouteWithChildren =
  orgProjectLayoutRoute._addFileChildren(orgProjectLayoutRouteChildren)

interface AuthRequiredDotlayoutOrganizationSlugRouteChildren {
  orgProjectLayoutRoute: typeof orgProjectLayoutRouteWithChildren
}

const AuthRequiredDotlayoutOrganizationSlugRouteChildren: AuthRequiredDotlayoutOrganizationSlugRouteChildren =
  {
    orgProjectLayoutRoute: orgProjectLayoutRouteWithChildren,
  }

const AuthRequiredDotlayoutOrganizationSlugRouteWithChildren =
  AuthRequiredDotlayoutOrganizationSlugRoute._addFileChildren(
    AuthRequiredDotlayoutOrganizationSlugRouteChildren,
  )

interface orgLayoutRouteChildren {
  orgSettingsRoute: typeof orgSettingsRoute
  orgTeamRoute: typeof orgTeamRoute
  orgIndexRoute: typeof orgIndexRoute
  AuthRequiredDotlayoutOrganizationSlugRoute: typeof AuthRequiredDotlayoutOrganizationSlugRouteWithChildren
}

const orgLayoutRouteChildren: orgLayoutRouteChildren = {
  orgSettingsRoute: orgSettingsRoute,
  orgTeamRoute: orgTeamRoute,
  orgIndexRoute: orgIndexRoute,
  AuthRequiredDotlayoutOrganizationSlugRoute:
    AuthRequiredDotlayoutOrganizationSlugRouteWithChildren,
}

const orgLayoutRouteWithChildren = orgLayoutRoute._addFileChildren(
  orgLayoutRouteChildren,
)

interface adminLayoutRouteChildren {
  adminSessionInfoRoute: typeof adminSessionInfoRoute
  adminTrpcToolsRoute: typeof adminTrpcToolsRoute
  adminIndexRoute: typeof adminIndexRoute
}

const adminLayoutRouteChildren: adminLayoutRouteChildren = {
  adminSessionInfoRoute: adminSessionInfoRoute,
  adminTrpcToolsRoute: adminTrpcToolsRoute,
  adminIndexRoute: adminIndexRoute,
}

const adminLayoutRouteWithChildren = adminLayoutRoute._addFileChildren(
  adminLayoutRouteChildren,
)

interface AuthRequiredDotlayoutRouteChildren {
  orgLayoutRoute: typeof orgLayoutRouteWithChildren
  adminLayoutRoute: typeof adminLayoutRouteWithChildren
}

const AuthRequiredDotlayoutRouteChildren: AuthRequiredDotlayoutRouteChildren = {
  orgLayoutRoute: orgLayoutRouteWithChildren,
  adminLayoutRoute: adminLayoutRouteWithChildren,
}

const AuthRequiredDotlayoutRouteWithChildren =
  AuthRequiredDotlayoutRoute._addFileChildren(
    AuthRequiredDotlayoutRouteChildren,
  )

interface authRequiredDotlayoutRouteChildren {
  indexRoute: typeof indexRoute
  newOrganizationRoute: typeof newOrganizationRoute
  AuthRequiredDotlayoutRoute: typeof AuthRequiredDotlayoutRouteWithChildren
  userSettingsRoute: typeof userSettingsRoute
}

const authRequiredDotlayoutRouteChildren: authRequiredDotlayoutRouteChildren = {
  indexRoute: indexRoute,
  newOrganizationRoute: newOrganizationRoute,
  AuthRequiredDotlayoutRoute: AuthRequiredDotlayoutRouteWithChildren,
  userSettingsRoute: userSettingsRoute,
}

const authRequiredDotlayoutRouteWithChildren =
  authRequiredDotlayoutRoute._addFileChildren(
    authRequiredDotlayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  authRequiredDotlayoutRoute: authRequiredDotlayoutRouteWithChildren,
  loginRoute: loginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
