/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as LayoutLessTerminalRouteImport } from './routes/_layout-less/terminal'
import { Route as AppAgentsIndexRouteImport } from './routes/_app/agents/index'
import { Route as AppAgentsNewRouteImport } from './routes/_app/agents/new'
import { Route as AppAgentsSlugRouteImport } from './routes/_app/agents/$slug'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const LayoutLessTerminalRoute = LayoutLessTerminalRouteImport.update({
  id: '/_layout-less/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentsIndexRoute = AppAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsNewRoute = AppAgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsSlugRoute = AppAgentsSlugRouteImport.update({
  id: '/agents/$slug',
  path: '/agents/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/terminal': typeof LayoutLessTerminalRoute
  '/': typeof AppIndexRoute
  '/agents/$slug': typeof AppAgentsSlugRoute
  '/agents/new': typeof AppAgentsNewRoute
  '/agents': typeof AppAgentsIndexRoute
}
export interface FileRoutesByTo {
  '/terminal': typeof LayoutLessTerminalRoute
  '/': typeof AppIndexRoute
  '/agents/$slug': typeof AppAgentsSlugRoute
  '/agents/new': typeof AppAgentsNewRoute
  '/agents': typeof AppAgentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_layout-less/terminal': typeof LayoutLessTerminalRoute
  '/_app/': typeof AppIndexRoute
  '/_app/agents/$slug': typeof AppAgentsSlugRoute
  '/_app/agents/new': typeof AppAgentsNewRoute
  '/_app/agents/': typeof AppAgentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/terminal' | '/' | '/agents/$slug' | '/agents/new' | '/agents'
  fileRoutesByTo: FileRoutesByTo
  to: '/terminal' | '/' | '/agents/$slug' | '/agents/new' | '/agents'
  id:
    | '__root__'
    | '/_app'
    | '/_layout-less/terminal'
    | '/_app/'
    | '/_app/agents/$slug'
    | '/_app/agents/new'
    | '/_app/agents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LayoutLessTerminalRoute: typeof LayoutLessTerminalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_layout-less/terminal': {
      id: '/_layout-less/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof LayoutLessTerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/agents/': {
      id: '/_app/agents/'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/new': {
      id: '/_app/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AppAgentsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/$slug': {
      id: '/_app/agents/$slug'
      path: '/agents/$slug'
      fullPath: '/agents/$slug'
      preLoaderRoute: typeof AppAgentsSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAgentsSlugRoute: typeof AppAgentsSlugRoute
  AppAgentsNewRoute: typeof AppAgentsNewRoute
  AppAgentsIndexRoute: typeof AppAgentsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAgentsSlugRoute: AppAgentsSlugRoute,
  AppAgentsNewRoute: AppAgentsNewRoute,
  AppAgentsIndexRoute: AppAgentsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LayoutLessTerminalRoute: LayoutLessTerminalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
