// Generated by `sqlfu generate`. Do not edit.

export * from "./queries.sql.ts";

export const sqlfuQuerySources = [
  {
    sqlFile: "queries.sql",
    generatedFile: "queries.sql.ts",
    sourceSql:
      "/** @name deleteLeaseBySlug */\nDELETE FROM leases\nWHERE slug = :slug;\n\n/** @name deleteLeaseBySlugAndLeaseId */\nDELETE FROM leases\nWHERE slug = :slug AND lease_id = :leaseId;\n\n/** @name insertCoordinatorType */\nINSERT OR REPLACE INTO metadata (key, value)\nVALUES ('type', :type);\n\n/** @name insertEvent */\nINSERT INTO events (occurred_at, event, slug, payload)\nVALUES (:occurredAt, :event, :slug, :payload);\n\n/** @name insertLease */\nINSERT INTO leases (slug, lease_id, expires_at, created_at)\nVALUES (:slug, :leaseId, :expiresAt, :createdAt);\n\n/** @name selectActiveLeaseSlugs */\nSELECT slug\nFROM leases;\n\n/** @name selectCoordinatorType */\nSELECT value\nFROM metadata\nWHERE key = 'type';\n\n/** @name selectExpiredLeases */\nSELECT slug, lease_id, expires_at\nFROM leases\nWHERE expires_at <= :now\nORDER BY expires_at ASC;\n\n/** @name selectLeaseCountBySlug */\nSELECT COUNT(*) AS count\nFROM leases\nWHERE slug = :slug;\n\n/** @name selectLeaseIdBySlug */\nSELECT lease_id\nFROM leases\nWHERE slug = :slug;\n\n/** @name selectLeaseBySlug */\nSELECT lease_id, expires_at\nFROM leases\nWHERE slug = :slug;\n\n/** @name selectNextLease */\nSELECT expires_at\nFROM leases\nORDER BY expires_at ASC\nLIMIT 1;\n\n/** @name updateLeaseExpires */\nUPDATE leases\nSET expires_at = :expiresAt\nWHERE slug = :slug AND lease_id = :leaseId;\n",
  },
];
