// Generated by `sqlfu generate`. Do not edit.
// A bundle of every migration in src/control-plane/db/migrations/,
// importable from runtimes without filesystem access (durable objects, edge workers, browsers).
// Use `migrate(client)` for the common path, or `migrations` for lower-level control.

import {applyMigrations, migrationsFromBundle, type AsyncClient, type Client, type SyncClient} from 'sqlfu';

export const migrations = {
  "src/control-plane/db/migrations/0000_control_plane.sql": "create table users (\n  id text primary key,\n  email text not null unique\n);\n\ncreate table identities (\n  provider text not null,\n  subject text not null,\n  user_id text not null references users (id),\n  primary key (provider, subject),\n  unique (provider, user_id)\n);\n\ncreate table organizations (\n  id text primary key,\n  name text not null\n);\n\ncreate table memberships (\n  org_id text not null references organizations (id) on delete cascade,\n  user_id text not null references users (id),\n  role text not null check (role in ('owner', 'member')),\n  primary key (org_id, user_id)\n);\ncreate index memberships_user on memberships (user_id);\n\ncreate table projects (\n  id text primary key,\n  slug text not null unique,\n  org_id text not null references organizations (id)\n);\ncreate index projects_org on projects (org_id);\n\ncreate table invitations (\n  id text primary key,\n  token_hash text not null unique,\n  org_id text not null references organizations (id) on delete cascade,\n  role text not null check (role in ('owner', 'member')),\n  email_hint text,\n  created_by text not null,\n  created_at integer not null,\n  expires_at integer not null,\n  revoked_at integer,\n  accepted_by text,\n  accepted_at integer,\n  acceptance_id text\n);\ncreate index invitations_org on invitations (org_id);\n\ncreate table project_hostnames (\n  hostname text primary key,\n  project_id text not null\n);\ncreate index project_hostnames_project on project_hostnames (project_id);\n\ncreate table project_primary_hostnames (\n  project_id text primary key,\n  hostname text not null\n);\n\ncreate table oauth_grants (\n  key text primary key,\n  value text not null,\n  expires_at integer\n);\ncreate index oauth_grants_expiry on oauth_grants (expires_at);\n",
  "src/control-plane/db/migrations/0001_integration_routes.sql": "-- THE INTEGRATION ROUTES: where a webhook the platform's own app at a provider receives goes\n-- (src/integrations/). An account there (a Slack team, a GitHub installation) is ONE connection's,\n-- the log at `path` in `project_id`; a connection holds one account (catalog.ts `routeIntegration`).\ncreate table integration_routes (\n  provider text not null,\n  external_id text not null,\n  project_id text not null,\n  path text not null,\n  primary key (provider, external_id)\n);\ncreate index integration_routes_connection on integration_routes (project_id, path);\n",
  "src/control-plane/db/migrations/0002_identities_added_at.sql": "-- WHEN A PERSON ADDED A SIGN-IN to their own account (catalog.ts `addIdentity`): null for every\n-- identity a sign-in linked, which is every one before this column.\nalter table identities add column added_at integer;\n",
  "src/control-plane/db/migrations/0003_added_sign_in_keeps_email.sql": "-- A person with a sign-in they added keeps their email: the address an added sign-in's provider\n-- reports is never theirs (catalog.ts `linkIdentity` never writes it), and this refuses the write\n-- from anything else, such as a version of the platform older than `added_at`. An operator who\n-- must change such an email clears the identity's `added_at` first.\n-- BEGIN and END in capitals: D1's query API finds the end of a trigger only so, and answers a\n-- lowercase one \"incomplete input\".\ncreate trigger users_email_kept_by_added_sign_in\nbefore update of email on users\nwhen new.email <> old.email\n  and exists (select 1 from identities i where i.user_id = old.id and i.added_at is not null)\nBEGIN\n  select raise(abort, 'a person with an added sign-in keeps their email');\nEND;\n",
};

export function migrate(client: SyncClient): void;
export function migrate(client: AsyncClient): Promise<void>;
export function migrate(client: Client): void | Promise<void> {
  return applyMigrations(client, {
    migrations: migrationsFromBundle(migrations),
    preset: "d1",
  });
}

export type MigrationBundle = typeof migrations;
