// Auto-generated by scripts/generate-queries.ts from sql/queries.sql. Do not edit manually.

import type { D1Database, D1PreparedStatement } from "@cloudflare/workers-types";

export type DeleteRouteByIdParams = {
  routeId: string;
};

export type DeleteRouteByIdResult = {
  changes: number;
};

export function deleteRouteByIdStmt(
  db: D1Database,
  params: DeleteRouteByIdParams,
): D1PreparedStatement {
  const sql = `
	DELETE FROM routes
	WHERE id = ?
	
	`;
  return db.prepare(sql).bind(params.routeId);
}

export async function deleteRouteById(
  db: D1Database,
  params: DeleteRouteByIdParams,
): Promise<DeleteRouteByIdResult> {
  return deleteRouteByIdStmt(db, params)
    .run()
    .then((res) => res.meta);
}

export type DeleteRouteByExternalIdParams = {
  externalId: string;
};

export type DeleteRouteByExternalIdResult = {
  changes: number;
};

export function deleteRouteByExternalIdStmt(
  db: D1Database,
  params: DeleteRouteByExternalIdParams,
): D1PreparedStatement {
  const sql = `
	DELETE FROM routes
	WHERE external_id = ?
	
	`;
  return db.prepare(sql).bind(params.externalId);
}

export async function deleteRouteByExternalId(
  db: D1Database,
  params: DeleteRouteByExternalIdParams,
): Promise<DeleteRouteByExternalIdResult> {
  return deleteRouteByExternalIdStmt(db, params)
    .run()
    .then((res) => res.meta);
}

export type DeleteRoutePatternsByRouteIdParams = {
  routeId: string;
};

export type DeleteRoutePatternsByRouteIdResult = {
  changes: number;
};

export function deleteRoutePatternsByRouteIdStmt(
  db: D1Database,
  params: DeleteRoutePatternsByRouteIdParams,
): D1PreparedStatement {
  const sql = `
	DELETE FROM route_patterns
	WHERE route_id = ?
	
	`;
  return db.prepare(sql).bind(params.routeId);
}

export async function deleteRoutePatternsByRouteId(
  db: D1Database,
  params: DeleteRoutePatternsByRouteIdParams,
): Promise<DeleteRoutePatternsByRouteIdResult> {
  return deleteRoutePatternsByRouteIdStmt(db, params)
    .run()
    .then((res) => res.meta);
}

export type InsertRoutePatternParams = {
  routeId: string;
  pattern: string;
  target: string;
  headers: string;
};

export type InsertRoutePatternResult = {
  changes: number;
  last_row_id: number;
};

export function insertRoutePatternStmt(
  db: D1Database,
  params: InsertRoutePatternParams,
): D1PreparedStatement {
  const sql = `
	INSERT INTO route_patterns (route_id, pattern, target, headers)
	VALUES (?, ?, ?, ?)
	
	`;
  return db.prepare(sql).bind(params.routeId, params.pattern, params.target, params.headers);
}

export async function insertRoutePattern(
  db: D1Database,
  params: InsertRoutePatternParams,
): Promise<InsertRoutePatternResult> {
  return insertRoutePatternStmt(db, params)
    .run()
    .then((res) => res.meta);
}

export type InsertRouteParams = {
  routeId: string;
  externalId: string | null;
  metadata: string;
};

export type InsertRouteResult = {
  changes: number;
  last_row_id: number;
};

export function insertRouteStmt(db: D1Database, params: InsertRouteParams): D1PreparedStatement {
  const sql = `
	INSERT INTO routes (id, external_id, metadata)
	VALUES (?, ?, ?)
	
	`;
  return db.prepare(sql).bind(params.routeId, params.externalId, params.metadata);
}

export async function insertRoute(
  db: D1Database,
  params: InsertRouteParams,
): Promise<InsertRouteResult> {
  return insertRouteStmt(db, params)
    .run()
    .then((res) => res.meta);
}

export type SelectResolvedRouteByHostParams = {
  host: string;
};

export type SelectResolvedRouteByHostResult = {
  routeId: string;
  pattern: string;
  target: string;
  headers: string;
  metadata: string;
};

export function selectResolvedRouteByHostStmt(
  db: D1Database,
  params: SelectResolvedRouteByHostParams,
): D1PreparedStatement {
  const sql = `
	SELECT
	  rp.route_id AS routeId,
	  rp.pattern AS pattern,
	  rp.target AS target,
	  rp.headers AS headers,
	  r.metadata AS metadata
	FROM route_patterns rp
	INNER JOIN routes r ON r.id = rp.route_id
	WHERE length(rp.pattern) <= 253
	  AND ? GLOB rp.pattern
	ORDER BY
	  CASE WHEN rp.pattern NOT LIKE '%*%' THEN 1 ELSE 0 END DESC,
	  length(rp.pattern) DESC,
	  rp.id ASC
	LIMIT 1
	
	`;
  return db.prepare(sql).bind(params.host);
}

export async function selectResolvedRouteByHost(
  db: D1Database,
  params: SelectResolvedRouteByHostParams,
): Promise<SelectResolvedRouteByHostResult | null> {
  return selectResolvedRouteByHostStmt(db, params)
    .raw({ columnNames: false })
    .then((rows) => (rows.length > 0 ? mapArrayToSelectResolvedRouteByHostResult(rows[0]) : null));
}

function mapArrayToSelectResolvedRouteByHostResult(data: any) {
  const result: SelectResolvedRouteByHostResult = {
    routeId: data[0],
    pattern: data[1],
    target: data[2],
    headers: data[3],
    metadata: data[4],
  };
  return result;
}

export type SelectRouteByIdParams = {
  routeId: string;
};

export type SelectRouteByIdResult = {
  id: string;
  external_id?: string;
  metadata: string;
  created_at: string;
  updated_at: string;
};

export function selectRouteByIdStmt(
  db: D1Database,
  params: SelectRouteByIdParams,
): D1PreparedStatement {
  const sql = `
	SELECT id, external_id, metadata, created_at, updated_at
	FROM routes
	WHERE id = ?
	
	`;
  return db.prepare(sql).bind(params.routeId);
}

export async function selectRouteById(
  db: D1Database,
  params: SelectRouteByIdParams,
): Promise<SelectRouteByIdResult[]> {
  return selectRouteByIdStmt(db, params)
    .raw({ columnNames: false })
    .then((rows) => rows.map((row) => mapArrayToSelectRouteByIdResult(row)));
}

function mapArrayToSelectRouteByIdResult(data: any) {
  const result: SelectRouteByIdResult = {
    id: data[0],
    external_id: data[1],
    metadata: data[2],
    created_at: data[3],
    updated_at: data[4],
  };
  return result;
}

export type SelectRoutePatternsByRouteIdParams = {
  routeId: string;
};

export type SelectRoutePatternsByRouteIdResult = {
  id: number;
  route_id: string;
  pattern: string;
  target: string;
  headers: string;
  created_at: string;
  updated_at: string;
};

export function selectRoutePatternsByRouteIdStmt(
  db: D1Database,
  params: SelectRoutePatternsByRouteIdParams,
): D1PreparedStatement {
  const sql = `
	SELECT id, route_id, pattern, target, headers, created_at, updated_at
	FROM route_patterns
	WHERE route_id = ?
	ORDER BY id ASC
	
	`;
  return db.prepare(sql).bind(params.routeId);
}

export async function selectRoutePatternsByRouteId(
  db: D1Database,
  params: SelectRoutePatternsByRouteIdParams,
): Promise<SelectRoutePatternsByRouteIdResult[]> {
  return selectRoutePatternsByRouteIdStmt(db, params)
    .raw({ columnNames: false })
    .then((rows) => rows.map((row) => mapArrayToSelectRoutePatternsByRouteIdResult(row)));
}

function mapArrayToSelectRoutePatternsByRouteIdResult(data: any) {
  const result: SelectRoutePatternsByRouteIdResult = {
    id: data[0],
    route_id: data[1],
    pattern: data[2],
    target: data[3],
    headers: data[4],
    created_at: data[5],
    updated_at: data[6],
  };
  return result;
}

export type SelectRoutePatternsResult = {
  id: number;
  route_id: string;
  pattern: string;
  target: string;
  headers: string;
  created_at: string;
  updated_at: string;
};

export function selectRoutePatternsStmt(db: D1Database): D1PreparedStatement {
  const sql = `
	SELECT id, route_id, pattern, target, headers, created_at, updated_at
	FROM route_patterns
	ORDER BY route_id ASC, id ASC
	
	`;
  return db.prepare(sql);
}

export async function selectRoutePatterns(db: D1Database): Promise<SelectRoutePatternsResult[]> {
  return selectRoutePatternsStmt(db)
    .raw({ columnNames: false })
    .then((rows) => rows.map((row) => mapArrayToSelectRoutePatternsResult(row)));
}

function mapArrayToSelectRoutePatternsResult(data: any) {
  const result: SelectRoutePatternsResult = {
    id: data[0],
    route_id: data[1],
    pattern: data[2],
    target: data[3],
    headers: data[4],
    created_at: data[5],
    updated_at: data[6],
  };
  return result;
}

export type SelectRoutesResult = {
  id: string;
  external_id?: string;
  metadata: string;
  created_at: string;
  updated_at: string;
};

export function selectRoutesStmt(db: D1Database): D1PreparedStatement {
  const sql = `
	SELECT id, external_id, metadata, created_at, updated_at
	FROM routes
	ORDER BY created_at ASC, id ASC
	
	`;
  return db.prepare(sql);
}

export async function selectRoutes(db: D1Database): Promise<SelectRoutesResult[]> {
  return selectRoutesStmt(db)
    .raw({ columnNames: false })
    .then((rows) => rows.map((row) => mapArrayToSelectRoutesResult(row)));
}

function mapArrayToSelectRoutesResult(data: any) {
  const result: SelectRoutesResult = {
    id: data[0],
    external_id: data[1],
    metadata: data[2],
    created_at: data[3],
    updated_at: data[4],
  };
  return result;
}

export type UpdateRouteByIdData = {
  metadata: string;
  externalId: string | null;
};

export type UpdateRouteByIdParams = {
  routeId: string;
};

export type UpdateRouteByIdResult = {
  changes: number;
};

export function updateRouteByIdStmt(
  db: D1Database,
  data: UpdateRouteByIdData,
  params: UpdateRouteByIdParams,
): D1PreparedStatement {
  const sql = `
	UPDATE routes
	SET metadata = ?, external_id = ?, updated_at = CURRENT_TIMESTAMP
	WHERE id = ?
	
	`;
  return db.prepare(sql).bind(data.metadata, data.externalId, params.routeId);
}

export async function updateRouteById(
  db: D1Database,
  data: UpdateRouteByIdData,
  params: UpdateRouteByIdParams,
): Promise<UpdateRouteByIdResult> {
  return updateRouteByIdStmt(db, data, params)
    .run()
    .then((res) => res.meta);
}
