// Auto-generated by scripts/generate-queries.ts from sql/queries.sql. Do not edit manually.

import type { D1Database, D1PreparedStatement } from "@cloudflare/workers-types";

export type DeleteRouteByIdParams = {
  routeId: string;
};

export type DeleteRouteByIdResult = {
  changes: number;
};

export function deleteRouteByIdStmt(
  db: D1Database,
  params: DeleteRouteByIdParams,
): D1PreparedStatement {
  const sql = `
	DELETE FROM routes
	WHERE id = ?
	
	`;
  return db.prepare(sql).bind(params.routeId);
}

export async function deleteRouteById(
  db: D1Database,
  params: DeleteRouteByIdParams,
): Promise<DeleteRouteByIdResult> {
  return deleteRouteByIdStmt(db, params)
    .run()
    .then((res) => res.meta);
}

export type DeleteRoutePatternsByRouteIdParams = {
  routeId: string;
};

export type DeleteRoutePatternsByRouteIdResult = {
  changes: number;
};

export function deleteRoutePatternsByRouteIdStmt(
  db: D1Database,
  params: DeleteRoutePatternsByRouteIdParams,
): D1PreparedStatement {
  const sql = `
	DELETE FROM route_patterns
	WHERE route_id = ?
	
	`;
  return db.prepare(sql).bind(params.routeId);
}

export async function deleteRoutePatternsByRouteId(
  db: D1Database,
  params: DeleteRoutePatternsByRouteIdParams,
): Promise<DeleteRoutePatternsByRouteIdResult> {
  return deleteRoutePatternsByRouteIdStmt(db, params)
    .run()
    .then((res) => res.meta);
}

export type InsertRoutePatternParams = {
  routeId: string;
  pattern: string;
  target: string;
  headers: string;
};

export type InsertRoutePatternResult = {
  changes: number;
  last_row_id: number;
};

export function insertRoutePatternStmt(
  db: D1Database,
  params: InsertRoutePatternParams,
): D1PreparedStatement {
  const sql = `
	INSERT INTO route_patterns (route_id, pattern, target, headers)
	VALUES (?, ?, ?, ?)
	
	`;
  return db.prepare(sql).bind(params.routeId, params.pattern, params.target, params.headers);
}

export async function insertRoutePattern(
  db: D1Database,
  params: InsertRoutePatternParams,
): Promise<InsertRoutePatternResult> {
  return insertRoutePatternStmt(db, params)
    .run()
    .then((res) => res.meta);
}

export type InsertRouteParams = {
  routeId: string;
  metadata: string;
};

export type InsertRouteResult = {
  changes: number;
  last_row_id: number;
};

export function insertRouteStmt(db: D1Database, params: InsertRouteParams): D1PreparedStatement {
  const sql = `
	INSERT INTO routes (id, metadata)
	VALUES (?, ?)
	
	`;
  return db.prepare(sql).bind(params.routeId, params.metadata);
}

export async function insertRoute(
  db: D1Database,
  params: InsertRouteParams,
): Promise<InsertRouteResult> {
  return insertRouteStmt(db, params)
    .run()
    .then((res) => res.meta);
}

export type SelectPatternConflictsExcludingRouteParams = {
  patterns: string[];
  excludeRouteId: string;
};

export type SelectPatternConflictsExcludingRouteResult = {
  routeId: string;
  pattern: string;
};

export function selectPatternConflictsExcludingRouteStmt(
  db: D1Database,
  params: SelectPatternConflictsExcludingRouteParams,
): D1PreparedStatement {
  const sql = `
	SELECT route_id AS routeId, pattern
	FROM route_patterns
	WHERE pattern IN (${params.patterns.map(() => "?")})
	  AND route_id != ?
	ORDER BY route_id ASC, pattern ASC
	
	`;
  return db.prepare(sql).bind(...params.patterns, params.excludeRouteId);
}

export async function selectPatternConflictsExcludingRoute(
  db: D1Database,
  params: SelectPatternConflictsExcludingRouteParams,
): Promise<SelectPatternConflictsExcludingRouteResult[]> {
  return selectPatternConflictsExcludingRouteStmt(db, params)
    .raw({ columnNames: false })
    .then((rows) => rows.map((row) => mapArrayToSelectPatternConflictsExcludingRouteResult(row)));
}

function mapArrayToSelectPatternConflictsExcludingRouteResult(data: any) {
  const result: SelectPatternConflictsExcludingRouteResult = {
    routeId: data[0],
    pattern: data[1],
  };
  return result;
}

export type SelectPatternConflictsParams = {
  patterns: string[];
};

export type SelectPatternConflictsResult = {
  routeId: string;
  pattern: string;
};

export function selectPatternConflictsStmt(
  db: D1Database,
  params: SelectPatternConflictsParams,
): D1PreparedStatement {
  const sql = `
	SELECT route_id AS routeId, pattern
	FROM route_patterns
	WHERE pattern IN (${params.patterns.map(() => "?")})
	ORDER BY route_id ASC, pattern ASC
	
	`;
  return db.prepare(sql).bind(...params.patterns);
}

export async function selectPatternConflicts(
  db: D1Database,
  params: SelectPatternConflictsParams,
): Promise<SelectPatternConflictsResult[]> {
  return selectPatternConflictsStmt(db, params)
    .raw({ columnNames: false })
    .then((rows) => rows.map((row) => mapArrayToSelectPatternConflictsResult(row)));
}

function mapArrayToSelectPatternConflictsResult(data: any) {
  const result: SelectPatternConflictsResult = {
    routeId: data[0],
    pattern: data[1],
  };
  return result;
}

export type SelectResolvedRouteByHostParams = {
  host: string;
};

export type SelectResolvedRouteByHostResult = {
  routeId: string;
  pattern: string;
  target: string;
  headers: string;
  metadata: string;
};

export function selectResolvedRouteByHostStmt(
  db: D1Database,
  params: SelectResolvedRouteByHostParams,
): D1PreparedStatement {
  const sql = `
	SELECT
	  rp.route_id AS routeId,
	  rp.pattern AS pattern,
	  rp.target AS target,
	  rp.headers AS headers,
	  r.metadata AS metadata
	FROM route_patterns rp
	INNER JOIN routes r ON r.id = rp.route_id
	WHERE ? GLOB rp.pattern
	ORDER BY
	  CASE WHEN rp.pattern NOT LIKE '%*%' THEN 1 ELSE 0 END DESC,
	  length(rp.pattern) DESC,
	  rp.id ASC
	LIMIT 1
	
	`;
  return db.prepare(sql).bind(params.host);
}

export async function selectResolvedRouteByHost(
  db: D1Database,
  params: SelectResolvedRouteByHostParams,
): Promise<SelectResolvedRouteByHostResult | null> {
  return selectResolvedRouteByHostStmt(db, params)
    .raw({ columnNames: false })
    .then((rows) => (rows.length > 0 ? mapArrayToSelectResolvedRouteByHostResult(rows[0]) : null));
}

function mapArrayToSelectResolvedRouteByHostResult(data: any) {
  const result: SelectResolvedRouteByHostResult = {
    routeId: data[0],
    pattern: data[1],
    target: data[2],
    headers: data[3],
    metadata: data[4],
  };
  return result;
}

export type SelectRouteByIdParams = {
  routeId: string;
};

export type SelectRouteByIdResult = {
  id: string;
  metadata: string;
  created_at: string;
  updated_at: string;
};

export function selectRouteByIdStmt(
  db: D1Database,
  params: SelectRouteByIdParams,
): D1PreparedStatement {
  const sql = `
	SELECT id, metadata, created_at, updated_at
	FROM routes
	WHERE id = ?
	
	`;
  return db.prepare(sql).bind(params.routeId);
}

export async function selectRouteById(
  db: D1Database,
  params: SelectRouteByIdParams,
): Promise<SelectRouteByIdResult | null> {
  return selectRouteByIdStmt(db, params)
    .raw({ columnNames: false })
    .then((rows) => (rows.length > 0 ? mapArrayToSelectRouteByIdResult(rows[0]) : null));
}

function mapArrayToSelectRouteByIdResult(data: any) {
  const result: SelectRouteByIdResult = {
    id: data[0],
    metadata: data[1],
    created_at: data[2],
    updated_at: data[3],
  };
  return result;
}

export type SelectRoutePatternsByRouteIdParams = {
  routeId: string;
};

export type SelectRoutePatternsByRouteIdResult = {
  id: number;
  route_id: string;
  pattern: string;
  target: string;
  headers: string;
  created_at: string;
  updated_at: string;
};

export function selectRoutePatternsByRouteIdStmt(
  db: D1Database,
  params: SelectRoutePatternsByRouteIdParams,
): D1PreparedStatement {
  const sql = `
	SELECT id, route_id, pattern, target, headers, created_at, updated_at
	FROM route_patterns
	WHERE route_id = ?
	ORDER BY id ASC
	
	`;
  return db.prepare(sql).bind(params.routeId);
}

export async function selectRoutePatternsByRouteId(
  db: D1Database,
  params: SelectRoutePatternsByRouteIdParams,
): Promise<SelectRoutePatternsByRouteIdResult[]> {
  return selectRoutePatternsByRouteIdStmt(db, params)
    .raw({ columnNames: false })
    .then((rows) => rows.map((row) => mapArrayToSelectRoutePatternsByRouteIdResult(row)));
}

function mapArrayToSelectRoutePatternsByRouteIdResult(data: any) {
  const result: SelectRoutePatternsByRouteIdResult = {
    id: data[0],
    route_id: data[1],
    pattern: data[2],
    target: data[3],
    headers: data[4],
    created_at: data[5],
    updated_at: data[6],
  };
  return result;
}

export type SelectRoutePatternsResult = {
  id: number;
  route_id: string;
  pattern: string;
  target: string;
  headers: string;
  created_at: string;
  updated_at: string;
};

export function selectRoutePatternsStmt(db: D1Database): D1PreparedStatement {
  const sql = `
	SELECT id, route_id, pattern, target, headers, created_at, updated_at
	FROM route_patterns
	ORDER BY route_id ASC, id ASC
	
	`;
  return db.prepare(sql);
}

export async function selectRoutePatterns(db: D1Database): Promise<SelectRoutePatternsResult[]> {
  return selectRoutePatternsStmt(db)
    .raw({ columnNames: false })
    .then((rows) => rows.map((row) => mapArrayToSelectRoutePatternsResult(row)));
}

function mapArrayToSelectRoutePatternsResult(data: any) {
  const result: SelectRoutePatternsResult = {
    id: data[0],
    route_id: data[1],
    pattern: data[2],
    target: data[3],
    headers: data[4],
    created_at: data[5],
    updated_at: data[6],
  };
  return result;
}

export type SelectRoutesResult = {
  id: string;
  metadata: string;
  created_at: string;
  updated_at: string;
};

export function selectRoutesStmt(db: D1Database): D1PreparedStatement {
  const sql = `
	SELECT id, metadata, created_at, updated_at
	FROM routes
	ORDER BY created_at ASC, id ASC
	
	`;
  return db.prepare(sql);
}

export async function selectRoutes(db: D1Database): Promise<SelectRoutesResult[]> {
  return selectRoutesStmt(db)
    .raw({ columnNames: false })
    .then((rows) => rows.map((row) => mapArrayToSelectRoutesResult(row)));
}

function mapArrayToSelectRoutesResult(data: any) {
  const result: SelectRoutesResult = {
    id: data[0],
    metadata: data[1],
    created_at: data[2],
    updated_at: data[3],
  };
  return result;
}

export type UpdateRouteMetadataData = {
  metadata: string;
};

export type UpdateRouteMetadataParams = {
  routeId: string;
};

export type UpdateRouteMetadataResult = {
  changes: number;
};

export function updateRouteMetadataStmt(
  db: D1Database,
  data: UpdateRouteMetadataData,
  params: UpdateRouteMetadataParams,
): D1PreparedStatement {
  const sql = `
	UPDATE routes
	SET metadata = ?, updated_at = CURRENT_TIMESTAMP
	WHERE id = ?
	
	`;
  return db.prepare(sql).bind(data.metadata, params.routeId);
}

export async function updateRouteMetadata(
  db: D1Database,
  data: UpdateRouteMetadataData,
  params: UpdateRouteMetadataParams,
): Promise<UpdateRouteMetadataResult> {
  return updateRouteMetadataStmt(db, data, params)
    .run()
    .then((res) => res.meta);
}
