/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// TanStack Router generates the `as any` route-update assertions below because

// the route IDs are registered by the later FileRoutesByPath declaration; the

// generated declaration makes those otherwise-unrepresentable assertions safe.

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WIndexRouteImport } from './routes/w.index'
import { Route as WBoardIdRouteImport } from './routes/w.$boardId'

const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WIndexRoute = WIndexRouteImport.update({
  id: '/w/',
  path: '/w/',
  getParentRoute: () => rootRouteImport,
} as any)
const WBoardIdRoute = WBoardIdRouteImport.update({
  id: '/w/$boardId',
  path: '/w/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notes': typeof NotesRoute
  '/w/$boardId': typeof WBoardIdRoute
  '/w/': typeof WIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notes': typeof NotesRoute
  '/w/$boardId': typeof WBoardIdRoute
  '/w': typeof WIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notes': typeof NotesRoute
  '/w/$boardId': typeof WBoardIdRoute
  '/w/': typeof WIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/notes' | '/w/$boardId' | '/w/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/notes' | '/w/$boardId' | '/w'
  id: '__root__' | '/' | '/notes' | '/w/$boardId' | '/w/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotesRoute: typeof NotesRoute
  WBoardIdRoute: typeof WBoardIdRoute
  WIndexRoute: typeof WIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/': {
      id: '/w/'
      path: '/w'
      fullPath: '/w/'
      preLoaderRoute: typeof WIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$boardId': {
      id: '/w/$boardId'
      path: '/w/$boardId'
      fullPath: '/w/$boardId'
      preLoaderRoute: typeof WBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotesRoute: NotesRoute,
  WBoardIdRoute: WBoardIdRoute,
  WIndexRoute: WIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
