// GENERATED by scripts/generate-itx-api.ts — do not edit.
// Regenerate with: pnpm generate:itx-api
//
// The source of truth is src/rpc-targets.ts (docstrings + signatures) and the
// zod schemas its signatures use. This file is the projection: one standalone,
// import-free module describing everything reachable from the /api entrypoint.

/**
 * The public ITX capability surface.
 *
 * `/api` — os' one API — gives callers one unauthenticated object.
 * Authentication returns a root catalog, and every object reachable from that
 * catalog is a Cap'n Web / Workers RPC capability. Projects and agents expose
 * stable built-ins (`streams`, `repos`, `workers`, etc.) plus dynamic dotted
 * capabilities mounted on capability hosts (`itx.capabilityHost`,
 * `itx.capabilityHosts.get(path)`). Streams are the durable coordination layer
 * underneath those surfaces: processors, project bootstrap, repo bootstrap,
 * and agent loops all communicate by appending and reducing events.
 *
 * The four nouns. Keeping them distinct is what makes this system legible:
 *
 * - a SESSION is what `os.authenticate()` returns. It is a catalog that *vends*
 *   itxs; it is not itself an itx.
 * - a PROJECT is the tenant / isolation boundary — a `prj_…` id, its Durable
 *   Objects, its streams. You never hold a "project object"; you hold an itx
 *   scoped into a project.
 * - an ITX is a capability context scoped into one project at one path. It is
 *   the `itx` in every `async (itx) => { … }` script and what `env.ITX.get()`
 *   returns; `session.projects.get(id)` gives you the itx at the project root,
 *   and an itx at "/agents/…" is what "an agent context" means.
 * - a CAPABILITY HOST is the durable dynamic-capability table (and script
 *   journal) at one scope path. Each itx fronts exactly one host
 *   (`itx.capabilityHost`; `itx.provideCapability`/`revokeCapability` are
 *   shortcuts onto it); `itx.capabilityHosts.get(path)` addresses any other
 *   scope's host, including the project root at `"/"`.
 */

/**
 * Entry point exposed before any principal or project authority is known.
 *
 * `/api` hands every caller one of these; the only thing it can do is
 * `authenticate(...)`, which on success returns a {@link Session}. This is the
 * canonical Cap'n Web pattern: authority cannot be forged, only handed back by a
 * method that already checked you.
 */
export interface UnauthenticatedOs {
  __describe(): Promise<Description>;
  /** Exchange credentials for a {@link Session}; rejects when they prove nothing. */
  authenticate(input: ItxAuthCredentials): Promise<Session>;
}

/**
 * What you authenticate into: a catalog that vends itxs.
 *
 * A session is NOT an itx — it is the directory you use to reach one.
 * `projects` is principal-scoped. `streams` and `repos` here are the
 * deployment-wide surfaces backed by `projectId: null`, so only admin/internal
 * auth can reach them.
 */
export interface Session {
  /** Includes `principal` — who this session is. */
  __describe(): Promise<Description & { principal: string }>;
  /** Deployment-wide streams (admin only; projectId: null). */
  streams: StreamCollection;
  /** Deployment-wide repos (admin only; projectId: null). */
  repos: RepoCollection;
  /** Project catalog: list(), get(projectId), create({ slug }) — each vends an itx. */
  projects: ProjectCollection;
}

/** Stream catalog for either a project or the deployment-wide global scope. */
export interface StreamCollection {
  __describe(): Promise<Description>;
  /** The durable event stream at a path. */
  get(path: string): Stream;
}

/** Repo catalog for either a project or the deployment-wide global scope. */
export interface RepoCollection {
  __describe(): Promise<Description>;
  /** Create the repo at a path; resolves once `repo/created` lands. */
  create(input: { path: string }): Promise<Repo>;
  /** The repo at a path. */
  get(path: string): Repo;
}

/** Catalog of projects reachable from a {@link Session}. */
export interface ProjectCollection {
  __describe(): Promise<Description>;
  /** The itx at the project root for a `prj_…` id. */
  get(projectId: string): Promise<Itx>;
  /**
   * Register and bootstrap a project. By default this resolves once the
   * bootstrap saga has committed `project/created` — convenient for scripts
   * and tests that use the project immediately. Pass
   * `waitUntilCreated: false` to resolve as soon as the project EXISTS
   * (identity registered, directory primed, bootstrap events appended): the
   * saga then runs behind the returned handle, and its progress is ordinary
   * live processor state (`itx.processor.onStateChange` — `state.created`
   * flips when bootstrap lands). The dashboard uses the fast path to redirect
   * into the project instantly and play creation progress from pushes.
   */
  create(args: {
    organizationSlug?: string;
    projectId?: string;
    slug: string;
    waitUntilCreated?: boolean;
  }): Promise<Itx>;
  /**
   * The session's projects, enriched: identity (id/slug/org) from the auth
   * claims or the project directory, deployment status from a concurrent
   * engine probe (`state.created` on each project's processor snapshot). A
   * probe failure degrades THAT entry to "unknown" — the list always renders.
   * Scope is explicit: "mine" (default for user principals) is the caller's
   * own claims even when admin credentials ride the same socket;
   * "deployment" (every directory-known project) requires an admin principal
   * and is the default for non-user admin principals, which have no claims.
   */
  list(input?: { scope?: "mine" | "deployment" }): Promise<ProjectListEntry[]>;
}

/**
 * Durable event stream capability.
 *
 * Streams are the public coordination primitive, not an internal queue hidden
 * behind domain methods. Domain helpers can construct common event shapes, but
 * callers and processors still work with explicit events.
 */
export interface Stream {
  __describe(): Promise<Description>;
  /** Commit events; resolves with the same events carrying offsets and timestamps. */
  append(...events: StreamEventInput[]): Promise<StreamEvent[]>;
  /** The stream at a sub-path, resolved relative to this stream's path. */
  at(path: string): Stream;
  /** One event by offset or idempotencyKey; undefined when it does not exist. */
  getEvent(
    args: { offset: number; idempotencyKey?: never } | { idempotencyKey: string; offset?: never },
  ): Promise<StreamEvent | undefined>;
  /** Read a range of committed events. */
  getEvents(args?: {
    afterOffset?: number;
    beforeOffset?: number | null;
    limit?: number;
  }): Promise<StreamEvent[]>;
  /**
   * Block until an event lands that is after `afterOffset`, matches
   * `eventTypes`, and passes `predicate`; rejects after `timeoutMs`.
   */
  waitForEvent(args: {
    afterOffset?: number;
    eventTypes?: readonly string[];
    predicate?: (event: StreamEvent) => boolean | Promise<boolean>;
    timeoutMs: number;
  }): Promise<StreamEvent>;
  /** The reduced-state snapshot (plus runtime debug info) of one configured processor. */
  getProcessorRuntimeState(args: {
    subscriptionKey: string;
  }): Promise<ProcessorRuntimeState | null>;
  /** Live debug view of the stream Durable Object: core processor state and open connections. */
  runtimeState(): Promise<{
    coreProcessorState: unknown;
    runtime: {
      connections: Record<string, unknown>;
    };
  }>;
  /**
   * Live event delivery: `processEventBatch` is called for every committed
   * batch (optionally replayed from `replayAfterOffset`); returns an
   * unsubscribe handle. Set `configured: true` only from trusted-internal
   * auth — it opens the durable configured subscription registered under
   * `subscriptionKey` (the wake-handshake response) instead of an ephemeral one.
   */
  subscribe(args: {
    subscriptionKey?: string;
    configured?: boolean;
    processEventBatch: ProcessEventBatch;
    replayAfterOffset?: number;
    eventTypes?: readonly string[];
    events?: boolean;
    subscriber?: unknown;
  }): Promise<StreamSubscriptionHandle>;
}

/** Git-backed repo capability used by project workers and dynamic worker refs. */
export interface Repo {
  __describe(): Promise<Description>;
  /** Create the repo if it does not exist yet; resolves once `repo/created` lands. */
  create(): Promise<Repo>;
  /** Repo identity string (debug). */
  whoami(): Promise<string>;
  /** Commit a batch of file changes; use `edit` for a targeted single-string replacement. */
  commitFiles(input: CommitRepoFilesInput): Promise<CommitRepoFilesResult>;
  /**
   * Safely replace text in one committed file and commit the result. The
   * `oldString` must match exactly once unless `replaceAll` is true.
   */
  edit(input: EditRepoFileInput): Promise<EditRepoFileResult>;
  /** All committed file paths at HEAD. */
  listFiles(): Promise<{ commitOid: string; paths: string[] }>;
  /** Committed file contents at HEAD; null when the path does not exist. */
  readFile(input: { path: string }): Promise<{
    commitOid: string;
    content: string;
    path: string;
  } | null>;
  /** The repo stream processor (snapshot/state). */
  processor: StreamProcessorRpc<RepoProcessorState>;
}

/**
 * The server-side **itx** — the object an `async (itx) => { … }` script holds and
 * what `env.ITX.get()` returns. One class serves the project root and every nested
 * (agent) scope; the injected `capabilityHost` selects which scope's dynamic
 * capability table backs it.
 *
 * DESIGN NOTE — this RpcTarget sits *in front of* the capability-host Durable
 * Object. Its built-in members (`streams`, `agents`, `repo`, …) are resolved here
 * in the isolate; only unknown roots fall through `withInvokeCapabilityFallback`
 * to the capability host's dynamic table (which itself chains up to enclosing
 * scopes). So the common `itx.streams.get(...)` path never makes a round trip
 * just to check whether `streams` was shadowed. The deliberate cost: a dynamic
 * capability can never shadow a built-in name — the built-in always wins
 * (`rejectBuiltinCollision` enforces this at provide time). If we end up needing
 * shadowable built-ins a lot, we'd move resolution behind the DO and pay the
 * round trip; today we don't.
 */
export interface Itx {
  /** The project this itx is scoped into. */
  projectId: string;
  /**
   * Identity + full capability inventory: `projectId`/`name`, every reachable
   * capability (built-ins + dynamic mounts), the children map, and the full
   * public type surface in `types`.
   */
  __describe(): Promise<ProjectDescription>;
  /** Formatted dashboard/debug info for this itx scope, suitable for Slack messages. */
  debug(): Promise<string>;
  /** The project stream processor (snapshot/state; `state.created` flips when bootstrap lands). */
  processor: StreamProcessorRpc<ProjectProcessorState>;
  /** Workers AI: run(model, body), models(). */
  ai: Ai;
  /** THIS agent's control surface — present only on an agent-scoped itx (path under `/agents/`). */
  agent?: Agent;
  /** THIS agent's web-chat door — present only on an agent-scoped itx. */
  chat?: AgentChat;
  /**
   * This scope's own capability host: the durable capability table behind
   * this itx (`provideCapability`, `revokeCapability`, `runScript`,
   * `__describe`). Dynamic dotted calls (`itx.foo.bar(...)`) fall back to it.
   */
  capabilityHost: CapabilityHost;
  /**
   * Capability hosts of OTHER scopes, by path. `capabilityHosts.get("/")` is
   * the project root — providing there makes a capability visible to every
   * scope in the project (child scopes inherit ancestors' mounts).
   */
  capabilityHosts: CapabilityHostCollection;
  /** Shortcut for `capabilityHost.provideCapability` (mounts on THIS scope). */
  provideCapability(input: ProvideCapabilityInput): Promise<CapabilityProvision>;
  /** Shortcut for `capabilityHost.revokeCapability`. */
  revokeCapability(input: RevokeCapabilityInput): Promise<void>;
  /** Project stream catalog: get(path), list(). */
  streams: ProjectStreamCollection;
  /** Agent catalog: get(path), list(). */
  agents: AgentCollection;
  /** Project-attributed outbound fetch (+ intercept). */
  egress: ProjectEgress;
  /** Read-only catalogue of known-good itx script snippets (`list()`, `get({ id })`). */
  examples: ItxExampleCatalog;
  /** Slack/Google connections + the connection-scoped API proxies (`integrations.gmail`, `integrations.slack`). */
  integrations: ProjectIntegrations;
  /** Ad-hoc MCP clients: connect(url); `itx.mcp.exa` is the built-in Exa web search. */
  mcp: McpClientCollection;
  /** Ad-hoc OpenAPI clients: connect(spec). */
  openapi: OpenApiCollection;
  /** Repo catalog by path. */
  repos: ProjectRepoCollection;
  /** Path-addressed sandboxes (`itx.sandboxes.get("/sandboxes/cloudflare/whatever")`). */
  sandboxes: SandboxCollection;
  /** Secret catalog by path. */
  secrets: SecretCollection;
  /** The project repo at /repos/project. */
  repo: Repo;
  /** Dynamic worker refs: get(ref). */
  workers: DynamicWorkerCollection;
  /** The default repo-backed project worker — a convenience alias; the general API is `workers.get(ref)`. */
  worker: DynamicWorkerCapability<ProjectWorker>;
}

/**
 * RPC ownership handle for a live stream connection.
 *
 * This follows Cap'n Web/Workers RPC lifecycle conventions: returned class
 * instances are object capabilities, and `using`/`[Symbol.dispose]` releases
 * the caller's ownership of the live resource.
 *
 * Docs:
 * - https://github.com/cloudflare/capnweb#memory-management
 * - https://developers.cloudflare.com/workers/runtime-apis/rpc/lifecycle/
 *
 * `unsubscribe()` remains the explicit, awaitable domain operation. Disposal is
 * the scoped cleanup path and calls the same captured close function. Capturing
 * the close function matters: a later subscription can reuse the same key, and
 * an old handle must not look up by key and close the replacement.
 */
export interface StreamSubscriptionHandle {
  /** Stable identity of this subscription connection. */
  subscriptionKey: string;
  /** The stream's max offset at subscribe time (replay starts behind it). */
  streamMaxOffset: number;
  /**
   * Liveness probe (see `StreamSubscriptionHandle.ping` in types.ts). Captures
   * the connection's own open flag, not a lookup by key, so a replacement
   * subscription under the same key reports `false` here.
   */
  ping(): boolean;
  /** Close this connection; safe to call more than once. */
  unsubscribe(): void;
  [Symbol.dispose](): void;
}

export interface StreamProcessorRpc<State = unknown> {
  getRuntimeState(): Promise<ProcessorRuntimeState<State>>;
  /**
   * Server-push of the processor's reduced state. The callback receives the
   * durable checkpoint `{ offset, state }` — offset-carrying so clients can
   * commit pushes and `snapshot()` reads monotonically against each other —
   * once immediately on subscribe (current state IS the first paint) and then
   * after every checkpointed batch that changed state.
   */
  onStateChange(
    cb: (snapshot: ProcessorSnapshot<State>) => unknown,
  ): Promise<ProcessorStateSubscriptionHandle>;
  snapshot(): Promise<ProcessorSnapshot<State>>;
  waitUntilEvent(input: { offset: number; timeoutMs?: number }): Promise<void>;
}

/** Workers AI binding exposed through ITX as a project/agent capability. */
export interface Ai {
  __describe(): Promise<Description>;
  /** List the Workers AI model catalog. */
  models(): Promise<unknown>;
  /** Run one model invocation (`run("@cf/meta/llama-3.1-8b-instruct", { prompt })`). */
  run(model: string, body: unknown): Promise<unknown>;
}

/** Agent capability surface for message loops and agent-local dynamic tools. */
export interface Agent {
  /** The agent scope's own capability host (provide/revoke/runScript/__describe). */
  capabilityHost: CapabilityHost;
  /** Shortcut for `capabilityHost.provideCapability` (mounts on THIS agent's scope). */
  provideCapability(input: ProvideCapabilityInput): Promise<CapabilityProvision>;
  /** Shortcut for `capabilityHost.revokeCapability`. */
  revokeCapability(input: RevokeCapabilityInput): Promise<void>;
  /** The agent stream processor (snapshot/state). */
  processor: StreamProcessorRpc<AgentProcessorState>;
  /** The agent's own event stream. */
  stream: Stream;
  /** The agent's web-chat door (what the user sees). */
  chat: AgentChat;
  /** Append a user message to the agent stream (triggers the agent's loop). */
  sendMessage(message: string): Promise<StreamEvent>;
  /**
   * Send-and-wait convenience: appends a user message and resolves with the
   * agent's next chat reply on this stream. Replies are matched by order, not
   * correlated per request — concurrent asks on one agent stream interleave
   * exactly like two people typing into the same chat.
   */
  ask(input: {
    message: string;
    /** Where the message came from. Defaults to "web". */
    origin?: "web" | "mcp";
    /** How long to wait for the reply. Defaults to 45s. */
    timeoutMs?: number;
  }): Promise<StreamEvent>;
  /** Includes `whoami` (`"agent <projectId>:<agentPath>"`), `projectId`, `agentPath`. */
  __describe(): Promise<Description & { agentPath: string; projectId: string; whoami: string }>;
}

/** Agent-local web chat response tool exposed inside agent script execution. */
export interface AgentChat {
  __describe(): Promise<Description>;
  /** The agent's own event stream (the chat rides on it). */
  stream: Stream;
  /** Say something to the user: appends the agent's reply to its stream. */
  sendMessage(input: { message: string }): Promise<StreamEvent>;
}

/**
 * The host surface for ONE capability scope: mount, revoke, invoke, describe,
 * and run scripts against the durable capability table at `path` (backed by
 * the CapabilityHostDurableObject with that name). Mounting is always local to
 * this scope; reads chain up through enclosing scopes inside the Durable
 * Object. `itx.capabilityHost` is the current scope's host;
 * `itx.capabilityHosts.get("/")` addresses the project root from anywhere —
 * that is how an agent provides a capability to the whole project.
 */
export interface CapabilityHost {
  /** The scope path this host fronts: `"/"` is the project root, `/agents/bla` an agent. */
  path: string;
  /** Mount a capability on THIS scope; returns an ownership handle that can revoke exactly this mount. */
  provideCapability(input: ProvideCapabilityInput): Promise<CapabilityProvision>;
  /** Remove the current mount at a path, or one exact mount by its offset. */
  revokeCapability(input: RevokeCapabilityInput): Promise<void>;
  /** Explicit dynamic dispatch; the dotted-path fallback (`itx.foo.bar(...)`) compiles to exactly this call. */
  invokeCapability(call: { args?: unknown[]; path: string[] }): Promise<unknown>;
  /** Includes `capabilities`: everything reachable at this scope — own mounts plus inherited ones, tagged with their declaring scope. */
  __describe(): Promise<Description & { capabilities: CapabilityDescription[]; path: string }>;
  /** Run an `async (itx) => { … }` script in this scope; the execution is journaled on the scope stream. */
  runScript(code: string): Promise<{
    completedEvent: StreamEvent;
    executionId: string;
    result: unknown;
  }>;
}

/** Catalog of capability scopes within one project (`itx.capabilityHosts`). */
export interface CapabilityHostCollection {
  __describe(): Promise<Description>;
  /** The capability host at a scope path (`"/"` is the project root). */
  get(path: string): CapabilityHost;
}

/**
 * Ownership handle for one `provideCapability()` call.
 *
 * Cap'n Web and Workers RPC model returned class instances as object
 * capabilities: callers hold a stub and dispose that stub when they are done.
 * See:
 * - https://github.com/cloudflare/capnweb#memory-management
 * - https://developers.cloudflare.com/workers/runtime-apis/rpc/lifecycle/
 *
 * We still keep the explicit `revoke()` method because it is a domain operation
 * callers can await and assert on. `[Symbol.dispose]` is the lifecycle fallback
 * for scopes (`using provision = ...`) and abandoned stubs. The handle is keyed
 * by the stream offset that mounted the capability, so disposing an older
 * provision after a replacement cannot revoke the newer mount at the same path.
 */
export interface CapabilityProvision {
  __describe(): Promise<Description>;
  /** The capability path this mount claimed. */
  path: string[];
  /** The stream offset of the `capability-provided` event this handle owns. */
  providedAtOffset: number;
  /** Remove exactly this mount (never a newer mount at the same path). */
  revoke(): Promise<void>;
  [Symbol.dispose](): void;
}

/** Project-scoped stream catalog with reduced-state listing. */
export interface ProjectStreamCollection extends StreamCollection {
  /** Known streams, read from the project processor's reduced state. */
  list(): Promise<StreamListItem[]>;
}

/** Agent catalog within one project. */
export interface AgentCollection {
  __describe(): Promise<Description>;
  /** The agent control surface at a path (`"/agents/<name>"`). */
  get(path: string): Agent;
  /** Known agents, read from the project processor's reduced state. */
  list(): Promise<StreamListItem[]>;
}

/**
 * Public project egress facet.
 *
 * The Project Durable Object is the single egress decision point: it owns the
 * live runtime interceptor slot and, when there is no interceptor, performs the
 * terminal secret-substitution fetch path.
 */
export interface ProjectEgress {
  __describe(): Promise<Description>;
  /** Outbound fetch with the project's identity and secret substitution. */
  fetch(request: Request): Promise<Response>;
  /** Install a live egress interceptor (last writer wins); returns a release handle. */
  intercept(handler: ProjectEgressInterceptor): Promise<ProjectEgressIntercept>;
}

/**
 * Read-only catalogue of known-good itx script snippets — the project-context
 * entries of the REPL "Examples" panel. `list()` returns every entry without
 * its code; `get({ id })` returns one entry with the full script body. Agents
 * copy working patterns from here instead of guessing at the surface.
 * Session-level examples (whoami, projects.list) are excluded: they run
 * against the OS Session `authenticate()` returns, which an itx holder does
 * not have.
 */
export interface ItxExampleCatalog {
  __describe(): Promise<Description>;
  /** Every example summary, without code bodies (cheap to skim). */
  list(): Promise<ItxExampleSummary[]>;
  /** One example with its full script body. */
  get(input: { id: string }): Promise<ItxExampleWithCode>;
}

/**
 * The `itx.integrations` built-in: connection status, OAuth start/complete,
 * and disconnect for slack/google, PLUS the connection-scoped API proxies
 * (`integrations.gmail`, `integrations.slack`) — they live here because they
 * only work through the project's connected accounts. The complete* methods
 * are called by the app worker's OAuth callback routes
 * (/api/integrations/<provider>/callback); their authority is the HMAC-signed
 * OAuth state minted by startOAuthFlow, verified itx-side.
 */
export interface ProjectIntegrations {
  __describe(): Promise<Description>;
  /** Gmail REST proxy for the project's connected Google account. */
  gmail: GmailCapability;
  /** Slack Web API proxy for the connected workspace (`integrations.slack.chat.postMessage(...)`). */
  slack: SlackCapability;
  /** Connection status for a provider. */
  getConnection(input: { provider: IntegrationProvider }): Promise<IntegrationConnectionStatus>;
  /** Begin the OAuth connect flow; returns the authorization URL to send the user to. */
  startOAuthFlow(input: {
    callbackUrl?: string;
    provider: IntegrationProvider;
    /** The user to bind the OAuth state to. Browser-supplied, not authority;
     * the callback's check against the signed state is the backstop. */
    userId: string;
  }): Promise<{ authorizationUrl: string }>;
  /** OAuth callback leg for Slack; authority is the HMAC-signed state from startOAuthFlow. */
  completeSlackConnect(input: {
    code: string;
    state: string;
    userId: string | null;
  }): Promise<CompleteConnectResult>;
  /** OAuth callback leg for Google; authority is the HMAC-signed state from startOAuthFlow. */
  completeGoogleConnect(input: {
    code: string;
    state: string;
    userId: string | null;
  }): Promise<CompleteConnectResult>;
  /** Disconnect a provider and forget its tokens. */
  disconnect(input: { provider: IntegrationProvider }): Promise<{ success: true }>;
}

export interface McpClientCollection {
  __describe(): Promise<Description>;
  /** Connect to an MCP server by URL; dotted calls on the client are tool invocations. */
  connect(input: McpClientConnectInput): Promise<McpClientRpc>;
  /**
   * The public Exa MCP server (https://mcp.exa.ai/mcp), pre-connected for every
   * project: web search and page reading as flat tool calls.
   * `itx.mcp.exa.web_search_exa({ query, numResults })` searches the web;
   * `itx.mcp.exa.web_fetch_exa({ urls, maxCharacters })` reads pages as markdown.
   */
  exa: McpClientRpc;
}

export interface OpenApiCollection {
  __describe(): Promise<Description>;
  /** Fetch and parse a spec; dotted calls on the returned client are operationIds. */
  connect(input: OpenApiConnectInput): Promise<OpenApiRpc>;
}

/** Project-scoped repo catalog with reduced-state listing. */
export interface ProjectRepoCollection extends RepoCollection {
  /** Known repos, read from the project processor's reduced state. */
  list(): Promise<StreamListItem[]>;
}

/**
 * The `itx.sandboxes` built-in. `get(path)` returns the sandbox Durable
 * Object's own RPC stub — deliberately NO RpcTarget wrapper, so the caller
 * sees exactly what the `@cloudflare/sandbox` SDK exposes and new SDK methods
 * need no forwarding code here. Confinement is by name: the stub is minted
 * from this project's id plus the validated `/sandboxes/cloudflare/...`
 * path, after the same project-access assert every collection performs.
 */
export interface SandboxCollection {
  __describe(): Promise<Description>;
  /** The sandbox at a path. Cheap — the container boots on the first command, not here. */
  get(path: string): Promise<CloudflareSandbox>;
}

/** Secret catalog within one project. */
export interface SecretCollection {
  __describe(): Promise<Description>;
  /** The secret at a path. */
  get(path: string): Secret;
  /** Known secrets, read from the project processor's reduced state. */
  list(): Promise<StreamListItem[]>;
}

/**
 * Public project-facing worker collection.
 *
 * `get(ref)` mirrors the desired capability-tree shape:
 * `itx.projects.get("prj").workers.get(ref).someRpcMethod()`.
 */
export interface DynamicWorkerCollection {
  __describe(): Promise<Description>;
  /** The live dispatch target for a declarative worker ref (validated by schema). */
  get<T extends object = Record<string, unknown>>(
    ref: DynamicWorkerRef,
  ): DynamicWorkerCapability<T>;
}

/**
 * Default seeded project worker contract.
 *
 * This documents the reference repo's `worker.js` only. Arbitrary dynamic
 * workers should be typed by callers through `workers.get<T>(ref)`.
 */
export interface ProjectWorker {
  fetch(req: Request): Promise<Response>;
  processEvent(input: { event: StreamEvent }): Promise<void>;
  testFetch(input: { headerValue: string; url: string }): Promise<unknown>;
}

/**
 * RPC ownership handle for one `onStateChange` subscription — the processor
 * counterpart of {@link StreamSubscriptionHandle}. `unsubscribe()` is the
 * explicit domain operation, disposal is the scoped cleanup path, and `ping()`
 * reports whether the subscription is still registered on the live processor
 * (a dead Durable Object incarnation makes the call itself reject — both
 * signals tell the client to re-subscribe).
 */
export interface ProcessorStateSubscriptionHandle {
  ping(): boolean;
  unsubscribe(): void;
  [Symbol.dispose](): void;
}

/**
 * Disposable ownership handle returned by `project.egress.intercept(...)`.
 *
 * The Project Durable Object owns the retained live callback. This handle only
 * releases that exact retained callback if it is still the current interceptor.
 */
export interface ProjectEgressIntercept {
  /** Release this interceptor if it is still the current one. */
  release(): Promise<void>;
  [Symbol.dispose](): void;
}

/** The `itx.integrations.gmail` built-in: Gmail REST proxy for the project's Google account. */
export interface GmailCapability {
  __describe(): Promise<Description>;
  /** One Gmail REST call, authorized by the project's stored Google tokens. */
  request(request: GmailRequestInput): Promise<{
    data: unknown;
    headers: Record<string, string>;
    status: number;
    statusText: string;
  }>;
}

/**
 * The `itx.integrations.slack` built-in: a Slack Web API proxy for the project's connected
 * workspace. Dotted Web API method paths (`itx.integrations.slack.chat.postMessage({...})`)
 * resolve through the dynamic path-call fallback onto `invokeCapability`;
 * authorization uses the project's stored bot token through the secret
 * substitution egress pipeline (domains/integrations/slack-api.ts).
 */
export interface SlackCapability {
  __describe(): Promise<Description>;
  /** itx path-call surface: itx.integrations.slack.<Slack Web API method path>(body). */
  invokeCapability(call: { args?: unknown[]; path: string[] }): Promise<unknown>;
  /** One Slack Web API call, authorized by the project's stored bot token. */
  request(input: {
    body?: Record<string, unknown>;
    method: string;
  }): Promise<Record<string, unknown>>;
}

/** Path-addressed secret capability. Secret material has no public read API. */
export interface Secret {
  __describe(): Promise<Description>;
  /** Metadata (exists, egress allowlist, audit trail) — never the value. */
  describe(): Promise<SecretDescription>;
  /** Egress fetch with this secret's placeholders substituted server-side. */
  fetch(request: Request): Promise<Response>;
  /** Set the secret material and/or its egress allowlist. */
  update(input: SecretUpdateInput): Promise<StreamEvent>;
  /** The secret stream processor; its public state IS the SecretDescription. */
  processor: StreamProcessorRpc<SecretDescription>;
}

// ─── Data shapes ─────────────────────────────────────────────────────────────

/**
 * Self-description of one node in the capability tree — what `__describe()`
 * returns, on EVERY node, by convention.
 *
 * This is the discovery groundwork: `instructions` and `types` are always
 * present and describe THIS node; `children` is the high-level map (one-line
 * blip per child member) so a caller can see what exists without walking;
 * `parent` says where the node sits. Deep discovery is a walk: call
 * `__describe()` on the children you care about. Nodes add structured extras
 * (a project adds `projectId`, an agent adds `whoami`, a capability host adds
 * `capabilities`), so `__describe` is also the identity query — there is no
 * separate `describe()`/`whoami()`.
 *
 * Today each node hand-writes its description (the `describeNode` helper only
 * enforces the shape); the plan is to grow this into a transitive mechanism
 * where a parent composes its children's descriptions.
 */
export type Description = {
  /** Prose: what this node is and how to use it. */
  instructions: string;
  /** TypeScript source for this node's surface ("" when not yet written). */
  types: string;
  /** Discovery map: one-line blip per child member. */
  children: Record<string, string>;
  /** Where this node sits / how you reached it. */
  parent?: string;
};

/**
 * Credentials accepted by `UnauthenticatedOs.authenticate`.
 *
 * - `from-server-cookie` — the browser lane: the deployment's admin cookie or
 *   the signed-in user's session cookie riding the WebSocket handshake.
 * - `bearer` — an auth access token presented as RPC data.
 * - `admin-secret` — the deployment admin API secret (CLI / tooling / e2e).
 * - `impersonate` — admin-secret-gated fake principal, for test suites that
 *   exercise per-project confinement without minting real users.
 */
export type ItxAuthCredentials =
  | { type: "from-server-cookie" }
  | { type: "bearer"; token: string }
  | { type: "admin-secret"; secret: string }
  | { type: "impersonate"; secret: string; token: ItxAuthToken };

/** Principal shape for `impersonate` credentials. */
export type ItxAuthToken =
  | { type: "admin"; principal?: string }
  | { type: "user"; principal: string; projectScopes: string[] };

/** One entry of {@link ProjectCollection.list}. */
export type ProjectListEntry = {
  id: string;
  slug: string;
  organizationId: string | null;
  organizationName: string | null;
  deploymentStatus: ProjectDeploymentStatus;
};

export type StreamEventInput = {
  type: string;
  payload?: Record<string, unknown> | undefined;
  metadata?: Record<string, unknown> | undefined;
  source?:
    | {
        processor?: { slug: string; version: string } | undefined;
        crossPost?:
          | {
              ruleId: string;
              from: {
                createdAt: string;
                offset: number;
                path: string;
                projectId: string | null;
                type: string;
              };
            }
          | undefined;
      }
    | undefined;
  idempotencyKey?: string | undefined;
};

export type StreamEvent = {
  type: string;
  offset: number;
  createdAt: string;
  payload?: Record<string, unknown> | undefined;
  metadata?: Record<string, unknown> | undefined;
  source?:
    | {
        processor?: { slug: string; version: string } | undefined;
        crossPost?:
          | {
              ruleId: string;
              from: {
                createdAt: string;
                offset: number;
                path: string;
                projectId: string | null;
                type: string;
              };
            }
          | undefined;
      }
    | undefined;
  idempotencyKey?: string | undefined;
};

/** Serializable snapshot plus optional live runtime debug state for a processor. */
export type ProcessorRuntimeState<State = unknown> = {
  snapshot: { offset: number; state: State };
  runtime?: Record<string, unknown>;
};

/**
 * Callback invoked by the stream pump for each delivered batch.
 *
 * It stays as a named type because Workers RPC callback lifecycle helpers need
 * to duplicate, retain, and dispose exactly this callback shape.
 */
export type ProcessEventBatch = (batch: StreamEventBatch) => unknown;

/** Command object for committing a batch of repo file mutations. */
export type CommitRepoFilesInput = {
  author?: { email: string; name: string };
  branch?: string;
  changes: RepoFileChange[];
  message: string;
};

/** Result returned after a repo commit attempt, including no-op commits. */
export type CommitRepoFilesResult = {
  branch: string;
  changedPaths: string[];
  commitOid: string;
  noChanges: boolean;
};

/** Command object for a coding-agent-style exact string edit. */
export type EditRepoFileInput = {
  author?: { email: string; name: string };
  branch?: string;
  message: string;
  newString: string;
  oldString: string;
  path: string;
  replaceAll?: boolean;
};

/** Result returned after an exact string edit commit attempt. */
export type EditRepoFileResult = CommitRepoFilesResult & {
  occurrenceCount: number;
  path: string;
};

export type RepoProcessorState = {
  artifactName: string | null;
  created: boolean;
  defaultBranch: string | null;
  initialized: boolean;
  remote: string | null;
};

/** What a project itx's `__describe()` returns: the Description convention plus identity and the capability inventory. */
export type ProjectDescription = Description & {
  capabilities: CapabilityDescription[];
  name: string;
  projectId: string;
};

export type ProjectProcessorState = {
  agents: StreamListItem[];
  createRequest: { projectId: string; slug: string } | null;
  created: boolean;
  repos: StreamListItem[];
  secrets: StreamListItem[];
  streams: StreamListItem[];
};

/** Capability recipe accepted by `provideCapability`. */
export type ProvideCapabilityInput =
  | {
      capability: unknown;
      flattenNestedPaths?: false;
      instructions?: string;
      path: string[];
      type: "live";
      types?: string;
    }
  | {
      capability: FlattenedCapabilityTarget;
      flattenNestedPaths: true;
      instructions?: string;
      path: string[];
      type: "live";
      types?: string;
    }
  | {
      expression: ItxExpression;
      flattenNestedPaths?: boolean;
      instructions?: string;
      path: string[];
      type: "itx-expression";
      types?: string;
    };

/** Revoke command for the current mount at a path or one exact mount offset. */
export type RevokeCapabilityInput = {
  path: string[];
  providedAtOffset?: number;
};

/** Dynamic worker RPC stub plus the disposal operation owned by the caller. */
export type DynamicWorkerCapability<T extends object = Record<string, unknown>> = T & Disposable;

/**
 * Whether a project the directory knows about actually exists in THIS
 * deployment's engine:
 * - `ready` — the project stream's bootstrap saga ran (`state.created`).
 * - `missing` — the engine has no state for it (e.g. the deployment was reset
 *   while the auth worker kept its rows); it can be set up again.
 * - `unknown` — the probe failed (engine hiccup); don't block the list on it.
 */
export type ProjectDeploymentStatus = "ready" | "missing" | "unknown";

/**
 * Batch delivered to stream processors and live subscribers.
 *
 * Kept named because callback retention, processor hosts, and tests all depend
 * on the same cross-RPC batch envelope.
 */
export type StreamEventBatch = {
  projectId: string | null;
  path: string;
  events: StreamEvent[];
  streamMaxOffset: number;
  state: unknown;
};

/**
 * One repo file mutation.
 *
 * Kept named because public `Repo.commitFiles`, input parsing, and artifact
 * commit implementation all validate the same command shape.
 */
export type RepoFileChange =
  | {
      path: string;
      content: string;
    }
  | {
      path: string;
      delete: true;
    };

export type ProcessorSnapshot<State> = {
  offset: number;
  state: State;
};

export type CapabilityDescription = {
  instructions?: string;
  path: string[];
  providedAtOffset?: number;
  /**
   * The itx scope path this capability is declared at (`"/"`, `"/agents/bla"`, …).
   * Set when a scope reports capabilities it inherited from an enclosing scope,
   * so the reader can tell a local mount from an inherited one. Absent on
   * built-ins (they exist at every scope).
   */
  scope?: string;
  type: "builtin" | "live" | "itx-expression";
  types?: string;
};

export type StreamListItem = {
  createdAt: string;
  path: string;
};

export type AgentProcessorState = {
  currentRequest:
    | { phase: "scheduled"; requestId: string; scheduledOffset: number }
    | { phase: "requested"; llmRequestId: number }
    | null;
  history: Array<{ role: "user" | "assistant"; content: string }>;
  llmConfig: { model: string };
  llmProvider: "cloudflare-ai" | "openai-ws";
  pendingTriggerOffset: number | null;
  scriptExecutionsCompleted: string[];
  systemPrompt: string;
};

/** Target shape for a live capability that wants to receive flattened paths. */
export type FlattenedCapabilityTarget = {
  invokeCapability(input: FlattenedCapabilityInvocation): unknown;
};

export type ItxExpression = ItxExpressionStep[];

/** Live replacement for project egress. It sees getSecret(...) placeholders, never material. */
export type ProjectEgressInterceptor = (req: Request) => Promise<Response>;

export type ItxExampleSummary = {
  description: string;
  id: string;
  title: string;
};

export type ItxExampleWithCode = ItxExampleSummary & { code: string };

export type IntegrationProvider = "google" | "slack";

export type IntegrationConnectionStatus = {
  connected: boolean;
  displayName: string | null;
  externalId: string | null;
  metadata: Record<string, unknown>;
};

export type CompleteConnectResult =
  | { callbackUrl: string | null; ok: true }
  | { callbackUrl: string | null; error: string; ok: false };

export type McpClientConnectInput = {
  headers?: Record<string, string>;
  timeoutMs?: number;
  url: string;
};

export type McpClientRpc = object;

export type OpenApiConnectInput = {
  baseUrl?: string;
  headers?: Record<string, string>;
  specUrl: string;
};

export type OpenApiRpc = object;

/**
 * One Cloudflare Sandbox: the bare `@cloudflare/sandbox` Durable Object stub,
 * nothing wrapped on top. Whatever the installed SDK exposes is callable —
 * `exec(command)`, `readFile`/`writeFile`/`listFiles`, `startProcess`,
 * `gitCheckout`, `exposePort`, `destroy()`, … — so this contract deliberately
 * does not re-declare that surface (same stance as {@link McpClientRpc}); see
 * https://developers.cloudflare.com/sandbox/ for the API. One addition: every
 * container start kicks off a clone of the project's repo to
 * `/workspace/repo` — `await sandbox.ensureProjectRepo()` before work that
 * depends on it.
 */
export type CloudflareSandbox = object;

/** Worker recipe accepted by `workers.get` and worker-backed capabilities. */
export type DynamicWorkerRef = StatelessDynamicWorkerRef | StatefulDynamicWorkerRef;

/** Dynamic invocation envelope used by flattened live capabilities. */
export type FlattenedCapabilityInvocation = {
  args: unknown[];
  flattenNestedPath?: boolean;
  path: string[];
};

/** Durable expression over the project ITX surface. */
export type ItxExpressionStep = string | [method: string, ...args: unknown[]];

export type GmailRequestInput = {
  body?: unknown;
  headers?: Record<string, string>;
  method?: string;
  path: string;
  query?: Record<string, boolean | number | string | null | undefined>;
};

export type SecretDescription = {
  audit: {
    lastUsedAt?: string;
    lastUsedBy?: string;
    lastUsedUrl?: string;
    usedCount: number;
  };
  egress: { urls: string[] };
  hasMaterial: boolean;
};

export type SecretUpdateInput = {
  egress?: { urls: string[] };
  material?: string;
};

/**
 * Stateless workers are WorkerEntrypoint exports loaded directly from source.
 *
 * `props` are passed to `worker.getEntrypoint(name, { props })` and appear as
 * `this.ctx.props` inside the exported WorkerEntrypoint. They deliberately live
 * only on stateless refs: Durable Object facets are started with
 * `ctx.facets.get(name, () => ({ class, id? }))`, which does not accept
 * WorkerEntrypoint-style props.
 */
export type StatelessDynamicWorkerRef = DynamicWorkerRefBase & {
  type: "stateless";
  entrypoint?: string;
  props?: Record<string, JsonValue>;
};

/**
 * Stateful workers are Durable Object class exports hosted by
 * `StatefulWorkerDurableObject`.
 *
 * `durableWorkerKey` is the durable identity under `{ projectId, path }`. It is
 * not a source cache key: source changes deliberately affect the next use of the
 * same durable worker identity.
 */
export type StatefulDynamicWorkerRef = DynamicWorkerRefBase & {
  type: "stateful";
  className: string;
  durableWorkerKey: string;
};

type DynamicWorkerRefBase = {
  /**
   * ITX scope path for the worker's `env.ITX` binding and for stateful worker
   * Durable Object names. This is intentionally not the mounted capability path:
   * one worker can be mounted at `db`, `counter`, etc. while all events still
   * belong to the host stream path.
   */
  path: string;
  source: DynamicWorkerSource;
};

/** JSON subset accepted by WorkerEntrypoint props and script results. */
export type JsonValue =
  | string
  | number
  | boolean
  | null
  | JsonValue[]
  | { [key: string]: JsonValue };

/**
 * Declarative source for a dynamic worker.
 *
 * `inline` is the simplest execution primitive: the caller already has module
 * text and asks the Worker Loader to run it. `repo` keeps source identity
 * separate from runtime identity; the repo resolves the current worker source
 * and contributes its own cache key, so future repo commits affect the next use.
 */
export type DynamicWorkerSource =
  | {
      type: "inline";
      mainModule: string;
      modules: Record<string, string>;
    }
  | {
      type: "repo";
      repoPath: string;
      sourcePath: string;
    };
