// build-sdk.mjs — bundle src/sdk/index.ts (the pure StreamProcessor author class, the
// StreamProcessorDurableObject host, the contract helper, zod, capnweb's client) into a generated TS
// module the host injects as `processor.js` into EVERY loaded isolate. Single source of truth: the
// SAME stream/processor.ts the host tests is what userspace extends. Run by the test and deploy scripts; the generated file is committed so typecheck works
// without a build.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { build } from "esbuild";

// Write ONLY when the content actually changed — otherwise `wrangler dev`'s watcher sees the custom
// build rewrite src/generated/* and restarts the build, forever (the generated files are inside the
// watched `src`). Idempotent writes break that loop and keep git/no-op rebuilds clean.
function writeIfChanged(path, next) {
  let prev;
  try {
    prev = readFileSync(path, "utf8");
  } catch (e) {
    if (e?.code !== "ENOENT") throw e; // only "new file" is expected — surface EACCES/EISDIR/etc
  }
  if (prev !== next) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, next);
  }
}

// `cloudflare:workers` stays external: the SDK's StreamProcessorDurableObject host extends the
// runtime's DurableObject, which exists only inside the loaded isolate.
const sdk = await build({
  entryPoints: ["src/sdk/index.ts"],
  bundle: true,
  format: "esm",
  platform: "neutral",
  target: "es2022",
  minify: true,
  write: false,
  external: ["cloudflare:workers"],
});
writeIfChanged(
  "src/generated/processor-sdk.ts",
  "// GENERATED by build-sdk.mjs from src/sdk/index.ts — do not edit.\n" +
    `export const PROCESSOR_SDK_MODULE = ${JSON.stringify(sdk.outputFiles[0].text)};\n`,
);
console.log(`processor.js: ${(sdk.outputFiles[0].text.length / 1024).toFixed(1)} KiB`);

// The hosted demo page: bundle src/client/demo.tsx (React + react-dom + the capnweb fork + the
// useLiveState hook, all inlined — no CDN) into ONE module script, inline it in an HTML doc, and
// write it to public/demo.html — a Workers STATIC ASSET (wrangler.jsonc `assets`), served at /demo
// by the platform before the worker runs, never part of the worker script (it was 255 KiB of the
// 1.48 MB upload as an inlined string, resident in every /api and DO isolate). platform:"browser"
// (this runs in a browser, not workerd); React 19 automatic JSX.
const demo = await build({
  entryPoints: ["src/client/demo.tsx"],
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2022",
  jsx: "automatic",
  jsxImportSource: "react",
  // React reads process.env.NODE_ENV; without this it runs the DEV build (StrictMode double-invokes
  // effects, which double-dials the capnweb session). Pin production for the served bundle.
  define: { "process.env.NODE_ENV": '"production"' },
  minify: true,
  write: false,
});
const demoHtml =
  `<!doctype html><html lang="en"><head><meta charset="utf-8">` +
  `<meta name="viewport" content="width=device-width,initial-scale=1">` +
  `<title>clean-room live state</title></head>` +
  `<body><main id="root"></main><script type="module">${demo.outputFiles[0].text}</script></body></html>`;
writeIfChanged("public/demo.html", demoHtml);
console.log(`demo.html: ${(demoHtml.length / 1024).toFixed(1)} KiB`);
