// build-sdk.mjs — bundle src/sdk.ts (base class + contract helper + zod) into a generated TS
// module the host injects as `processor.js` into userspace processor isolates. Single source of
// truth: the SAME core/processor.ts the host runs is what userspace extends. Run by the test
// and deploy scripts; the generated file is committed so typecheck works without a build.
import { build } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";

// Write ONLY when the content actually changed — otherwise `wrangler dev`'s watcher sees the custom
// build rewrite src/generated/* and restarts the build, forever (the generated files are inside the
// watched `src`). Idempotent writes break that loop and keep git/no-op rebuilds clean.
function writeIfChanged(path, next) {
  let prev;
  try {
    prev = readFileSync(path, "utf8");
  } catch {
    /* new file */
  }
  if (prev !== next) writeFileSync(path, next);
}

const sdk = await build({
  entryPoints: ["src/sdk.ts"],
  bundle: true,
  format: "esm",
  platform: "neutral",
  target: "es2022",
  minify: true,
  write: false,
});
writeIfChanged(
  "src/generated/processor-sdk.ts",
  "// GENERATED by build-sdk.mjs from src/sdk.ts — do not edit.\n" +
    `export const PROCESSOR_SDK_MODULE = ${JSON.stringify(sdk.outputFiles[0].text)};\n`,
);
console.log(`processor.js: ${(sdk.outputFiles[0].text.length / 1024).toFixed(1)} KiB`);

// The runner: REAL TypeScript (src/runner-entry.ts) — cap.js/processor.js/cloudflare:workers
// stay external (they exist only inside the loaded isolate).
const runner = await build({
  entryPoints: ["src/runner-entry.ts"],
  bundle: true,
  format: "esm",
  platform: "neutral",
  target: "es2022",
  minify: true,
  write: false,
  external: ["cloudflare:workers", "./cap.js", "./processor.js"],
});
writeIfChanged(
  "src/generated/processor-runner.ts",
  "// GENERATED by build-sdk.mjs from src/runner-entry.ts — do not edit.\n" +
    `export const PROCESSOR_RUNNER_MODULE = ${JSON.stringify(runner.outputFiles[0].text)};\n`,
);
console.log(`runner.js: ${(runner.outputFiles[0].text.length / 1024).toFixed(1)} KiB`);

// The hosted demo page: bundle src/client/demo.tsx (React + react-dom + the capnweb fork + the
// useLiveState hook, all inlined — no CDN) into ONE module script, inline it in an HTML doc, and
// emit it as a string the worker serves at /demo (worker.ts). The starter-apps/todo idiom, on
// esbuild. platform:"browser" (this runs in a browser, not workerd); React 19 automatic JSX.
const demo = await build({
  entryPoints: ["src/client/demo.tsx"],
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2022",
  jsx: "automatic",
  jsxImportSource: "react",
  // React reads process.env.NODE_ENV; without this it runs the DEV build (StrictMode double-invokes
  // effects, which double-dials the capnweb session). Pin production for the served bundle.
  define: { "process.env.NODE_ENV": '"production"' },
  minify: true,
  write: false,
});
const demoHtml =
  `<!doctype html><html lang="en"><head><meta charset="utf-8">` +
  `<meta name="viewport" content="width=device-width,initial-scale=1">` +
  `<title>clean-room live state</title></head>` +
  `<body><main id="root"></main><script type="module">${demo.outputFiles[0].text}</script></body></html>`;
writeIfChanged(
  "src/generated/demo-page.ts",
  "// GENERATED by build-sdk.mjs from src/client/demo.tsx — do not edit.\n" +
    `export const DEMO_PAGE_HTML = ${JSON.stringify(demoHtml)};\n`,
);
console.log(`demo.html: ${(demoHtml.length / 1024).toFixed(1)} KiB`);
