/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/root.tsx'
import { Route as loginRouteImport } from './routes/login.tsx'
import { Route as authRequiredDotlayoutRouteImport } from './routes/auth-required.layout.tsx'
import { Route as userSettingsRouteImport } from './routes/user-settings.tsx'
import { Route as newOrganizationRouteImport } from './routes/new-organization.tsx'
import { Route as adminLayoutRouteImport } from './routes/admin/layout.tsx'
import { Route as orgLayoutRouteImport } from './routes/org/layout.tsx'
import { Route as indexRouteImport } from './routes/index.tsx'
import { Route as adminIndexRouteImport } from './routes/admin/index.tsx'
import { Route as orgIndexRouteImport } from './routes/org/index.tsx'
import { Route as adminTrpcToolsRouteImport } from './routes/admin/trpc-tools.tsx'
import { Route as adminSlackNotificationRouteImport } from './routes/admin/slack-notification.tsx'
import { Route as adminSessionInfoRouteImport } from './routes/admin/session-info.tsx'
import { Route as adminEstatesRouteImport } from './routes/admin/estates.tsx'
import { Route as adminDbToolsRouteImport } from './routes/admin/db-tools.tsx'
import { Route as orgTeamRouteImport } from './routes/org/team.tsx'
import { Route as orgSettingsRouteImport } from './routes/org/settings.tsx'
import { Route as orgEstateLayoutRouteImport } from './routes/org/estate/layout.tsx'
import { Route as orgEstateIndexRouteImport } from './routes/org/estate/index.tsx'
import { Route as orgEstateRepoRouteImport } from './routes/org/estate/repo.tsx'
import { Route as orgEstateIntegrationsIndexRouteImport } from './routes/org/estate/integrations/index.tsx'
import { Route as orgEstateIntegrationsRedirectRouteImport } from './routes/org/estate/integrations/redirect.tsx'
import { Route as orgEstateIntegrationsMcpParamsRouteImport } from './routes/org/estate/integrations/mcp-params.tsx'
import { Route as offlineAgentDetailRouteImport } from './routes/offline-agent-detail.tsx'
import { Route as onlineAgentDetailRouteImport } from './routes/online-agent-detail.tsx'

const loginRoute = loginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authRequiredDotlayoutRoute = authRequiredDotlayoutRouteImport.update({
  id: '/_auth.layout',
  getParentRoute: () => rootRouteImport,
} as any)
const userSettingsRoute = userSettingsRouteImport.update({
  id: '/user-settings',
  path: '/user-settings',
  getParentRoute: () => authRequiredDotlayoutRoute,
} as any)
const newOrganizationRoute = newOrganizationRouteImport.update({
  id: '/new-organization',
  path: '/new-organization',
  getParentRoute: () => authRequiredDotlayoutRoute,
} as any)
const adminLayoutRoute = adminLayoutRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => authRequiredDotlayoutRoute,
} as any)
const orgLayoutRoute = orgLayoutRouteImport.update({
  id: '/$organizationId',
  path: '/$organizationId',
  getParentRoute: () => authRequiredDotlayoutRoute,
} as any)
const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authRequiredDotlayoutRoute,
} as any)
const adminIndexRoute = adminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => adminLayoutRoute,
} as any)
const orgIndexRoute = orgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => orgLayoutRoute,
} as any)
const adminTrpcToolsRoute = adminTrpcToolsRouteImport.update({
  id: '/trpc-tools',
  path: '/trpc-tools',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminSlackNotificationRoute = adminSlackNotificationRouteImport.update({
  id: '/slack-notification',
  path: '/slack-notification',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminSessionInfoRoute = adminSessionInfoRouteImport.update({
  id: '/session-info',
  path: '/session-info',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminEstatesRoute = adminEstatesRouteImport.update({
  id: '/estates',
  path: '/estates',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminDbToolsRoute = adminDbToolsRouteImport.update({
  id: '/db-tools',
  path: '/db-tools',
  getParentRoute: () => adminLayoutRoute,
} as any)
const orgTeamRoute = orgTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => orgLayoutRoute,
} as any)
const orgSettingsRoute = orgSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => orgLayoutRoute,
} as any)
const orgEstateLayoutRoute = orgEstateLayoutRouteImport.update({
  id: '/$estateId',
  path: '/$estateId',
  getParentRoute: () => orgLayoutRoute,
} as any)
const orgEstateIndexRoute = orgEstateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => orgEstateLayoutRoute,
} as any)
const orgEstateRepoRoute = orgEstateRepoRouteImport.update({
  id: '/repo',
  path: '/repo',
  getParentRoute: () => orgEstateLayoutRoute,
} as any)
const orgEstateIntegrationsIndexRoute =
  orgEstateIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => orgEstateLayoutRoute,
  } as any)
const orgEstateIntegrationsRedirectRoute =
  orgEstateIntegrationsRedirectRouteImport.update({
    id: '/integrations/redirect',
    path: '/integrations/redirect',
    getParentRoute: () => orgEstateLayoutRoute,
  } as any)
const orgEstateIntegrationsMcpParamsRoute =
  orgEstateIntegrationsMcpParamsRouteImport.update({
    id: '/integrations/mcp-params',
    path: '/integrations/mcp-params',
    getParentRoute: () => orgEstateLayoutRoute,
  } as any)
const offlineAgentDetailRoute = offlineAgentDetailRouteImport.update({
  id: '/agents/offline',
  path: '/agents/offline',
  getParentRoute: () => orgEstateLayoutRoute,
} as any)
const onlineAgentDetailRoute = onlineAgentDetailRouteImport.update({
  id: '/agents/$agentClassName/$durableObjectName',
  path: '/agents/$agentClassName/$durableObjectName',
  getParentRoute: () => orgEstateLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof loginRoute
  '/': typeof indexRoute
  '/$organizationId': typeof orgLayoutRouteWithChildren
  '/admin': typeof adminLayoutRouteWithChildren
  '/new-organization': typeof newOrganizationRoute
  '/user-settings': typeof userSettingsRoute
  '/$organizationId/$estateId': typeof orgEstateLayoutRouteWithChildren
  '/$organizationId/settings': typeof orgSettingsRoute
  '/$organizationId/team': typeof orgTeamRoute
  '/admin/db-tools': typeof adminDbToolsRoute
  '/admin/estates': typeof adminEstatesRoute
  '/admin/session-info': typeof adminSessionInfoRoute
  '/admin/slack-notification': typeof adminSlackNotificationRoute
  '/admin/trpc-tools': typeof adminTrpcToolsRoute
  '/$organizationId/': typeof orgIndexRoute
  '/admin/': typeof adminIndexRoute
  '/$organizationId/$estateId/repo': typeof orgEstateRepoRoute
  '/$organizationId/$estateId/': typeof orgEstateIndexRoute
  '/$organizationId/$estateId/agents/offline': typeof offlineAgentDetailRoute
  '/$organizationId/$estateId/integrations/mcp-params': typeof orgEstateIntegrationsMcpParamsRoute
  '/$organizationId/$estateId/integrations/redirect': typeof orgEstateIntegrationsRedirectRoute
  '/$organizationId/$estateId/integrations': typeof orgEstateIntegrationsIndexRoute
  '/$organizationId/$estateId/agents/$agentClassName/$durableObjectName': typeof onlineAgentDetailRoute
}
export interface FileRoutesByTo {
  '/login': typeof loginRoute
  '/': typeof indexRoute
  '/new-organization': typeof newOrganizationRoute
  '/user-settings': typeof userSettingsRoute
  '/$organizationId/settings': typeof orgSettingsRoute
  '/$organizationId/team': typeof orgTeamRoute
  '/admin/db-tools': typeof adminDbToolsRoute
  '/admin/estates': typeof adminEstatesRoute
  '/admin/session-info': typeof adminSessionInfoRoute
  '/admin/slack-notification': typeof adminSlackNotificationRoute
  '/admin/trpc-tools': typeof adminTrpcToolsRoute
  '/$organizationId': typeof orgIndexRoute
  '/admin': typeof adminIndexRoute
  '/$organizationId/$estateId/repo': typeof orgEstateRepoRoute
  '/$organizationId/$estateId': typeof orgEstateIndexRoute
  '/$organizationId/$estateId/agents/offline': typeof offlineAgentDetailRoute
  '/$organizationId/$estateId/integrations/mcp-params': typeof orgEstateIntegrationsMcpParamsRoute
  '/$organizationId/$estateId/integrations/redirect': typeof orgEstateIntegrationsRedirectRoute
  '/$organizationId/$estateId/integrations': typeof orgEstateIntegrationsIndexRoute
  '/$organizationId/$estateId/agents/$agentClassName/$durableObjectName': typeof onlineAgentDetailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth.layout': typeof authRequiredDotlayoutRouteWithChildren
  '/login': typeof loginRoute
  '/_auth.layout/': typeof indexRoute
  '/_auth.layout/$organizationId': typeof orgLayoutRouteWithChildren
  '/_auth.layout/admin': typeof adminLayoutRouteWithChildren
  '/_auth.layout/new-organization': typeof newOrganizationRoute
  '/_auth.layout/user-settings': typeof userSettingsRoute
  '/_auth.layout/$organizationId/$estateId': typeof orgEstateLayoutRouteWithChildren
  '/_auth.layout/$organizationId/settings': typeof orgSettingsRoute
  '/_auth.layout/$organizationId/team': typeof orgTeamRoute
  '/_auth.layout/admin/db-tools': typeof adminDbToolsRoute
  '/_auth.layout/admin/estates': typeof adminEstatesRoute
  '/_auth.layout/admin/session-info': typeof adminSessionInfoRoute
  '/_auth.layout/admin/slack-notification': typeof adminSlackNotificationRoute
  '/_auth.layout/admin/trpc-tools': typeof adminTrpcToolsRoute
  '/_auth.layout/$organizationId/': typeof orgIndexRoute
  '/_auth.layout/admin/': typeof adminIndexRoute
  '/_auth.layout/$organizationId/$estateId/repo': typeof orgEstateRepoRoute
  '/_auth.layout/$organizationId/$estateId/': typeof orgEstateIndexRoute
  '/_auth.layout/$organizationId/$estateId/agents/offline': typeof offlineAgentDetailRoute
  '/_auth.layout/$organizationId/$estateId/integrations/mcp-params': typeof orgEstateIntegrationsMcpParamsRoute
  '/_auth.layout/$organizationId/$estateId/integrations/redirect': typeof orgEstateIntegrationsRedirectRoute
  '/_auth.layout/$organizationId/$estateId/integrations/': typeof orgEstateIntegrationsIndexRoute
  '/_auth.layout/$organizationId/$estateId/agents/$agentClassName/$durableObjectName': typeof onlineAgentDetailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/$organizationId'
    | '/admin'
    | '/new-organization'
    | '/user-settings'
    | '/$organizationId/$estateId'
    | '/$organizationId/settings'
    | '/$organizationId/team'
    | '/admin/db-tools'
    | '/admin/estates'
    | '/admin/session-info'
    | '/admin/slack-notification'
    | '/admin/trpc-tools'
    | '/$organizationId/'
    | '/admin/'
    | '/$organizationId/$estateId/repo'
    | '/$organizationId/$estateId/'
    | '/$organizationId/$estateId/agents/offline'
    | '/$organizationId/$estateId/integrations/mcp-params'
    | '/$organizationId/$estateId/integrations/redirect'
    | '/$organizationId/$estateId/integrations'
    | '/$organizationId/$estateId/agents/$agentClassName/$durableObjectName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/new-organization'
    | '/user-settings'
    | '/$organizationId/settings'
    | '/$organizationId/team'
    | '/admin/db-tools'
    | '/admin/estates'
    | '/admin/session-info'
    | '/admin/slack-notification'
    | '/admin/trpc-tools'
    | '/$organizationId'
    | '/admin'
    | '/$organizationId/$estateId/repo'
    | '/$organizationId/$estateId'
    | '/$organizationId/$estateId/agents/offline'
    | '/$organizationId/$estateId/integrations/mcp-params'
    | '/$organizationId/$estateId/integrations/redirect'
    | '/$organizationId/$estateId/integrations'
    | '/$organizationId/$estateId/agents/$agentClassName/$durableObjectName'
  id:
    | '__root__'
    | '/_auth.layout'
    | '/login'
    | '/_auth.layout/'
    | '/_auth.layout/$organizationId'
    | '/_auth.layout/admin'
    | '/_auth.layout/new-organization'
    | '/_auth.layout/user-settings'
    | '/_auth.layout/$organizationId/$estateId'
    | '/_auth.layout/$organizationId/settings'
    | '/_auth.layout/$organizationId/team'
    | '/_auth.layout/admin/db-tools'
    | '/_auth.layout/admin/estates'
    | '/_auth.layout/admin/session-info'
    | '/_auth.layout/admin/slack-notification'
    | '/_auth.layout/admin/trpc-tools'
    | '/_auth.layout/$organizationId/'
    | '/_auth.layout/admin/'
    | '/_auth.layout/$organizationId/$estateId/repo'
    | '/_auth.layout/$organizationId/$estateId/'
    | '/_auth.layout/$organizationId/$estateId/agents/offline'
    | '/_auth.layout/$organizationId/$estateId/integrations/mcp-params'
    | '/_auth.layout/$organizationId/$estateId/integrations/redirect'
    | '/_auth.layout/$organizationId/$estateId/integrations/'
    | '/_auth.layout/$organizationId/$estateId/agents/$agentClassName/$durableObjectName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRequiredDotlayoutRoute: typeof authRequiredDotlayoutRouteWithChildren
  loginRoute: typeof loginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof loginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth.layout': {
      id: '/_auth.layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRequiredDotlayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth.layout/user-settings': {
      id: '/_auth.layout/user-settings'
      path: '/user-settings'
      fullPath: '/user-settings'
      preLoaderRoute: typeof userSettingsRouteImport
      parentRoute: typeof authRequiredDotlayoutRoute
    }
    '/_auth.layout/new-organization': {
      id: '/_auth.layout/new-organization'
      path: '/new-organization'
      fullPath: '/new-organization'
      preLoaderRoute: typeof newOrganizationRouteImport
      parentRoute: typeof authRequiredDotlayoutRoute
    }
    '/_auth.layout/admin': {
      id: '/_auth.layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof adminLayoutRouteImport
      parentRoute: typeof authRequiredDotlayoutRoute
    }
    '/_auth.layout/$organizationId': {
      id: '/_auth.layout/$organizationId'
      path: '/$organizationId'
      fullPath: '/$organizationId'
      preLoaderRoute: typeof orgLayoutRouteImport
      parentRoute: typeof authRequiredDotlayoutRoute
    }
    '/_auth.layout/': {
      id: '/_auth.layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexRouteImport
      parentRoute: typeof authRequiredDotlayoutRoute
    }
    '/_auth.layout/admin/': {
      id: '/_auth.layout/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof adminIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/_auth.layout/$organizationId/': {
      id: '/_auth.layout/$organizationId/'
      path: '/'
      fullPath: '/$organizationId/'
      preLoaderRoute: typeof orgIndexRouteImport
      parentRoute: typeof orgLayoutRoute
    }
    '/_auth.layout/admin/trpc-tools': {
      id: '/_auth.layout/admin/trpc-tools'
      path: '/trpc-tools'
      fullPath: '/admin/trpc-tools'
      preLoaderRoute: typeof adminTrpcToolsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/_auth.layout/admin/slack-notification': {
      id: '/_auth.layout/admin/slack-notification'
      path: '/slack-notification'
      fullPath: '/admin/slack-notification'
      preLoaderRoute: typeof adminSlackNotificationRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/_auth.layout/admin/session-info': {
      id: '/_auth.layout/admin/session-info'
      path: '/session-info'
      fullPath: '/admin/session-info'
      preLoaderRoute: typeof adminSessionInfoRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/_auth.layout/admin/estates': {
      id: '/_auth.layout/admin/estates'
      path: '/estates'
      fullPath: '/admin/estates'
      preLoaderRoute: typeof adminEstatesRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/_auth.layout/admin/db-tools': {
      id: '/_auth.layout/admin/db-tools'
      path: '/db-tools'
      fullPath: '/admin/db-tools'
      preLoaderRoute: typeof adminDbToolsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/_auth.layout/$organizationId/team': {
      id: '/_auth.layout/$organizationId/team'
      path: '/team'
      fullPath: '/$organizationId/team'
      preLoaderRoute: typeof orgTeamRouteImport
      parentRoute: typeof orgLayoutRoute
    }
    '/_auth.layout/$organizationId/settings': {
      id: '/_auth.layout/$organizationId/settings'
      path: '/settings'
      fullPath: '/$organizationId/settings'
      preLoaderRoute: typeof orgSettingsRouteImport
      parentRoute: typeof orgLayoutRoute
    }
    '/_auth.layout/$organizationId/$estateId': {
      id: '/_auth.layout/$organizationId/$estateId'
      path: '/$estateId'
      fullPath: '/$organizationId/$estateId'
      preLoaderRoute: typeof orgEstateLayoutRouteImport
      parentRoute: typeof orgLayoutRoute
    }
    '/_auth.layout/$organizationId/$estateId/': {
      id: '/_auth.layout/$organizationId/$estateId/'
      path: '/'
      fullPath: '/$organizationId/$estateId/'
      preLoaderRoute: typeof orgEstateIndexRouteImport
      parentRoute: typeof orgEstateLayoutRoute
    }
    '/_auth.layout/$organizationId/$estateId/repo': {
      id: '/_auth.layout/$organizationId/$estateId/repo'
      path: '/repo'
      fullPath: '/$organizationId/$estateId/repo'
      preLoaderRoute: typeof orgEstateRepoRouteImport
      parentRoute: typeof orgEstateLayoutRoute
    }
    '/_auth.layout/$organizationId/$estateId/integrations/': {
      id: '/_auth.layout/$organizationId/$estateId/integrations/'
      path: '/integrations'
      fullPath: '/$organizationId/$estateId/integrations'
      preLoaderRoute: typeof orgEstateIntegrationsIndexRouteImport
      parentRoute: typeof orgEstateLayoutRoute
    }
    '/_auth.layout/$organizationId/$estateId/integrations/redirect': {
      id: '/_auth.layout/$organizationId/$estateId/integrations/redirect'
      path: '/integrations/redirect'
      fullPath: '/$organizationId/$estateId/integrations/redirect'
      preLoaderRoute: typeof orgEstateIntegrationsRedirectRouteImport
      parentRoute: typeof orgEstateLayoutRoute
    }
    '/_auth.layout/$organizationId/$estateId/integrations/mcp-params': {
      id: '/_auth.layout/$organizationId/$estateId/integrations/mcp-params'
      path: '/integrations/mcp-params'
      fullPath: '/$organizationId/$estateId/integrations/mcp-params'
      preLoaderRoute: typeof orgEstateIntegrationsMcpParamsRouteImport
      parentRoute: typeof orgEstateLayoutRoute
    }
    '/_auth.layout/$organizationId/$estateId/agents/offline': {
      id: '/_auth.layout/$organizationId/$estateId/agents/offline'
      path: '/agents/offline'
      fullPath: '/$organizationId/$estateId/agents/offline'
      preLoaderRoute: typeof offlineAgentDetailRouteImport
      parentRoute: typeof orgEstateLayoutRoute
    }
    '/_auth.layout/$organizationId/$estateId/agents/$agentClassName/$durableObjectName': {
      id: '/_auth.layout/$organizationId/$estateId/agents/$agentClassName/$durableObjectName'
      path: '/agents/$agentClassName/$durableObjectName'
      fullPath: '/$organizationId/$estateId/agents/$agentClassName/$durableObjectName'
      preLoaderRoute: typeof onlineAgentDetailRouteImport
      parentRoute: typeof orgEstateLayoutRoute
    }
  }
}

interface orgEstateLayoutRouteChildren {
  orgEstateRepoRoute: typeof orgEstateRepoRoute
  orgEstateIndexRoute: typeof orgEstateIndexRoute
  offlineAgentDetailRoute: typeof offlineAgentDetailRoute
  orgEstateIntegrationsMcpParamsRoute: typeof orgEstateIntegrationsMcpParamsRoute
  orgEstateIntegrationsRedirectRoute: typeof orgEstateIntegrationsRedirectRoute
  orgEstateIntegrationsIndexRoute: typeof orgEstateIntegrationsIndexRoute
  onlineAgentDetailRoute: typeof onlineAgentDetailRoute
}

const orgEstateLayoutRouteChildren: orgEstateLayoutRouteChildren = {
  orgEstateRepoRoute: orgEstateRepoRoute,
  orgEstateIndexRoute: orgEstateIndexRoute,
  offlineAgentDetailRoute: offlineAgentDetailRoute,
  orgEstateIntegrationsMcpParamsRoute: orgEstateIntegrationsMcpParamsRoute,
  orgEstateIntegrationsRedirectRoute: orgEstateIntegrationsRedirectRoute,
  orgEstateIntegrationsIndexRoute: orgEstateIntegrationsIndexRoute,
  onlineAgentDetailRoute: onlineAgentDetailRoute,
}

const orgEstateLayoutRouteWithChildren = orgEstateLayoutRoute._addFileChildren(
  orgEstateLayoutRouteChildren,
)

interface orgLayoutRouteChildren {
  orgEstateLayoutRoute: typeof orgEstateLayoutRouteWithChildren
  orgSettingsRoute: typeof orgSettingsRoute
  orgTeamRoute: typeof orgTeamRoute
  orgIndexRoute: typeof orgIndexRoute
}

const orgLayoutRouteChildren: orgLayoutRouteChildren = {
  orgEstateLayoutRoute: orgEstateLayoutRouteWithChildren,
  orgSettingsRoute: orgSettingsRoute,
  orgTeamRoute: orgTeamRoute,
  orgIndexRoute: orgIndexRoute,
}

const orgLayoutRouteWithChildren = orgLayoutRoute._addFileChildren(
  orgLayoutRouteChildren,
)

interface adminLayoutRouteChildren {
  adminDbToolsRoute: typeof adminDbToolsRoute
  adminEstatesRoute: typeof adminEstatesRoute
  adminSessionInfoRoute: typeof adminSessionInfoRoute
  adminSlackNotificationRoute: typeof adminSlackNotificationRoute
  adminTrpcToolsRoute: typeof adminTrpcToolsRoute
  adminIndexRoute: typeof adminIndexRoute
}

const adminLayoutRouteChildren: adminLayoutRouteChildren = {
  adminDbToolsRoute: adminDbToolsRoute,
  adminEstatesRoute: adminEstatesRoute,
  adminSessionInfoRoute: adminSessionInfoRoute,
  adminSlackNotificationRoute: adminSlackNotificationRoute,
  adminTrpcToolsRoute: adminTrpcToolsRoute,
  adminIndexRoute: adminIndexRoute,
}

const adminLayoutRouteWithChildren = adminLayoutRoute._addFileChildren(
  adminLayoutRouteChildren,
)

interface authRequiredDotlayoutRouteChildren {
  indexRoute: typeof indexRoute
  orgLayoutRoute: typeof orgLayoutRouteWithChildren
  adminLayoutRoute: typeof adminLayoutRouteWithChildren
  newOrganizationRoute: typeof newOrganizationRoute
  userSettingsRoute: typeof userSettingsRoute
}

const authRequiredDotlayoutRouteChildren: authRequiredDotlayoutRouteChildren = {
  indexRoute: indexRoute,
  orgLayoutRoute: orgLayoutRouteWithChildren,
  adminLayoutRoute: adminLayoutRouteWithChildren,
  newOrganizationRoute: newOrganizationRoute,
  userSettingsRoute: userSettingsRoute,
}

const authRequiredDotlayoutRouteWithChildren =
  authRequiredDotlayoutRoute._addFileChildren(
    authRequiredDotlayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  authRequiredDotlayoutRoute: authRequiredDotlayoutRouteWithChildren,
  loginRoute: loginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
