/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/root.tsx'
import { Route as loginRouteImport } from './routes/login.tsx'
import { Route as authRequiredDotlayoutRouteImport } from './routes/auth-required.layout.tsx'
import { Route as userSettingsRouteImport } from './routes/user-settings.tsx'
import { Route as newOrganizationRouteImport } from './routes/new-organization.tsx'
import { Route as adminLayoutRouteImport } from './routes/admin/layout.tsx'
import { Route as orgLayoutRouteImport } from './routes/org/layout.tsx'
import { Route as indexRouteImport } from './routes/index.tsx'
import { Route as adminIndexRouteImport } from './routes/admin/index.tsx'
import { Route as orgIndexRouteImport } from './routes/org/index.tsx'
import { Route as adminTrpcToolsRouteImport } from './routes/admin/trpc-tools.tsx'
import { Route as adminSlackNotificationRouteImport } from './routes/admin/slack-notification.tsx'
import { Route as adminSessionInfoRouteImport } from './routes/admin/session-info.tsx'
import { Route as adminInstallationsRouteImport } from './routes/admin/installations.tsx'
import { Route as adminDbToolsRouteImport } from './routes/admin/db-tools.tsx'
import { Route as orgTeamRouteImport } from './routes/org/team.tsx'
import { Route as orgSettingsRouteImport } from './routes/org/settings.tsx'
import { Route as orgInstallationLayoutRouteImport } from './routes/org/installation/layout.tsx'
import { Route as orgInstallationIndexRouteImport } from './routes/org/installation/index.tsx'
import { Route as orgInstallationRepoRouteImport } from './routes/org/installation/repo.tsx'
import { Route as orgInstallationOnboardingRouteImport } from './routes/org/installation/onboarding.tsx'
import { Route as orgInstallationIntegrationsIndexRouteImport } from './routes/org/installation/integrations/index.tsx'
import { Route as orgInstallationIntegrationsRedirectRouteImport } from './routes/org/installation/integrations/redirect.tsx'
import { Route as orgInstallationIntegrationsMcpParamsRouteImport } from './routes/org/installation/integrations/mcp-params.tsx'
import { Route as offlineAgentDetailRouteImport } from './routes/offline-agent-detail.tsx'
import { Route as onlineAgentDetailRouteImport } from './routes/online-agent-detail.tsx'

const loginRoute = loginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authRequiredDotlayoutRoute = authRequiredDotlayoutRouteImport.update({
  id: '/_auth.layout',
  getParentRoute: () => rootRouteImport,
} as any)
const userSettingsRoute = userSettingsRouteImport.update({
  id: '/user-settings',
  path: '/user-settings',
  getParentRoute: () => authRequiredDotlayoutRoute,
} as any)
const newOrganizationRoute = newOrganizationRouteImport.update({
  id: '/new-organization',
  path: '/new-organization',
  getParentRoute: () => authRequiredDotlayoutRoute,
} as any)
const adminLayoutRoute = adminLayoutRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => authRequiredDotlayoutRoute,
} as any)
const orgLayoutRoute = orgLayoutRouteImport.update({
  id: '/$organizationId',
  path: '/$organizationId',
  getParentRoute: () => authRequiredDotlayoutRoute,
} as any)
const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authRequiredDotlayoutRoute,
} as any)
const adminIndexRoute = adminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => adminLayoutRoute,
} as any)
const orgIndexRoute = orgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => orgLayoutRoute,
} as any)
const adminTrpcToolsRoute = adminTrpcToolsRouteImport.update({
  id: '/trpc-tools',
  path: '/trpc-tools',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminSlackNotificationRoute = adminSlackNotificationRouteImport.update({
  id: '/slack-notification',
  path: '/slack-notification',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminSessionInfoRoute = adminSessionInfoRouteImport.update({
  id: '/session-info',
  path: '/session-info',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminInstallationsRoute = adminInstallationsRouteImport.update({
  id: '/installations',
  path: '/installations',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminDbToolsRoute = adminDbToolsRouteImport.update({
  id: '/db-tools',
  path: '/db-tools',
  getParentRoute: () => adminLayoutRoute,
} as any)
const orgTeamRoute = orgTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => orgLayoutRoute,
} as any)
const orgSettingsRoute = orgSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => orgLayoutRoute,
} as any)
const orgInstallationLayoutRoute = orgInstallationLayoutRouteImport.update({
  id: '/$installationId',
  path: '/$installationId',
  getParentRoute: () => orgLayoutRoute,
} as any)
const orgInstallationIndexRoute = orgInstallationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => orgInstallationLayoutRoute,
} as any)
const orgInstallationRepoRoute = orgInstallationRepoRouteImport.update({
  id: '/repo',
  path: '/repo',
  getParentRoute: () => orgInstallationLayoutRoute,
} as any)
const orgInstallationOnboardingRoute =
  orgInstallationOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => orgInstallationLayoutRoute,
  } as any)
const orgInstallationIntegrationsIndexRoute =
  orgInstallationIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => orgInstallationLayoutRoute,
  } as any)
const orgInstallationIntegrationsRedirectRoute =
  orgInstallationIntegrationsRedirectRouteImport.update({
    id: '/integrations/redirect',
    path: '/integrations/redirect',
    getParentRoute: () => orgInstallationLayoutRoute,
  } as any)
const orgInstallationIntegrationsMcpParamsRoute =
  orgInstallationIntegrationsMcpParamsRouteImport.update({
    id: '/integrations/mcp-params',
    path: '/integrations/mcp-params',
    getParentRoute: () => orgInstallationLayoutRoute,
  } as any)
const offlineAgentDetailRoute = offlineAgentDetailRouteImport.update({
  id: '/agents/offline',
  path: '/agents/offline',
  getParentRoute: () => orgInstallationLayoutRoute,
} as any)
const onlineAgentDetailRoute = onlineAgentDetailRouteImport.update({
  id: '/agents/$agentClassName/$durableObjectName',
  path: '/agents/$agentClassName/$durableObjectName',
  getParentRoute: () => orgInstallationLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof loginRoute
  '/': typeof indexRoute
  '/$organizationId': typeof orgLayoutRouteWithChildren
  '/admin': typeof adminLayoutRouteWithChildren
  '/new-organization': typeof newOrganizationRoute
  '/user-settings': typeof userSettingsRoute
  '/$organizationId/$installationId': typeof orgInstallationLayoutRouteWithChildren
  '/$organizationId/settings': typeof orgSettingsRoute
  '/$organizationId/team': typeof orgTeamRoute
  '/admin/db-tools': typeof adminDbToolsRoute
  '/admin/installations': typeof adminInstallationsRoute
  '/admin/session-info': typeof adminSessionInfoRoute
  '/admin/slack-notification': typeof adminSlackNotificationRoute
  '/admin/trpc-tools': typeof adminTrpcToolsRoute
  '/$organizationId/': typeof orgIndexRoute
  '/admin/': typeof adminIndexRoute
  '/$organizationId/$installationId/onboarding': typeof orgInstallationOnboardingRoute
  '/$organizationId/$installationId/repo': typeof orgInstallationRepoRoute
  '/$organizationId/$installationId/': typeof orgInstallationIndexRoute
  '/$organizationId/$installationId/agents/offline': typeof offlineAgentDetailRoute
  '/$organizationId/$installationId/integrations/mcp-params': typeof orgInstallationIntegrationsMcpParamsRoute
  '/$organizationId/$installationId/integrations/redirect': typeof orgInstallationIntegrationsRedirectRoute
  '/$organizationId/$installationId/integrations': typeof orgInstallationIntegrationsIndexRoute
  '/$organizationId/$installationId/agents/$agentClassName/$durableObjectName': typeof onlineAgentDetailRoute
}
export interface FileRoutesByTo {
  '/login': typeof loginRoute
  '/': typeof indexRoute
  '/new-organization': typeof newOrganizationRoute
  '/user-settings': typeof userSettingsRoute
  '/$organizationId/settings': typeof orgSettingsRoute
  '/$organizationId/team': typeof orgTeamRoute
  '/admin/db-tools': typeof adminDbToolsRoute
  '/admin/installations': typeof adminInstallationsRoute
  '/admin/session-info': typeof adminSessionInfoRoute
  '/admin/slack-notification': typeof adminSlackNotificationRoute
  '/admin/trpc-tools': typeof adminTrpcToolsRoute
  '/$organizationId': typeof orgIndexRoute
  '/admin': typeof adminIndexRoute
  '/$organizationId/$installationId/onboarding': typeof orgInstallationOnboardingRoute
  '/$organizationId/$installationId/repo': typeof orgInstallationRepoRoute
  '/$organizationId/$installationId': typeof orgInstallationIndexRoute
  '/$organizationId/$installationId/agents/offline': typeof offlineAgentDetailRoute
  '/$organizationId/$installationId/integrations/mcp-params': typeof orgInstallationIntegrationsMcpParamsRoute
  '/$organizationId/$installationId/integrations/redirect': typeof orgInstallationIntegrationsRedirectRoute
  '/$organizationId/$installationId/integrations': typeof orgInstallationIntegrationsIndexRoute
  '/$organizationId/$installationId/agents/$agentClassName/$durableObjectName': typeof onlineAgentDetailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth.layout': typeof authRequiredDotlayoutRouteWithChildren
  '/login': typeof loginRoute
  '/_auth.layout/': typeof indexRoute
  '/_auth.layout/$organizationId': typeof orgLayoutRouteWithChildren
  '/_auth.layout/admin': typeof adminLayoutRouteWithChildren
  '/_auth.layout/new-organization': typeof newOrganizationRoute
  '/_auth.layout/user-settings': typeof userSettingsRoute
  '/_auth.layout/$organizationId/$installationId': typeof orgInstallationLayoutRouteWithChildren
  '/_auth.layout/$organizationId/settings': typeof orgSettingsRoute
  '/_auth.layout/$organizationId/team': typeof orgTeamRoute
  '/_auth.layout/admin/db-tools': typeof adminDbToolsRoute
  '/_auth.layout/admin/installations': typeof adminInstallationsRoute
  '/_auth.layout/admin/session-info': typeof adminSessionInfoRoute
  '/_auth.layout/admin/slack-notification': typeof adminSlackNotificationRoute
  '/_auth.layout/admin/trpc-tools': typeof adminTrpcToolsRoute
  '/_auth.layout/$organizationId/': typeof orgIndexRoute
  '/_auth.layout/admin/': typeof adminIndexRoute
  '/_auth.layout/$organizationId/$installationId/onboarding': typeof orgInstallationOnboardingRoute
  '/_auth.layout/$organizationId/$installationId/repo': typeof orgInstallationRepoRoute
  '/_auth.layout/$organizationId/$installationId/': typeof orgInstallationIndexRoute
  '/_auth.layout/$organizationId/$installationId/agents/offline': typeof offlineAgentDetailRoute
  '/_auth.layout/$organizationId/$installationId/integrations/mcp-params': typeof orgInstallationIntegrationsMcpParamsRoute
  '/_auth.layout/$organizationId/$installationId/integrations/redirect': typeof orgInstallationIntegrationsRedirectRoute
  '/_auth.layout/$organizationId/$installationId/integrations/': typeof orgInstallationIntegrationsIndexRoute
  '/_auth.layout/$organizationId/$installationId/agents/$agentClassName/$durableObjectName': typeof onlineAgentDetailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/$organizationId'
    | '/admin'
    | '/new-organization'
    | '/user-settings'
    | '/$organizationId/$installationId'
    | '/$organizationId/settings'
    | '/$organizationId/team'
    | '/admin/db-tools'
    | '/admin/installations'
    | '/admin/session-info'
    | '/admin/slack-notification'
    | '/admin/trpc-tools'
    | '/$organizationId/'
    | '/admin/'
    | '/$organizationId/$installationId/onboarding'
    | '/$organizationId/$installationId/repo'
    | '/$organizationId/$installationId/'
    | '/$organizationId/$installationId/agents/offline'
    | '/$organizationId/$installationId/integrations/mcp-params'
    | '/$organizationId/$installationId/integrations/redirect'
    | '/$organizationId/$installationId/integrations'
    | '/$organizationId/$installationId/agents/$agentClassName/$durableObjectName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/new-organization'
    | '/user-settings'
    | '/$organizationId/settings'
    | '/$organizationId/team'
    | '/admin/db-tools'
    | '/admin/installations'
    | '/admin/session-info'
    | '/admin/slack-notification'
    | '/admin/trpc-tools'
    | '/$organizationId'
    | '/admin'
    | '/$organizationId/$installationId/onboarding'
    | '/$organizationId/$installationId/repo'
    | '/$organizationId/$installationId'
    | '/$organizationId/$installationId/agents/offline'
    | '/$organizationId/$installationId/integrations/mcp-params'
    | '/$organizationId/$installationId/integrations/redirect'
    | '/$organizationId/$installationId/integrations'
    | '/$organizationId/$installationId/agents/$agentClassName/$durableObjectName'
  id:
    | '__root__'
    | '/_auth.layout'
    | '/login'
    | '/_auth.layout/'
    | '/_auth.layout/$organizationId'
    | '/_auth.layout/admin'
    | '/_auth.layout/new-organization'
    | '/_auth.layout/user-settings'
    | '/_auth.layout/$organizationId/$installationId'
    | '/_auth.layout/$organizationId/settings'
    | '/_auth.layout/$organizationId/team'
    | '/_auth.layout/admin/db-tools'
    | '/_auth.layout/admin/installations'
    | '/_auth.layout/admin/session-info'
    | '/_auth.layout/admin/slack-notification'
    | '/_auth.layout/admin/trpc-tools'
    | '/_auth.layout/$organizationId/'
    | '/_auth.layout/admin/'
    | '/_auth.layout/$organizationId/$installationId/onboarding'
    | '/_auth.layout/$organizationId/$installationId/repo'
    | '/_auth.layout/$organizationId/$installationId/'
    | '/_auth.layout/$organizationId/$installationId/agents/offline'
    | '/_auth.layout/$organizationId/$installationId/integrations/mcp-params'
    | '/_auth.layout/$organizationId/$installationId/integrations/redirect'
    | '/_auth.layout/$organizationId/$installationId/integrations/'
    | '/_auth.layout/$organizationId/$installationId/agents/$agentClassName/$durableObjectName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRequiredDotlayoutRoute: typeof authRequiredDotlayoutRouteWithChildren
  loginRoute: typeof loginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof loginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth.layout': {
      id: '/_auth.layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRequiredDotlayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth.layout/user-settings': {
      id: '/_auth.layout/user-settings'
      path: '/user-settings'
      fullPath: '/user-settings'
      preLoaderRoute: typeof userSettingsRouteImport
      parentRoute: typeof authRequiredDotlayoutRoute
    }
    '/_auth.layout/new-organization': {
      id: '/_auth.layout/new-organization'
      path: '/new-organization'
      fullPath: '/new-organization'
      preLoaderRoute: typeof newOrganizationRouteImport
      parentRoute: typeof authRequiredDotlayoutRoute
    }
    '/_auth.layout/admin': {
      id: '/_auth.layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof adminLayoutRouteImport
      parentRoute: typeof authRequiredDotlayoutRoute
    }
    '/_auth.layout/$organizationId': {
      id: '/_auth.layout/$organizationId'
      path: '/$organizationId'
      fullPath: '/$organizationId'
      preLoaderRoute: typeof orgLayoutRouteImport
      parentRoute: typeof authRequiredDotlayoutRoute
    }
    '/_auth.layout/': {
      id: '/_auth.layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexRouteImport
      parentRoute: typeof authRequiredDotlayoutRoute
    }
    '/_auth.layout/admin/': {
      id: '/_auth.layout/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof adminIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/_auth.layout/$organizationId/': {
      id: '/_auth.layout/$organizationId/'
      path: '/'
      fullPath: '/$organizationId/'
      preLoaderRoute: typeof orgIndexRouteImport
      parentRoute: typeof orgLayoutRoute
    }
    '/_auth.layout/admin/trpc-tools': {
      id: '/_auth.layout/admin/trpc-tools'
      path: '/trpc-tools'
      fullPath: '/admin/trpc-tools'
      preLoaderRoute: typeof adminTrpcToolsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/_auth.layout/admin/slack-notification': {
      id: '/_auth.layout/admin/slack-notification'
      path: '/slack-notification'
      fullPath: '/admin/slack-notification'
      preLoaderRoute: typeof adminSlackNotificationRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/_auth.layout/admin/session-info': {
      id: '/_auth.layout/admin/session-info'
      path: '/session-info'
      fullPath: '/admin/session-info'
      preLoaderRoute: typeof adminSessionInfoRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/_auth.layout/admin/installations': {
      id: '/_auth.layout/admin/installations'
      path: '/installations'
      fullPath: '/admin/installations'
      preLoaderRoute: typeof adminInstallationsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/_auth.layout/admin/db-tools': {
      id: '/_auth.layout/admin/db-tools'
      path: '/db-tools'
      fullPath: '/admin/db-tools'
      preLoaderRoute: typeof adminDbToolsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/_auth.layout/$organizationId/team': {
      id: '/_auth.layout/$organizationId/team'
      path: '/team'
      fullPath: '/$organizationId/team'
      preLoaderRoute: typeof orgTeamRouteImport
      parentRoute: typeof orgLayoutRoute
    }
    '/_auth.layout/$organizationId/settings': {
      id: '/_auth.layout/$organizationId/settings'
      path: '/settings'
      fullPath: '/$organizationId/settings'
      preLoaderRoute: typeof orgSettingsRouteImport
      parentRoute: typeof orgLayoutRoute
    }
    '/_auth.layout/$organizationId/$installationId': {
      id: '/_auth.layout/$organizationId/$installationId'
      path: '/$installationId'
      fullPath: '/$organizationId/$installationId'
      preLoaderRoute: typeof orgInstallationLayoutRouteImport
      parentRoute: typeof orgLayoutRoute
    }
    '/_auth.layout/$organizationId/$installationId/': {
      id: '/_auth.layout/$organizationId/$installationId/'
      path: '/'
      fullPath: '/$organizationId/$installationId/'
      preLoaderRoute: typeof orgInstallationIndexRouteImport
      parentRoute: typeof orgInstallationLayoutRoute
    }
    '/_auth.layout/$organizationId/$installationId/repo': {
      id: '/_auth.layout/$organizationId/$installationId/repo'
      path: '/repo'
      fullPath: '/$organizationId/$installationId/repo'
      preLoaderRoute: typeof orgInstallationRepoRouteImport
      parentRoute: typeof orgInstallationLayoutRoute
    }
    '/_auth.layout/$organizationId/$installationId/onboarding': {
      id: '/_auth.layout/$organizationId/$installationId/onboarding'
      path: '/onboarding'
      fullPath: '/$organizationId/$installationId/onboarding'
      preLoaderRoute: typeof orgInstallationOnboardingRouteImport
      parentRoute: typeof orgInstallationLayoutRoute
    }
    '/_auth.layout/$organizationId/$installationId/integrations/': {
      id: '/_auth.layout/$organizationId/$installationId/integrations/'
      path: '/integrations'
      fullPath: '/$organizationId/$installationId/integrations'
      preLoaderRoute: typeof orgInstallationIntegrationsIndexRouteImport
      parentRoute: typeof orgInstallationLayoutRoute
    }
    '/_auth.layout/$organizationId/$installationId/integrations/redirect': {
      id: '/_auth.layout/$organizationId/$installationId/integrations/redirect'
      path: '/integrations/redirect'
      fullPath: '/$organizationId/$installationId/integrations/redirect'
      preLoaderRoute: typeof orgInstallationIntegrationsRedirectRouteImport
      parentRoute: typeof orgInstallationLayoutRoute
    }
    '/_auth.layout/$organizationId/$installationId/integrations/mcp-params': {
      id: '/_auth.layout/$organizationId/$installationId/integrations/mcp-params'
      path: '/integrations/mcp-params'
      fullPath: '/$organizationId/$installationId/integrations/mcp-params'
      preLoaderRoute: typeof orgInstallationIntegrationsMcpParamsRouteImport
      parentRoute: typeof orgInstallationLayoutRoute
    }
    '/_auth.layout/$organizationId/$installationId/agents/offline': {
      id: '/_auth.layout/$organizationId/$installationId/agents/offline'
      path: '/agents/offline'
      fullPath: '/$organizationId/$installationId/agents/offline'
      preLoaderRoute: typeof offlineAgentDetailRouteImport
      parentRoute: typeof orgInstallationLayoutRoute
    }
    '/_auth.layout/$organizationId/$installationId/agents/$agentClassName/$durableObjectName': {
      id: '/_auth.layout/$organizationId/$installationId/agents/$agentClassName/$durableObjectName'
      path: '/agents/$agentClassName/$durableObjectName'
      fullPath: '/$organizationId/$installationId/agents/$agentClassName/$durableObjectName'
      preLoaderRoute: typeof onlineAgentDetailRouteImport
      parentRoute: typeof orgInstallationLayoutRoute
    }
  }
}

interface orgInstallationLayoutRouteChildren {
  orgInstallationOnboardingRoute: typeof orgInstallationOnboardingRoute
  orgInstallationRepoRoute: typeof orgInstallationRepoRoute
  orgInstallationIndexRoute: typeof orgInstallationIndexRoute
  offlineAgentDetailRoute: typeof offlineAgentDetailRoute
  orgInstallationIntegrationsMcpParamsRoute: typeof orgInstallationIntegrationsMcpParamsRoute
  orgInstallationIntegrationsRedirectRoute: typeof orgInstallationIntegrationsRedirectRoute
  orgInstallationIntegrationsIndexRoute: typeof orgInstallationIntegrationsIndexRoute
  onlineAgentDetailRoute: typeof onlineAgentDetailRoute
}

const orgInstallationLayoutRouteChildren: orgInstallationLayoutRouteChildren = {
  orgInstallationOnboardingRoute: orgInstallationOnboardingRoute,
  orgInstallationRepoRoute: orgInstallationRepoRoute,
  orgInstallationIndexRoute: orgInstallationIndexRoute,
  offlineAgentDetailRoute: offlineAgentDetailRoute,
  orgInstallationIntegrationsMcpParamsRoute:
    orgInstallationIntegrationsMcpParamsRoute,
  orgInstallationIntegrationsRedirectRoute:
    orgInstallationIntegrationsRedirectRoute,
  orgInstallationIntegrationsIndexRoute: orgInstallationIntegrationsIndexRoute,
  onlineAgentDetailRoute: onlineAgentDetailRoute,
}

const orgInstallationLayoutRouteWithChildren =
  orgInstallationLayoutRoute._addFileChildren(
    orgInstallationLayoutRouteChildren,
  )

interface orgLayoutRouteChildren {
  orgInstallationLayoutRoute: typeof orgInstallationLayoutRouteWithChildren
  orgSettingsRoute: typeof orgSettingsRoute
  orgTeamRoute: typeof orgTeamRoute
  orgIndexRoute: typeof orgIndexRoute
}

const orgLayoutRouteChildren: orgLayoutRouteChildren = {
  orgInstallationLayoutRoute: orgInstallationLayoutRouteWithChildren,
  orgSettingsRoute: orgSettingsRoute,
  orgTeamRoute: orgTeamRoute,
  orgIndexRoute: orgIndexRoute,
}

const orgLayoutRouteWithChildren = orgLayoutRoute._addFileChildren(
  orgLayoutRouteChildren,
)

interface adminLayoutRouteChildren {
  adminDbToolsRoute: typeof adminDbToolsRoute
  adminInstallationsRoute: typeof adminInstallationsRoute
  adminSessionInfoRoute: typeof adminSessionInfoRoute
  adminSlackNotificationRoute: typeof adminSlackNotificationRoute
  adminTrpcToolsRoute: typeof adminTrpcToolsRoute
  adminIndexRoute: typeof adminIndexRoute
}

const adminLayoutRouteChildren: adminLayoutRouteChildren = {
  adminDbToolsRoute: adminDbToolsRoute,
  adminInstallationsRoute: adminInstallationsRoute,
  adminSessionInfoRoute: adminSessionInfoRoute,
  adminSlackNotificationRoute: adminSlackNotificationRoute,
  adminTrpcToolsRoute: adminTrpcToolsRoute,
  adminIndexRoute: adminIndexRoute,
}

const adminLayoutRouteWithChildren = adminLayoutRoute._addFileChildren(
  adminLayoutRouteChildren,
)

interface authRequiredDotlayoutRouteChildren {
  indexRoute: typeof indexRoute
  orgLayoutRoute: typeof orgLayoutRouteWithChildren
  adminLayoutRoute: typeof adminLayoutRouteWithChildren
  newOrganizationRoute: typeof newOrganizationRoute
  userSettingsRoute: typeof userSettingsRoute
}

const authRequiredDotlayoutRouteChildren: authRequiredDotlayoutRouteChildren = {
  indexRoute: indexRoute,
  orgLayoutRoute: orgLayoutRouteWithChildren,
  adminLayoutRoute: adminLayoutRouteWithChildren,
  newOrganizationRoute: newOrganizationRoute,
  userSettingsRoute: userSettingsRoute,
}

const authRequiredDotlayoutRouteWithChildren =
  authRequiredDotlayoutRoute._addFileChildren(
    authRequiredDotlayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  authRequiredDotlayoutRoute: authRequiredDotlayoutRouteWithChildren,
  loginRoute: loginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
