/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThingsRouteImport } from './routes/things'
import { Route as ServerFnsRouteImport } from './routes/server-fns'
import { Route as CounterRouteImport } from './routes/counter'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ThingsRoute = ThingsRouteImport.update({
  id: '/things',
  path: '/things',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerFnsRoute = ServerFnsRouteImport.update({
  id: '/server-fns',
  path: '/server-fns',
  getParentRoute: () => rootRouteImport,
} as any)
const CounterRoute = CounterRouteImport.update({
  id: '/counter',
  path: '/counter',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/counter': typeof CounterRoute
  '/server-fns': typeof ServerFnsRoute
  '/things': typeof ThingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/counter': typeof CounterRoute
  '/server-fns': typeof ServerFnsRoute
  '/things': typeof ThingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/counter': typeof CounterRoute
  '/server-fns': typeof ServerFnsRoute
  '/things': typeof ThingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/counter' | '/server-fns' | '/things'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/counter' | '/server-fns' | '/things'
  id: '__root__' | '/' | '/about' | '/counter' | '/server-fns' | '/things'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CounterRoute: typeof CounterRoute
  ServerFnsRoute: typeof ServerFnsRoute
  ThingsRoute: typeof ThingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/things': {
      id: '/things'
      path: '/things'
      fullPath: '/things'
      preLoaderRoute: typeof ThingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-fns': {
      id: '/server-fns'
      path: '/server-fns'
      fullPath: '/server-fns'
      preLoaderRoute: typeof ServerFnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counter': {
      id: '/counter'
      path: '/counter'
      fullPath: '/counter'
      preLoaderRoute: typeof CounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CounterRoute: CounterRoute,
  ServerFnsRoute: ServerFnsRoute,
  ThingsRoute: ThingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
