// Generated by `sqlfu generate`. Do not edit.

export * from "./queries.sql.ts";

export const sqlfuQuerySources = [
  {
    sqlFile: "queries.sql",
    generatedFile: "queries.sql.ts",
    sourceSql:
      "/** @name selectResources */\nSELECT type, slug, data, lease_state, leased_until, last_acquired_at, last_released_at, created_at, updated_at\nFROM resources\nORDER BY type ASC, created_at ASC, slug ASC;\n\n/** @name selectResourcesByType */\nSELECT type, slug, data, lease_state, leased_until, last_acquired_at, last_released_at, created_at, updated_at\nFROM resources\nWHERE type = :type\nORDER BY created_at ASC, slug ASC;\n\n/** @name insertResourceRow */\nINSERT INTO resources (type, slug, data)\nVALUES (:type, :slug, :data);\n\n/** @name selectResourceByTypeAndSlug */\nSELECT type, slug, data, lease_state, leased_until, last_acquired_at, last_released_at, created_at, updated_at\nFROM resources\nWHERE type = :type AND slug = :slug;\n\n/** @name deleteResourceByTypeAndSlug */\nDELETE FROM resources\nWHERE type = :type AND slug = :slug;\n\n/** @name selectResourcePresenceByType */\nSELECT 1 AS present\nFROM resources\nWHERE type = :type\nLIMIT 1;\n\n/** @name updateResourceLeased */\nUPDATE resources\nSET lease_state = 'leased',\n  leased_until = :leasedUntil,\n  last_acquired_at = :lastAcquiredAt,\n  updated_at = strftime('%Y-%m-%d %H:%M:%S', 'now')\nWHERE type = :type AND slug = :slug;\n\n/** @name updateResourceAvailable */\nUPDATE resources\nSET lease_state = 'available',\n  leased_until = NULL,\n  last_released_at = COALESCE(:lastReleasedAt, last_released_at),\n  updated_at = strftime('%Y-%m-%d %H:%M:%S', 'now')\nWHERE type = :type AND slug = :slug;\n",
  },
];
