/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppDeploymentsIndexRouteImport } from './routes/_app/deployments/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as AppDeploymentsNewRouteImport } from './routes/_app/deployments/new'
import { Route as AppDeploymentsSlugRouteImport } from './routes/_app/deployments/$slug'
import { Route as AppDeploymentsSlugIndexRouteImport } from './routes/_app/deployments/$slug/index'
import { Route as AppDeploymentsSlugEventsRouteImport } from './routes/_app/deployments/$slug/events'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDeploymentsIndexRoute = AppDeploymentsIndexRouteImport.update({
  id: '/deployments/',
  path: '/deployments/',
  getParentRoute: () => AppRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDeploymentsNewRoute = AppDeploymentsNewRouteImport.update({
  id: '/deployments/new',
  path: '/deployments/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDeploymentsSlugRoute = AppDeploymentsSlugRouteImport.update({
  id: '/deployments/$slug',
  path: '/deployments/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppDeploymentsSlugIndexRoute = AppDeploymentsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDeploymentsSlugRoute,
} as any)
const AppDeploymentsSlugEventsRoute =
  AppDeploymentsSlugEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AppDeploymentsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/deployments/$slug': typeof AppDeploymentsSlugRouteWithChildren
  '/deployments/new': typeof AppDeploymentsNewRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/deployments/': typeof AppDeploymentsIndexRoute
  '/deployments/$slug/events': typeof AppDeploymentsSlugEventsRoute
  '/deployments/$slug/': typeof AppDeploymentsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/deployments/new': typeof AppDeploymentsNewRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/deployments': typeof AppDeploymentsIndexRoute
  '/deployments/$slug/events': typeof AppDeploymentsSlugEventsRoute
  '/deployments/$slug': typeof AppDeploymentsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/deployments/$slug': typeof AppDeploymentsSlugRouteWithChildren
  '/_app/deployments/new': typeof AppDeploymentsNewRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_app/deployments/': typeof AppDeploymentsIndexRoute
  '/_app/deployments/$slug/events': typeof AppDeploymentsSlugEventsRoute
  '/_app/deployments/$slug/': typeof AppDeploymentsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deployments/$slug'
    | '/deployments/new'
    | '/api/rpc/$'
    | '/deployments/'
    | '/deployments/$slug/events'
    | '/deployments/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deployments/new'
    | '/api/rpc/$'
    | '/deployments'
    | '/deployments/$slug/events'
    | '/deployments/$slug'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/deployments/$slug'
    | '/_app/deployments/new'
    | '/api/rpc/$'
    | '/_app/deployments/'
    | '/_app/deployments/$slug/events'
    | '/_app/deployments/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deployments/': {
      id: '/_app/deployments/'
      path: '/deployments'
      fullPath: '/deployments/'
      preLoaderRoute: typeof AppDeploymentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/deployments/new': {
      id: '/_app/deployments/new'
      path: '/deployments/new'
      fullPath: '/deployments/new'
      preLoaderRoute: typeof AppDeploymentsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deployments/$slug': {
      id: '/_app/deployments/$slug'
      path: '/deployments/$slug'
      fullPath: '/deployments/$slug'
      preLoaderRoute: typeof AppDeploymentsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deployments/$slug/': {
      id: '/_app/deployments/$slug/'
      path: '/'
      fullPath: '/deployments/$slug/'
      preLoaderRoute: typeof AppDeploymentsSlugIndexRouteImport
      parentRoute: typeof AppDeploymentsSlugRoute
    }
    '/_app/deployments/$slug/events': {
      id: '/_app/deployments/$slug/events'
      path: '/events'
      fullPath: '/deployments/$slug/events'
      preLoaderRoute: typeof AppDeploymentsSlugEventsRouteImport
      parentRoute: typeof AppDeploymentsSlugRoute
    }
  }
}

interface AppDeploymentsSlugRouteChildren {
  AppDeploymentsSlugEventsRoute: typeof AppDeploymentsSlugEventsRoute
  AppDeploymentsSlugIndexRoute: typeof AppDeploymentsSlugIndexRoute
}

const AppDeploymentsSlugRouteChildren: AppDeploymentsSlugRouteChildren = {
  AppDeploymentsSlugEventsRoute: AppDeploymentsSlugEventsRoute,
  AppDeploymentsSlugIndexRoute: AppDeploymentsSlugIndexRoute,
}

const AppDeploymentsSlugRouteWithChildren =
  AppDeploymentsSlugRoute._addFileChildren(AppDeploymentsSlugRouteChildren)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppDeploymentsSlugRoute: typeof AppDeploymentsSlugRouteWithChildren
  AppDeploymentsNewRoute: typeof AppDeploymentsNewRoute
  AppDeploymentsIndexRoute: typeof AppDeploymentsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppDeploymentsSlugRoute: AppDeploymentsSlugRouteWithChildren,
  AppDeploymentsNewRoute: AppDeploymentsNewRoute,
  AppDeploymentsIndexRoute: AppDeploymentsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
