import { defineConfig } from "tsdown";

export default defineConfig([
  {
    entry: { node: "src/node.ts" },
    format: "esm",
    fixedExtension: true,
    platform: "node",
    target: "node22",
    dts: false,
    sourcemap: true,
    clean: true,
  },
  {
    entry: {
      sdk: "src/sdk/index.ts",
      app: "src/app.ts",
      "app-server": "src/app-server.ts",
      "app-session": "src/app-session.ts",
      client: "src/client/live-state.ts",
      react: "src/client/react.tsx",
      api: "src/api.ts",
      lib: "src/lib.ts",
      expression: "src/expression.ts",
      principal: "src/principal.ts",
      "stream/processor": "src/stream/processor.ts",
      "stream/run": "src/stream/run.ts",
      "oauth-scopes": "src/oauth-scopes.ts",
      "project-ingress": "src/project-ingress.ts",
      oauth: "src/client/oauth.ts",
    },
    format: "esm",
    fixedExtension: true,
    platform: "neutral",
    target: "es2022",
    deps: { neverBundle: ["cloudflare:workers"] },
    dts: false,
    sourcemap: true,
    clean: false,
  },
]);
