import { defineConfig } from "tsdown";

export default defineConfig([
  {
    entry: { cli: "src/cli.ts", "next-node": "src/next-node.ts" },
    format: "esm",
    fixedExtension: true,
    platform: "node",
    target: "node22",
    dts: false,
    sourcemap: true,
    clean: true,
  },
  {
    entry: {
      "next/sdk": "src/next/sdk/index.ts",
      "next/app": "src/next/app.ts",
      "next/app-server": "src/next/app-server.ts",
      "next/app-session": "src/next/app-session.ts",
      "next/client": "src/next/client/live-state.ts",
      "next/react": "src/next/client/react.tsx",
      "next/api": "src/next/api.ts",
      "next/lib": "src/next/lib.ts",
      "next/expression": "src/next/expression.ts",
      "next/principal": "src/next/principal.ts",
      "next/stream/processor": "src/next/stream/processor.ts",
      "next/stream/run": "src/next/stream/run.ts",
      "next/oauth-scopes": "src/next/oauth-scopes.ts",
      "next/project-ingress": "src/next/project-ingress.ts",
      "next/oauth": "src/next/client/oauth.ts",
    },
    format: "esm",
    fixedExtension: true,
    platform: "neutral",
    target: "es2022",
    deps: { neverBundle: ["cloudflare:workers"] },
    dts: false,
    sourcemap: true,
    clean: false,
  },
]);
