receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:15317
      http:
        endpoint: 0.0.0.0:15318

processors:
  batch: {}

exporters:
  otlphttp/openobserve_traces:
    endpoint: http://127.0.0.1:5080/api/default
    traces_endpoint: http://127.0.0.1:5080/api/default/traces
    headers:
      Authorization: Basic cm9vdEBleGFtcGxlLmNvbTpDb21wbGV4cGFzcyMxMjM=

  otlphttp/openobserve_logs:
    endpoint: http://127.0.0.1:5080/api/default
    logs_endpoint: http://127.0.0.1:5080/api/default/v1/logs
    headers:
      Authorization: Basic cm9vdEBleGFtcGxlLmNvbTpDb21wbGV4cGFzcyMxMjM=
      stream-name: orpc_logs

  otlphttp/clickstack:
    endpoint: http://127.0.0.1:4318

extensions:
  health_check:
    endpoint: 0.0.0.0:15333

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/openobserve_traces, otlphttp/clickstack]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/openobserve_logs, otlphttp/clickstack]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/clickstack]
