// Generated by `sqlfu generate`. Do not edit.
// A bundle of every migration in db/migrations/,
// importable from runtimes without filesystem access (durable objects, edge workers, browsers).
// Use `migrate(client)` for the common path, or `migrations` for lower-level control.

import {applyMigrations, migrationsFromBundle, type AsyncClient, type Client, type SyncClient} from 'sqlfu';

export const migrations = {
  "db/migrations/0000_init.sql": "-- Use IF NOT EXISTS in this introductory migration only: existing Durable\n-- Object instances already created these tables via ResourceCoordinator's old\n-- initializeSql() helper. The IF NOT EXISTS lets fresh and previously-deployed\n-- DO instances both record this migration in sqlfu_migrations.\nCREATE TABLE IF NOT EXISTS leases (\n  slug TEXT PRIMARY KEY,\n  lease_id TEXT NOT NULL,\n  expires_at INTEGER NOT NULL,\n  created_at INTEGER NOT NULL\n);\n\nCREATE TABLE IF NOT EXISTS events (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  occurred_at INTEGER NOT NULL,\n  event TEXT NOT NULL,\n  slug TEXT,\n  payload TEXT NOT NULL CHECK (json_valid(payload))\n);\n\nCREATE TABLE IF NOT EXISTS metadata (\n  key TEXT PRIMARY KEY,\n  value TEXT NOT NULL\n);\n\nCREATE INDEX IF NOT EXISTS idx_leases_expires_at ON leases(expires_at);\n",
};

export function migrate(client: SyncClient): void;
export function migrate(client: AsyncClient): Promise<void>;
export function migrate(client: Client): void | Promise<void> {
  return applyMigrations(client, {
    migrations: migrationsFromBundle(migrations),
    preset: "sqlfu",
  });
}

export type MigrationBundle = typeof migrations;
