import { describe, expect, test } from "vitest";
import {
  assessVoicePeAecRun,
  parseKitRawCleanAecMetrics,
  selectSettledVoicePeFarEndSequences,
} from "./voice-pe-aec-assessment.ts";

function sample(overrides: Record<string, number | string> = {}) {
  const value = {
    schemaVersion: 4,
    topology: "raw-clean",
    sequence: 1,
    windowStartedAtMs: 1_000,
    producedAtMs: 2_000,
    sampleStride: 8,
    sampledSamples: 2_000,
    rawPeak: 12_000,
    cleanPeak: 2_000,
    rawMeanAbsolute: 1_200,
    cleanMeanAbsolute: 200,
    playbackContentSamples: 48_000,
    lifetimeCaptureFrames: 100,
    lifetimeCleanUplinkFrames: 95,
    lifetimeCleanUplinkDrops: 0,
    lifetimeCaptureFailures: 0,
    lifetimeSignalMeasurementFailures: 0,
    lastCaptureToUplinkUs: 200,
    maximumCaptureToUplinkUs: 500,
    lifetimePlaybackContentSamples: 96_000,
    lifetimePlaybackResets: 0,
    lifetimePlaybackFramesDiscardedByReset: 0,
    lifetimePlaybackWriteFailures: 0,
    lifetimePlaybackQueueOverflows: 0,
    lifetimePlaybackPolicyErrors: 0,
    lifetimePlaybackResetFailures: 0,
    lifetimePlaybackObservationFailures: 0,
    lifetimePlaybackUnderrunIncidents: 0,
    lifetimePlaybackUnderrunSilenceSamples: 0,
    lifetimePlaybackStaleFramesDiscarded: 0,
    lastPlaybackWriteUs: 8_000,
    maximumPlaybackWriteUs: 9_000,
    lastReceiveToRenderMs: 20,
    maximumReceiveToRenderMs: 30,
    ...overrides,
  };
  return {
    ...value,
    /*
     * Schema v2 exposed only a truncated integer mean. On HAVPE's quiet raw
     * XMOS tap, a difference of one integer changed the physical verdict by
     * several dB between otherwise clean runs. The firmware already owns the
     * exact accumulators, so schema v3 retains those sums and lets the host
     * combine windows without manufacturing precision after the fact.
     */
    rawAbsoluteSum:
      typeof overrides.rawAbsoluteSum === "number"
        ? overrides.rawAbsoluteSum
        : value.rawMeanAbsolute * value.sampledSamples,
    cleanAbsoluteSum:
      typeof overrides.cleanAbsoluteSum === "number"
        ? overrides.cleanAbsoluteSum
        : value.cleanMeanAbsolute * value.sampledSamples,
  };
}

describe("HAVPE raw/clean AEC evidence", () => {
  test("accepts a speaker-active suppressed window plus a preserved near-end window", () => {
    const farEnd = parseKitRawCleanAecMetrics(sample());
    const nearEnd = parseKitRawCleanAecMetrics(
      sample({
        sequence: 2,
        windowStartedAtMs: 2_000,
        producedAtMs: 3_000,
        rawPeak: 8_000,
        cleanPeak: 7_000,
        rawMeanAbsolute: 800,
        cleanMeanAbsolute: 720,
        playbackContentSamples: 0,
        lifetimeCaptureFrames: 150,
        lifetimeCleanUplinkFrames: 145,
      }),
    );

    const assessment = assessVoicePeAecRun([farEnd, nearEnd]);
    expect(assessment.passed).toBe(true);
    expect(assessment.farEnd.gainNormalizedEchoSuppressionDb).toBeGreaterThan(14);
    expect(assessment.nearEnd.processedToRawRatio).toBeCloseTo(0.9);
    expect(assessment.lifecycleDeltas.captureFrames).toBe(50);
  });

  test("rejects fabricated reference fields and a speaker window without suppression", () => {
    expect(() => parseKitRawCleanAecMetrics({ ...sample(), referencePeak: 123 })).toThrow(
      "referencePeak",
    );

    const assessment = assessVoicePeAecRun([
      parseKitRawCleanAecMetrics(sample({ cleanMeanAbsolute: 1_100, lifetimeCaptureFrames: 100 })),
      parseKitRawCleanAecMetrics(
        sample({
          sequence: 2,
          windowStartedAtMs: 2_000,
          producedAtMs: 3_000,
          playbackContentSamples: 0,
          lifetimeCaptureFrames: 150,
          lifetimeCleanUplinkFrames: 145,
        }),
      ),
    ]);
    expect(assessment.passed).toBe(false);
    expect(assessment.reasons.join(" ")).toContain("echo suppression");
  });

  /*
   * The August physical run sounded clean for one second and then developed
   * repeated holes while every codec write still succeeded. Those holes are
   * generated by the hardware clock when the downlink lane is empty, so a
   * write-only ledger falsely certified the run. Preserve the exact regression:
   * any response-active silence or freshness discard invalidates AEC evidence,
   * even when the amplitude windows themselves look healthy.
   */
  test("rejects speaker-clock underruns and stale downlink discards", () => {
    const assessment = assessVoicePeAecRun([
      parseKitRawCleanAecMetrics(sample()),
      parseKitRawCleanAecMetrics(
        sample({
          sequence: 2,
          windowStartedAtMs: 2_000,
          producedAtMs: 3_000,
          playbackContentSamples: 0,
          lifetimeCaptureFrames: 150,
          lifetimeCleanUplinkFrames: 145,
          lifetimePlaybackUnderrunIncidents: 2,
          lifetimePlaybackUnderrunSilenceSamples: 320,
          lifetimePlaybackStaleFramesDiscarded: 1,
        }),
      ),
    ]);

    expect(assessment.passed).toBe(false);
    expect(assessment.reasons.join(" ")).toContain("2 underrun");
    expect(assessment.reasons.join(" ")).toContain("320 silence samples");
    expect(assessment.reasons.join(" ")).toContain("1 stale");
  });

  /*
   * A production barge-in is supposed to purge the old voice from the physical
   * lane. Counting that commanded generation barrier as an unexplained reset
   * made the full-duplex test condemn the very interruption it requested. The
   * expected count is still exact: a missing reset means stale speech may have
   * escaped, while a surplus reset means playback changed generation without
   * an authorized semantic boundary.
   */
  test("classifies exactly one harness-requested playback reset", () => {
    const farEnd = parseKitRawCleanAecMetrics(sample());
    const nearEndWithReset = parseKitRawCleanAecMetrics(
      sample({
        sequence: 2,
        playbackContentSamples: 0,
        rawMeanAbsolute: 800,
        cleanMeanAbsolute: 720,
        lifetimeCaptureFrames: 150,
        lifetimeCleanUplinkFrames: 145,
        lifetimePlaybackResets: 1,
        lifetimePlaybackFramesDiscardedByReset: 14,
      }),
    );

    const expected = assessVoicePeAecRun([farEnd, nearEndWithReset], undefined, {
      expectedPlaybackResets: 1,
    });
    expect(expected.passed).toBe(true);

    const surplus = assessVoicePeAecRun(
      [
        farEnd,
        parseKitRawCleanAecMetrics(
          sample({
            ...nearEndWithReset,
            lifetimePlaybackResets: 2,
          }),
        ),
      ],
      undefined,
      { expectedPlaybackResets: 1 },
    );
    expect(surplus.passed).toBe(false);
    expect(surplus.reasons).toContain(
      "Playback reset 2 times during the run; expected exactly 1 harness-requested reset.",
    );
  });

  /*
   * A callback with playback content is not automatically a settled AEC
   * measurement. The first windows after a new voice begins include acoustic
   * onset and filter adaptation; using them made the score depend on callback
   * phase. The harness waits for a fixed warm-up count and then retains a fixed
   * evidence count, so the same physical interval has one deterministic
   * interpretation without selecting whichever window happens to look best.
   */
  test("selects fixed settled windows after fixed speaker-on warm-up", () => {
    const samples = [
      parseKitRawCleanAecMetrics(sample({ sequence: 10, playbackContentSamples: 0 })),
      parseKitRawCleanAecMetrics(sample({ sequence: 11 })),
      parseKitRawCleanAecMetrics(sample({ sequence: 12 })),
      parseKitRawCleanAecMetrics(sample({ sequence: 13 })),
      parseKitRawCleanAecMetrics(sample({ sequence: 14 })),
    ];

    expect(
      selectSettledVoicePeFarEndSequences(samples, {
        evidenceWindows: 2,
        minimumPlaybackContentSamples: 8_000,
        warmupWindows: 2,
      }),
    ).toEqual([13, 14]);
  });

  /*
   * HAVPE deliberately exposes XMOS's original microphone beside its public
   * AEC+IC+NS+AGC output. AGC therefore makes the processed energy larger than
   * raw energy even when the local pipeline suppresses far-end speech. The
   * first physical production run measured the literal pair below: treating
   * it as equal-gain raw/AEC made healthy, audible barge-in report -36.08 dB.
   * A valid assessment has to remove the independently observed near-end gain
   * before deciding whether the far-end path was selectively attenuated.
   */
  test("does not mistake the public AGC stage for amplified far-end echo", () => {
    const nearEnd = parseKitRawCleanAecMetrics(
      sample({
        sequence: 68,
        rawPeak: 396,
        cleanPeak: 30_726,
        rawMeanAbsolute: 49,
        cleanMeanAbsolute: 6_220,
        playbackContentSamples: 0,
        lifetimeCaptureFrames: 3_000,
        lifetimeCleanUplinkFrames: 2_900,
      }),
    );
    const farEnd = parseKitRawCleanAecMetrics(
      sample({
        sequence: 83,
        rawPeak: 1_005,
        cleanPeak: 30_502,
        rawMeanAbsolute: 102,
        cleanMeanAbsolute: 6_496,
        playbackContentSamples: 16_320,
        lifetimeCaptureFrames: 3_750,
        lifetimeCleanUplinkFrames: 3_650,
      }),
    );

    const assessment = assessVoicePeAecRun([nearEnd, farEnd]);
    expect(assessment.passed).toBe(true);
    expect(assessment.farEnd.gainNormalizedEchoSuppressionDb).toBeCloseTo(5.99, 1);
    expect(assessment.nearEnd.processedToRawRatio).toBeCloseTo(126.94, 1);
    expect(assessment.farEnd.processedToRawRatio).toBeCloseTo(63.69, 1);
  });

  /*
   * Gain normalization is not permission to wave through arbitrary amplified
   * output. If the processed path transfers far-end and near-end energy by the
   * same factor, it has shown no selective echo suppression and must still
   * block physical acceptance.
   */
  test("rejects equal near-end and far-end transfer after gain calibration", () => {
    const assessment = assessVoicePeAecRun([
      parseKitRawCleanAecMetrics(
        sample({
          sequence: 1,
          rawPeak: 800,
          cleanPeak: 25_600,
          rawMeanAbsolute: 100,
          cleanMeanAbsolute: 6_400,
          playbackContentSamples: 0,
        }),
      ),
      parseKitRawCleanAecMetrics(
        sample({
          sequence: 2,
          rawPeak: 1_000,
          cleanPeak: 30_000,
          rawMeanAbsolute: 120,
          cleanMeanAbsolute: 7_680,
          playbackContentSamples: 16_000,
          lifetimeCaptureFrames: 150,
          lifetimeCleanUplinkFrames: 145,
        }),
      ),
    ]);

    expect(assessment.passed).toBe(false);
    expect(assessment.farEnd.gainNormalizedEchoSuppressionDb).toBeCloseTo(0);
  });

  /*
   * This is the exact signal shape from the first network-valid HAVPE run at
   * the AGC tap. The device later transcribed its own spoken replacement reply
   * as another user turn, so describing this as "no speaker-active window"
   * loses the most important diagnosis. Playback accounting is the authority
   * for whether the speaker was active; a low original-mic peak is evidence to
   * retain, not permission to discard the interval. The unequal-gain ratio
   * then correctly shows that the public path preserved far-end residue almost
   * as strongly as near-end speech and must fail the suppression gate.
   */
  test("measures low-level speaker residue instead of erasing an echo-triggered window", () => {
    const assessment = assessVoicePeAecRun([
      parseKitRawCleanAecMetrics(
        sample({
          sequence: 43,
          rawPeak: 224,
          cleanPeak: 24_118,
          rawMeanAbsolute: 32,
          cleanMeanAbsolute: 3_143,
          playbackContentSamples: 16_320,
        }),
      ),
      parseKitRawCleanAecMetrics(
        sample({
          sequence: 47,
          rawPeak: 396,
          cleanPeak: 30_726,
          rawMeanAbsolute: 82,
          cleanMeanAbsolute: 8_497,
          playbackContentSamples: 0,
          lifetimeCaptureFrames: 150,
          lifetimeCleanUplinkFrames: 145,
        }),
      ),
    ]);

    expect(assessment.passed).toBe(false);
    expect(assessment.farEnd.observed).toBe(true);
    expect(assessment.farEnd.gainNormalizedEchoSuppressionDb).toBeCloseTo(0.46, 1);
    expect(assessment.reasons.join(" ")).toContain("echo suppression");
  });

  /*
   * A full-duplex proof contains three acoustically different intervals:
   * ordinary replies, a deliberately settled speaker-only story, and the
   * injected barge-in. Selecting the first maximum-playback window made the
   * score depend on callback phase; pooling every playback window incorrectly
   * treats deliberate double-talk as echo. The harness knows the exact
   * speaker-only phase, so the assessor must honor those sequences and combine
   * their exact sums while leaving the overlapping barge-in window out.
   */
  test("scores the explicitly marked speaker-only phase instead of double-talk", () => {
    const nearEnd = parseKitRawCleanAecMetrics(
      sample({
        sequence: 34,
        rawPeak: 362,
        /*
         * The 2026-08-02 physical fixed-gain run produced an original-mic
         * peak above the live-speech threshold while NS correctly reduced the
         * public-channel peak below 500. Requiring the processed signal to be
         * louder than the source circularly rejects the suppression pipeline
         * we are trying to measure. The raw XMOS tap is the authority for
         * whether near-end sound physically reached the microphones.
         */
        cleanPeak: 474,
        rawMeanAbsolute: 70,
        cleanMeanAbsolute: 64,
        playbackContentSamples: 0,
      }),
    );
    const settling = parseKitRawCleanAecMetrics(
      sample({
        sequence: 50,
        rawPeak: 126,
        cleanPeak: 50,
        rawMeanAbsolute: 10,
        cleanMeanAbsolute: 2,
        playbackContentSamples: 16_320,
      }),
    );
    const settled = parseKitRawCleanAecMetrics(
      sample({
        sequence: 51,
        rawPeak: 279,
        cleanPeak: 19,
        rawMeanAbsolute: 22,
        cleanMeanAbsolute: 1,
        playbackContentSamples: 16_320,
      }),
    );
    const deliberateDoubleTalk = parseKitRawCleanAecMetrics(
      sample({
        sequence: 52,
        rawPeak: 347,
        cleanPeak: 377,
        rawMeanAbsolute: 51,
        cleanMeanAbsolute: 51,
        playbackContentSamples: 16_320,
        lifetimeCaptureFrames: 150,
        lifetimeCleanUplinkFrames: 145,
      }),
    );

    const assessment = assessVoicePeAecRun([nearEnd, settling, settled, deliberateDoubleTalk], {
      farEndSequences: [50, 51],
      nearEndSequences: [34],
    });

    expect(assessment.passed).toBe(true);
    expect(assessment.farEnd.sequences).toEqual([50, 51]);
    expect(assessment.farEnd.gainNormalizedEchoSuppressionDb).toBeGreaterThan(15);
  });

  /*
   * HAVPE's original-microphone tap is deliberately low gain. The first
   * complete production waveform run measured quiet-room peaks of 4-5 and the
   * Mac near-end prompt at only 65-72, despite the provider recording proving
   * that the prompt was coherent and intelligible. An absolute peak of 300
   * therefore rejected a real near-end interval based on board gain, not on
   * signal-to-noise. The physical harness owns a separate ambient phase, so
   * qualify near speech relative to that run's exact ambient floor instead.
   * This is a stricter semantic test than lowering a device-specific constant:
   * a noisy room raises the required near-end energy, while a quiet board no
   * longer needs an arbitrary electrical amplitude.
   */
  test("qualifies low-gain HAVPE near speech against the measured ambient phase", () => {
    const ambient = parseKitRawCleanAecMetrics(
      sample({
        sequence: 22,
        rawPeak: 5,
        rawMeanAbsolute: 0,
        rawAbsoluteSum: 1_792,
        cleanMeanAbsolute: 0,
        cleanAbsoluteSum: 1_816,
        playbackContentSamples: 0,
      }),
    );
    const farEnd = parseKitRawCleanAecMetrics(
      sample({
        sequence: 40,
        rawPeak: 389,
        rawMeanAbsolute: 55,
        rawAbsoluteSum: 112_200,
        cleanPeak: 20,
        cleanMeanAbsolute: 4,
        cleanAbsoluteSum: 8_160,
        playbackContentSamples: 16_320,
      }),
    );
    const nearEnd = parseKitRawCleanAecMetrics(
      sample({
        sequence: 54,
        rawPeak: 66,
        rawMeanAbsolute: 15,
        rawAbsoluteSum: 32_437,
        cleanPeak: 66,
        cleanMeanAbsolute: 15,
        cleanAbsoluteSum: 31_432,
        playbackContentSamples: 0,
        lifetimeCaptureFrames: 150,
        lifetimeCleanUplinkFrames: 145,
      }),
    );

    const assessment = assessVoicePeAecRun([ambient, farEnd, nearEnd], {
      ambientSequences: [22],
      farEndSequences: [40],
      nearEndSequences: [54],
    });

    expect(assessment.passed).toBe(true);
    expect(assessment.ambient.observed).toBe(true);
    expect(assessment.ambient.rawPeak).toBe(5);
    expect(assessment.nearEnd.sequences).toEqual([54]);
    expect(assessment.nearEnd.minimumQualifiedRawPeak).toBe(20);
  });

  /*
   * Phase labels alone must not manufacture a near-end proof. A playback-quiet
   * sample indistinguishable from the measured ambient floor is silence, even
   * if it falls inside the wall-clock interval in which the harness invoked
   * `say`. This also excludes the pre-speech boundary window observed in the
   * retained production run.
   */
  test("rejects an explicitly marked near-end window that does not clear ambient", () => {
    const ambient = parseKitRawCleanAecMetrics(
      sample({
        sequence: 22,
        rawPeak: 5,
        rawAbsoluteSum: 1_800,
        playbackContentSamples: 0,
      }),
    );
    const farEnd = parseKitRawCleanAecMetrics(sample({ sequence: 40 }));
    const ambientLikeNearEnd = parseKitRawCleanAecMetrics(
      sample({
        sequence: 56,
        rawPeak: 5,
        rawAbsoluteSum: 2_110,
        playbackContentSamples: 0,
        lifetimeCaptureFrames: 150,
        lifetimeCleanUplinkFrames: 145,
      }),
    );

    const assessment = assessVoicePeAecRun([ambient, farEnd, ambientLikeNearEnd], {
      ambientSequences: [22],
      farEndSequences: [40],
      nearEndSequences: [56],
    });

    expect(assessment.passed).toBe(false);
    expect(assessment.reasons.join(" ")).toContain("ambient-referenced");
    expect(assessment.nearEnd.observed).toBe(false);
  });

  /*
   * AEC evidence is useful only if the realtime capture path stayed healthy.
   * This regression keeps a quiet-looking clean channel from hiding a dropped
   * frame or a failed signal measurement during exactly the acceptance run.
   */
  test("fails on capture loss, measurement failure, or excessive uplink delay", () => {
    const assessment = assessVoicePeAecRun([
      parseKitRawCleanAecMetrics(sample()),
      parseKitRawCleanAecMetrics(
        sample({
          sequence: 2,
          windowStartedAtMs: 2_000,
          producedAtMs: 3_000,
          playbackContentSamples: 0,
          lifetimeCaptureFrames: 150,
          lifetimeCleanUplinkFrames: 145,
          lifetimeCleanUplinkDrops: 1,
          lifetimeCaptureFailures: 1,
          lifetimeSignalMeasurementFailures: 1,
          maximumCaptureToUplinkUs: 100_001,
        }),
      ),
    ]);
    expect(assessment.passed).toBe(false);
    expect(assessment.lifecycleDeltas.cleanUplinkDrops).toBe(1);
    expect(assessment.lifecycleDeltas.captureFailures).toBe(1);
    expect(assessment.lifecycleDeltas.signalMeasurementFailures).toBe(1);
    expect(assessment.timing.maximumObservedCaptureToUplinkUs).toBe(100_001);
  });

  test("retains lifetime timing maxima instead of only the latest healthy sample", () => {
    /*
     * A codec or render stall can be over by the time the one-second metrics
     * callback reaches the harness. The firmware therefore exports both the
     * latest value and a lifetime high-water mark. Using the latest value here
     * made precisely the intermittent stalls this proof exists to find vanish
     * from its durable summary whenever the following write was healthy.
     */
    const assessment = assessVoicePeAecRun([
      parseKitRawCleanAecMetrics(sample()),
      parseKitRawCleanAecMetrics(
        sample({
          sequence: 2,
          windowStartedAtMs: 2_000,
          producedAtMs: 3_000,
          playbackContentSamples: 0,
          lifetimeCaptureFrames: 150,
          lifetimeCleanUplinkFrames: 145,
          lastPlaybackWriteUs: 200,
          maximumPlaybackWriteUs: 91_000,
          lastReceiveToRenderMs: 2,
          maximumReceiveToRenderMs: 417,
        }),
      ),
    ]);

    expect(assessment.timing.maximumObservedPlaybackWriteUs).toBe(91_000);
    expect(assessment.timing.maximumObservedReceiveToRenderMs).toBe(417);
  });
});
