// Generated by `sqlfu generate`. Do not edit.
// Row types for every table and view in your project's schema.

export type SecretsRow = {
  id: string;
  name: string;
  value: string;
  description: string | null;
  created_at: string;
  updated_at: string;
  project_slug: string;
};

export type SqlfuMigrationsRow = {
  name: string;
  checksum: string;
  applied_at: string;
};
