/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VirtualReproRouteImport } from './routes/virtual-repro'
import { Route as SplitStreamRouteImport } from './routes/split-stream'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StreamsIndexRouteImport } from './routes/streams/index'
import { Route as StreamsSplatRouteImport } from './routes/streams.$'

const VirtualReproRoute = VirtualReproRouteImport.update({
  id: '/virtual-repro',
  path: '/virtual-repro',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitStreamRoute = SplitStreamRouteImport.update({
  id: '/split-stream',
  path: '/split-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamsIndexRoute = StreamsIndexRouteImport.update({
  id: '/streams/',
  path: '/streams/',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamsSplatRoute = StreamsSplatRouteImport.update({
  id: '/streams/$',
  path: '/streams/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/split-stream': typeof SplitStreamRoute
  '/virtual-repro': typeof VirtualReproRoute
  '/streams/$': typeof StreamsSplatRoute
  '/streams/': typeof StreamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/split-stream': typeof SplitStreamRoute
  '/virtual-repro': typeof VirtualReproRoute
  '/streams/$': typeof StreamsSplatRoute
  '/streams': typeof StreamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/split-stream': typeof SplitStreamRoute
  '/virtual-repro': typeof VirtualReproRoute
  '/streams/$': typeof StreamsSplatRoute
  '/streams/': typeof StreamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/split-stream'
    | '/virtual-repro'
    | '/streams/$'
    | '/streams/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/split-stream' | '/virtual-repro' | '/streams/$' | '/streams'
  id:
    | '__root__'
    | '/'
    | '/split-stream'
    | '/virtual-repro'
    | '/streams/$'
    | '/streams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplitStreamRoute: typeof SplitStreamRoute
  VirtualReproRoute: typeof VirtualReproRoute
  StreamsSplatRoute: typeof StreamsSplatRoute
  StreamsIndexRoute: typeof StreamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/virtual-repro': {
      id: '/virtual-repro'
      path: '/virtual-repro'
      fullPath: '/virtual-repro'
      preLoaderRoute: typeof VirtualReproRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split-stream': {
      id: '/split-stream'
      path: '/split-stream'
      fullPath: '/split-stream'
      preLoaderRoute: typeof SplitStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streams/': {
      id: '/streams/'
      path: '/streams'
      fullPath: '/streams/'
      preLoaderRoute: typeof StreamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streams/$': {
      id: '/streams/$'
      path: '/streams/$'
      fullPath: '/streams/$'
      preLoaderRoute: typeof StreamsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplitStreamRoute: SplitStreamRoute,
  VirtualReproRoute: VirtualReproRoute,
  StreamsSplatRoute: StreamsSplatRoute,
  StreamsIndexRoute: StreamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
