/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PosthogProxySplatRouteImport } from './routes/posthog-proxy.$'
import { Route as ApiPtyRouteImport } from './routes/api.pty'
import { Route as ApiOrpcWsRouteImport } from './routes/api.orpc-ws'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AppThingsRouteImport } from './routes/_app/things'
import { Route as AppTerminalRouteImport } from './routes/_app/terminal'
import { Route as AppLogStreamRouteImport } from './routes/_app/log-stream'
import { Route as AppDebugRouteImport } from './routes/_app/debug'
import { Route as AppThingsIndexRouteImport } from './routes/_app/things.index'
import { Route as AppThingsThingIdRouteImport } from './routes/_app/things.$thingId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosthogProxySplatRoute = PosthogProxySplatRouteImport.update({
  id: '/posthog-proxy/$',
  path: '/posthog-proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPtyRoute = ApiPtyRouteImport.update({
  id: '/api/pty',
  path: '/api/pty',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrpcWsRoute = ApiOrpcWsRouteImport.update({
  id: '/api/orpc-ws',
  path: '/api/orpc-ws',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppThingsRoute = AppThingsRouteImport.update({
  id: '/things',
  path: '/things',
  getParentRoute: () => AppRoute,
} as any)
const AppTerminalRoute = AppTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => AppRoute,
} as any)
const AppLogStreamRoute = AppLogStreamRouteImport.update({
  id: '/log-stream',
  path: '/log-stream',
  getParentRoute: () => AppRoute,
} as any)
const AppDebugRoute = AppDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => AppRoute,
} as any)
const AppThingsIndexRoute = AppThingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppThingsRoute,
} as any)
const AppThingsThingIdRoute = AppThingsThingIdRouteImport.update({
  id: '/$thingId',
  path: '/$thingId',
  getParentRoute: () => AppThingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debug': typeof AppDebugRoute
  '/log-stream': typeof AppLogStreamRoute
  '/terminal': typeof AppTerminalRoute
  '/things': typeof AppThingsRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/api/orpc-ws': typeof ApiOrpcWsRoute
  '/api/pty': typeof ApiPtyRoute
  '/posthog-proxy/$': typeof PosthogProxySplatRoute
  '/things/$thingId': typeof AppThingsThingIdRoute
  '/things/': typeof AppThingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debug': typeof AppDebugRoute
  '/log-stream': typeof AppLogStreamRoute
  '/terminal': typeof AppTerminalRoute
  '/api/$': typeof ApiSplatRoute
  '/api/orpc-ws': typeof ApiOrpcWsRoute
  '/api/pty': typeof ApiPtyRoute
  '/posthog-proxy/$': typeof PosthogProxySplatRoute
  '/things/$thingId': typeof AppThingsThingIdRoute
  '/things': typeof AppThingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/debug': typeof AppDebugRoute
  '/_app/log-stream': typeof AppLogStreamRoute
  '/_app/terminal': typeof AppTerminalRoute
  '/_app/things': typeof AppThingsRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/api/orpc-ws': typeof ApiOrpcWsRoute
  '/api/pty': typeof ApiPtyRoute
  '/posthog-proxy/$': typeof PosthogProxySplatRoute
  '/_app/things/$thingId': typeof AppThingsThingIdRoute
  '/_app/things/': typeof AppThingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debug'
    | '/log-stream'
    | '/terminal'
    | '/things'
    | '/api/$'
    | '/api/orpc-ws'
    | '/api/pty'
    | '/posthog-proxy/$'
    | '/things/$thingId'
    | '/things/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debug'
    | '/log-stream'
    | '/terminal'
    | '/api/$'
    | '/api/orpc-ws'
    | '/api/pty'
    | '/posthog-proxy/$'
    | '/things/$thingId'
    | '/things'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/debug'
    | '/_app/log-stream'
    | '/_app/terminal'
    | '/_app/things'
    | '/api/$'
    | '/api/orpc-ws'
    | '/api/pty'
    | '/posthog-proxy/$'
    | '/_app/things/$thingId'
    | '/_app/things/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiOrpcWsRoute: typeof ApiOrpcWsRoute
  ApiPtyRoute: typeof ApiPtyRoute
  PosthogProxySplatRoute: typeof PosthogProxySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posthog-proxy/$': {
      id: '/posthog-proxy/$'
      path: '/posthog-proxy/$'
      fullPath: '/posthog-proxy/$'
      preLoaderRoute: typeof PosthogProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pty': {
      id: '/api/pty'
      path: '/api/pty'
      fullPath: '/api/pty'
      preLoaderRoute: typeof ApiPtyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orpc-ws': {
      id: '/api/orpc-ws'
      path: '/api/orpc-ws'
      fullPath: '/api/orpc-ws'
      preLoaderRoute: typeof ApiOrpcWsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/things': {
      id: '/_app/things'
      path: '/things'
      fullPath: '/things'
      preLoaderRoute: typeof AppThingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terminal': {
      id: '/_app/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof AppTerminalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/log-stream': {
      id: '/_app/log-stream'
      path: '/log-stream'
      fullPath: '/log-stream'
      preLoaderRoute: typeof AppLogStreamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/debug': {
      id: '/_app/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof AppDebugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/things/': {
      id: '/_app/things/'
      path: '/'
      fullPath: '/things/'
      preLoaderRoute: typeof AppThingsIndexRouteImport
      parentRoute: typeof AppThingsRoute
    }
    '/_app/things/$thingId': {
      id: '/_app/things/$thingId'
      path: '/$thingId'
      fullPath: '/things/$thingId'
      preLoaderRoute: typeof AppThingsThingIdRouteImport
      parentRoute: typeof AppThingsRoute
    }
  }
}

interface AppThingsRouteChildren {
  AppThingsThingIdRoute: typeof AppThingsThingIdRoute
  AppThingsIndexRoute: typeof AppThingsIndexRoute
}

const AppThingsRouteChildren: AppThingsRouteChildren = {
  AppThingsThingIdRoute: AppThingsThingIdRoute,
  AppThingsIndexRoute: AppThingsIndexRoute,
}

const AppThingsRouteWithChildren = AppThingsRoute._addFileChildren(
  AppThingsRouteChildren,
)

interface AppRouteChildren {
  AppDebugRoute: typeof AppDebugRoute
  AppLogStreamRoute: typeof AppLogStreamRoute
  AppTerminalRoute: typeof AppTerminalRoute
  AppThingsRoute: typeof AppThingsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDebugRoute: AppDebugRoute,
  AppLogStreamRoute: AppLogStreamRoute,
  AppTerminalRoute: AppTerminalRoute,
  AppThingsRoute: AppThingsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiOrpcWsRoute: ApiOrpcWsRoute,
  ApiPtyRoute: ApiPtyRoute,
  PosthogProxySplatRoute: PosthogProxySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
