// Generated by `sqlfu generate`. Do not edit.
// A bundle of every migration in db/migrations/,
// importable from runtimes without filesystem access (durable objects, edge workers, browsers).
// Use `migrate(client)` for the common path, or `migrations` for lower-level control.

import {applyMigrations, migrationsFromBundle, type AsyncClient, type Client, type SyncClient} from 'sqlfu';

export const migrations = {
  "db/migrations/0000_init.sql": "-- Use IF NOT EXISTS in this introductory migration only: existing Durable\n-- Object instances already created these tables via the old ensureSchema()\n-- helper, before sqlfu took over migrations. The IF NOT EXISTS lets a fresh\n-- DO and a previously-deployed DO both end up with a consistent\n-- sqlfu_migrations row after the first call to migrate(client). Future\n-- migrations should use plain DDL.\ncreate table if not exists events (\n  offset integer primary key,\n  type text not null,\n  payload text not null check (json_valid(payload)),\n  metadata text check (metadata is null or (json_valid(metadata) and json_type(metadata) = 'object')),\n  idempotency_key text unique,\n  created_at text not null\n);\n\ncreate table if not exists reduced_state (\n  singleton integer primary key check (singleton = 1),\n  json text not null check (json_valid(json))\n);\n",
};

export function migrate(client: SyncClient): void;
export function migrate(client: AsyncClient): Promise<void>;
export function migrate(client: Client): void | Promise<void> {
  return applyMigrations(client, {
    migrations: migrationsFromBundle(migrations),
    preset: "sqlfu",
  });
}

export type MigrationBundle = typeof migrations;
