/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root.tsx";
import { Route as LoginRouteImport } from "./routes/login.tsx";
import { Route as AuthorizeRouteImport } from "./routes/authorize.tsx";
import { Route as AuthRouteImport } from "./routes/_auth.tsx";
import { Route as AuthIndexRouteImport } from "./routes/_auth/index.tsx";
import { Route as AuthSessionsRouteImport } from "./routes/_auth/sessions.tsx";
import { Route as AuthAccountRouteImport } from "./routes/_auth/account.tsx";

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthorizeRoute = AuthorizeRouteImport.update({
  id: "/authorize",
  path: "/authorize",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthRoute,
} as any);
const AuthSessionsRoute = AuthSessionsRouteImport.update({
  id: "/sessions",
  path: "/sessions",
  getParentRoute: () => AuthRoute,
} as any);
const AuthAccountRoute = AuthAccountRouteImport.update({
  id: "/account",
  path: "/account",
  getParentRoute: () => AuthRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof AuthIndexRoute;
  "/authorize": typeof AuthorizeRoute;
  "/login": typeof LoginRoute;
  "/account": typeof AuthAccountRoute;
  "/sessions": typeof AuthSessionsRoute;
}
export interface FileRoutesByTo {
  "/authorize": typeof AuthorizeRoute;
  "/login": typeof LoginRoute;
  "/account": typeof AuthAccountRoute;
  "/sessions": typeof AuthSessionsRoute;
  "/": typeof AuthIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_auth": typeof AuthRouteWithChildren;
  "/authorize": typeof AuthorizeRoute;
  "/login": typeof LoginRoute;
  "/_auth/account": typeof AuthAccountRoute;
  "/_auth/sessions": typeof AuthSessionsRoute;
  "/_auth/": typeof AuthIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/authorize" | "/login" | "/account" | "/sessions";
  fileRoutesByTo: FileRoutesByTo;
  to: "/authorize" | "/login" | "/account" | "/sessions" | "/";
  id:
    | "__root__"
    | "/_auth"
    | "/authorize"
    | "/login"
    | "/_auth/account"
    | "/_auth/sessions"
    | "/_auth/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren;
  AuthorizeRoute: typeof AuthorizeRoute;
  LoginRoute: typeof LoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/authorize": {
      id: "/authorize";
      path: "/authorize";
      fullPath: "/authorize";
      preLoaderRoute: typeof AuthorizeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth/": {
      id: "/_auth/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AuthIndexRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/sessions": {
      id: "/_auth/sessions";
      path: "/sessions";
      fullPath: "/sessions";
      preLoaderRoute: typeof AuthSessionsRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/account": {
      id: "/_auth/account";
      path: "/account";
      fullPath: "/account";
      preLoaderRoute: typeof AuthAccountRouteImport;
      parentRoute: typeof AuthRoute;
    };
  }
}

interface AuthRouteChildren {
  AuthAccountRoute: typeof AuthAccountRoute;
  AuthSessionsRoute: typeof AuthSessionsRoute;
  AuthIndexRoute: typeof AuthIndexRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAccountRoute: AuthAccountRoute,
  AuthSessionsRoute: AuthSessionsRoute,
  AuthIndexRoute: AuthIndexRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthorizeRoute: AuthorizeRoute,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
