/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root.tsx";
import { Route as LoginRouteImport } from "./routes/login.tsx";
import { Route as AuthRouteImport } from "./routes/_auth.tsx";
import { Route as AuthIndexRouteImport } from "./routes/_auth/index.tsx";
import { Route as AuthAuthorizeRouteImport } from "./routes/_auth/authorize.tsx";

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthRoute,
} as any);
const AuthAuthorizeRoute = AuthAuthorizeRouteImport.update({
  id: "/authorize",
  path: "/authorize",
  getParentRoute: () => AuthRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof AuthIndexRoute;
  "/login": typeof LoginRoute;
  "/authorize": typeof AuthAuthorizeRoute;
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute;
  "/authorize": typeof AuthAuthorizeRoute;
  "/": typeof AuthIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_auth": typeof AuthRouteWithChildren;
  "/login": typeof LoginRoute;
  "/_auth/authorize": typeof AuthAuthorizeRoute;
  "/_auth/": typeof AuthIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/login" | "/authorize";
  fileRoutesByTo: FileRoutesByTo;
  to: "/login" | "/authorize" | "/";
  id: "__root__" | "/_auth" | "/login" | "/_auth/authorize" | "/_auth/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth/": {
      id: "/_auth/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AuthIndexRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/authorize": {
      id: "/_auth/authorize";
      path: "/authorize";
      fullPath: "/authorize";
      preLoaderRoute: typeof AuthAuthorizeRouteImport;
      parentRoute: typeof AuthRoute;
    };
  }
}

interface AuthRouteChildren {
  AuthAuthorizeRoute: typeof AuthAuthorizeRoute;
  AuthIndexRoute: typeof AuthIndexRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthorizeRoute: AuthAuthorizeRoute,
  AuthIndexRoute: AuthIndexRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
