#!/usr/bin/env python3
"""Bake name=file WAV pairs from WORK into static 16 kHz mono PCM16LE sounds.

Sources are the Apache-2.0 Home Assistant Voice PE press chime and OpenAI
marin announcements. tools/generate-sounds.sh supplies each board's measured
wake trim and gain. Names starting with mode_ also populate mode_sounds.
"""
import argparse
from fractions import Fraction
import pathlib
import struct


def pcm_of(path):
    """Read the PCM data chunk from a pipeline-normalized WAV file."""
    raw = path.read_bytes()
    offset = 12
    while offset + 8 <= len(raw):
        cid = raw[offset:offset+4]
        size = struct.unpack("<I", raw[offset+4:offset+8])[0]
        if cid == b"data":
            return raw[offset+8:offset+8+size]
        offset += 8 + size + (size % 2)
    raise SystemExit(f"no data chunk in {path}")


def trim_wake(pcm):
    """Keep the 0.4 s audible body and fade its last 40 ms, as bench-proven."""
    samples = list(struct.unpack("<%dh" % (len(pcm) // 2), pcm))
    samples = samples[:6400]
    for i in range(640):
        j = len(samples) - 640 + i
        samples[j] = samples[j] * (640 - 1 - i) // 640
    return struct.pack("<%dh" % len(samples), *samples)


def apply_gain(pcm, gain):
    """Scale with signed floor division and saturate before packing PCM16."""
    samples = struct.unpack("<%dh" % (len(pcm) // 2), pcm)
    scaled = []
    for sample in samples:
        boosted = sample * gain.numerator // gain.denominator
        scaled.append(max(-32768, min(32767, boosted)))
    return struct.pack("<%dh" % len(scaled), *scaled)


def main():
    """Write the C include to stdout in the supplied sound order."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("work", type=pathlib.Path)
    parser.add_argument("sounds", nargs="+", metavar="name=file")
    parser.add_argument("--trim-wake", action="store_true")
    parser.add_argument("--gain", type=Fraction, default=Fraction(1))
    args = parser.parse_args()
    names = [pair.split("=", 1) for pair in args.sounds]
    print("/* GENERATED by make-sounds.py — do not edit. 16 kHz mono PCM16LE. */")
    for cname, fname in names:
        pcm = pcm_of(args.work / fname)
        if args.trim_wake and cname == "chime_press":
            pcm = trim_wake(pcm)
        if args.gain != 1:
            pcm = apply_gain(pcm, args.gain)
        print(f"static const uint8_t sound_{cname}[] = {{")
        for i in range(0, len(pcm), 24):
            print("  " + ",".join(str(b) for b in pcm[i:i+24]) + ",")
        print("};")
    modes = [cname for cname, _ in names if cname.startswith("mode_")]
    if modes:
        print("struct sound { const uint8_t *pcm; uint32_t bytes; };")
        print(f"static const struct sound mode_sounds[{len(modes)}] = {{")
        for cname in modes:
            print(f"  {{ sound_{cname}, sizeof(sound_{cname}) }},")
        print("};")


if __name__ == "__main__":
    main()
