/**
 * Reads drizzle-kit's generated migrations and bundles them into a single .ts
 * file with SQL inlined as strings. This is needed because the LOADER dynamic
 * worker can't import .sql files as text modules.
 *
 * Run after `npx drizzle-kit generate`:
 *   npx drizzle-kit generate && npx tsx scripts/bundle-migrations.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const root = join(__dirname, "..");
const journal = JSON.parse(readFileSync(join(root, "drizzle/meta/_journal.json"), "utf8"));

const migrations: Record<string, string> = {};
for (const entry of journal.entries) {
  const key = `m${String(entry.idx).padStart(4, "0")}`;
  const sql = readFileSync(join(root, `drizzle/${entry.tag}.sql`), "utf8");
  migrations[key] = sql;
}

const output = `// Auto-generated by scripts/bundle-migrations.ts — do not edit
// Run: npx drizzle-kit generate && npx tsx scripts/bundle-migrations.ts
export default ${JSON.stringify({ journal, migrations }, null, 2)} as const;
`;

writeFileSync(join(root, "src/db/migrations.ts"), output);
console.log(`Bundled ${Object.keys(migrations).length} migration(s) → src/db/migrations.ts`);
