/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ProcessorSlugRouteImport } from './routes/$processorSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProcessorSlugIndexRouteImport } from './routes/$processorSlug.index'
import { Route as PosthogProxySplatRouteImport } from './routes/posthog-proxy.$'
import { Route as ApiOrpcWsRouteImport } from './routes/api.orpc-ws'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AppStreamsRouteImport } from './routes/_app/streams'
import { Route as AppSecretsRouteImport } from './routes/_app/secrets'
import { Route as ProcessorSlugEventSlugRouteImport } from './routes/$processorSlug.$eventSlug'
import { Route as AppStreamsIndexRouteImport } from './routes/_app/streams.index'
import { Route as AppSecretsIndexRouteImport } from './routes/_app/secrets.index'
import { Route as ApiOrpcSplatRouteImport } from './routes/api.orpc.$'
import { Route as AppStreamsSplatRouteImport } from './routes/_app/streams.$'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessorSlugRoute = ProcessorSlugRouteImport.update({
  id: '/$processorSlug',
  path: '/$processorSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessorSlugIndexRoute = ProcessorSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProcessorSlugRoute,
} as any)
const PosthogProxySplatRoute = PosthogProxySplatRouteImport.update({
  id: '/posthog-proxy/$',
  path: '/posthog-proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrpcWsRoute = ApiOrpcWsRouteImport.update({
  id: '/api/orpc-ws',
  path: '/api/orpc-ws',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStreamsRoute = AppStreamsRouteImport.update({
  id: '/streams',
  path: '/streams',
  getParentRoute: () => AppRoute,
} as any)
const AppSecretsRoute = AppSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => AppRoute,
} as any)
const ProcessorSlugEventSlugRoute = ProcessorSlugEventSlugRouteImport.update({
  id: '/$eventSlug',
  path: '/$eventSlug',
  getParentRoute: () => ProcessorSlugRoute,
} as any)
const AppStreamsIndexRoute = AppStreamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppStreamsRoute,
} as any)
const AppSecretsIndexRoute = AppSecretsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSecretsRoute,
} as any)
const ApiOrpcSplatRoute = ApiOrpcSplatRouteImport.update({
  id: '/api/orpc/$',
  path: '/api/orpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStreamsSplatRoute = AppStreamsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppStreamsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$processorSlug': typeof ProcessorSlugRouteWithChildren
  '/docs': typeof DocsRoute
  '/$processorSlug/$eventSlug': typeof ProcessorSlugEventSlugRoute
  '/secrets': typeof AppSecretsRouteWithChildren
  '/streams': typeof AppStreamsRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/api/orpc-ws': typeof ApiOrpcWsRoute
  '/posthog-proxy/$': typeof PosthogProxySplatRoute
  '/$processorSlug/': typeof ProcessorSlugIndexRoute
  '/streams/$': typeof AppStreamsSplatRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/secrets/': typeof AppSecretsIndexRoute
  '/streams/': typeof AppStreamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/$processorSlug/$eventSlug': typeof ProcessorSlugEventSlugRoute
  '/api/$': typeof ApiSplatRoute
  '/api/orpc-ws': typeof ApiOrpcWsRoute
  '/posthog-proxy/$': typeof PosthogProxySplatRoute
  '/$processorSlug': typeof ProcessorSlugIndexRoute
  '/streams/$': typeof AppStreamsSplatRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/secrets': typeof AppSecretsIndexRoute
  '/streams': typeof AppStreamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$processorSlug': typeof ProcessorSlugRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/docs': typeof DocsRoute
  '/$processorSlug/$eventSlug': typeof ProcessorSlugEventSlugRoute
  '/_app/secrets': typeof AppSecretsRouteWithChildren
  '/_app/streams': typeof AppStreamsRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/api/orpc-ws': typeof ApiOrpcWsRoute
  '/posthog-proxy/$': typeof PosthogProxySplatRoute
  '/$processorSlug/': typeof ProcessorSlugIndexRoute
  '/_app/streams/$': typeof AppStreamsSplatRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/_app/secrets/': typeof AppSecretsIndexRoute
  '/_app/streams/': typeof AppStreamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$processorSlug'
    | '/docs'
    | '/$processorSlug/$eventSlug'
    | '/secrets'
    | '/streams'
    | '/api/$'
    | '/api/orpc-ws'
    | '/posthog-proxy/$'
    | '/$processorSlug/'
    | '/streams/$'
    | '/api/orpc/$'
    | '/secrets/'
    | '/streams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/$processorSlug/$eventSlug'
    | '/api/$'
    | '/api/orpc-ws'
    | '/posthog-proxy/$'
    | '/$processorSlug'
    | '/streams/$'
    | '/api/orpc/$'
    | '/secrets'
    | '/streams'
  id:
    | '__root__'
    | '/'
    | '/$processorSlug'
    | '/_app'
    | '/docs'
    | '/$processorSlug/$eventSlug'
    | '/_app/secrets'
    | '/_app/streams'
    | '/api/$'
    | '/api/orpc-ws'
    | '/posthog-proxy/$'
    | '/$processorSlug/'
    | '/_app/streams/$'
    | '/api/orpc/$'
    | '/_app/secrets/'
    | '/_app/streams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProcessorSlugRoute: typeof ProcessorSlugRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  DocsRoute: typeof DocsRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiOrpcWsRoute: typeof ApiOrpcWsRoute
  PosthogProxySplatRoute: typeof PosthogProxySplatRoute
  ApiOrpcSplatRoute: typeof ApiOrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$processorSlug': {
      id: '/$processorSlug'
      path: '/$processorSlug'
      fullPath: '/$processorSlug'
      preLoaderRoute: typeof ProcessorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$processorSlug/': {
      id: '/$processorSlug/'
      path: '/'
      fullPath: '/$processorSlug/'
      preLoaderRoute: typeof ProcessorSlugIndexRouteImport
      parentRoute: typeof ProcessorSlugRoute
    }
    '/posthog-proxy/$': {
      id: '/posthog-proxy/$'
      path: '/posthog-proxy/$'
      fullPath: '/posthog-proxy/$'
      preLoaderRoute: typeof PosthogProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orpc-ws': {
      id: '/api/orpc-ws'
      path: '/api/orpc-ws'
      fullPath: '/api/orpc-ws'
      preLoaderRoute: typeof ApiOrpcWsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/streams': {
      id: '/_app/streams'
      path: '/streams'
      fullPath: '/streams'
      preLoaderRoute: typeof AppStreamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/secrets': {
      id: '/_app/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof AppSecretsRouteImport
      parentRoute: typeof AppRoute
    }
    '/$processorSlug/$eventSlug': {
      id: '/$processorSlug/$eventSlug'
      path: '/$eventSlug'
      fullPath: '/$processorSlug/$eventSlug'
      preLoaderRoute: typeof ProcessorSlugEventSlugRouteImport
      parentRoute: typeof ProcessorSlugRoute
    }
    '/_app/streams/': {
      id: '/_app/streams/'
      path: '/'
      fullPath: '/streams/'
      preLoaderRoute: typeof AppStreamsIndexRouteImport
      parentRoute: typeof AppStreamsRoute
    }
    '/_app/secrets/': {
      id: '/_app/secrets/'
      path: '/'
      fullPath: '/secrets/'
      preLoaderRoute: typeof AppSecretsIndexRouteImport
      parentRoute: typeof AppSecretsRoute
    }
    '/api/orpc/$': {
      id: '/api/orpc/$'
      path: '/api/orpc/$'
      fullPath: '/api/orpc/$'
      preLoaderRoute: typeof ApiOrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/streams/$': {
      id: '/_app/streams/$'
      path: '/$'
      fullPath: '/streams/$'
      preLoaderRoute: typeof AppStreamsSplatRouteImport
      parentRoute: typeof AppStreamsRoute
    }
  }
}

interface ProcessorSlugRouteChildren {
  ProcessorSlugEventSlugRoute: typeof ProcessorSlugEventSlugRoute
  ProcessorSlugIndexRoute: typeof ProcessorSlugIndexRoute
}

const ProcessorSlugRouteChildren: ProcessorSlugRouteChildren = {
  ProcessorSlugEventSlugRoute: ProcessorSlugEventSlugRoute,
  ProcessorSlugIndexRoute: ProcessorSlugIndexRoute,
}

const ProcessorSlugRouteWithChildren = ProcessorSlugRoute._addFileChildren(
  ProcessorSlugRouteChildren,
)

interface AppSecretsRouteChildren {
  AppSecretsIndexRoute: typeof AppSecretsIndexRoute
}

const AppSecretsRouteChildren: AppSecretsRouteChildren = {
  AppSecretsIndexRoute: AppSecretsIndexRoute,
}

const AppSecretsRouteWithChildren = AppSecretsRoute._addFileChildren(
  AppSecretsRouteChildren,
)

interface AppStreamsRouteChildren {
  AppStreamsSplatRoute: typeof AppStreamsSplatRoute
  AppStreamsIndexRoute: typeof AppStreamsIndexRoute
}

const AppStreamsRouteChildren: AppStreamsRouteChildren = {
  AppStreamsSplatRoute: AppStreamsSplatRoute,
  AppStreamsIndexRoute: AppStreamsIndexRoute,
}

const AppStreamsRouteWithChildren = AppStreamsRoute._addFileChildren(
  AppStreamsRouteChildren,
)

interface AppRouteChildren {
  AppSecretsRoute: typeof AppSecretsRouteWithChildren
  AppStreamsRoute: typeof AppStreamsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppSecretsRoute: AppSecretsRouteWithChildren,
  AppStreamsRoute: AppStreamsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProcessorSlugRoute: ProcessorSlugRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  DocsRoute: DocsRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiOrpcWsRoute: ApiOrpcWsRoute,
  PosthogProxySplatRoute: PosthogProxySplatRoute,
  ApiOrpcSplatRoute: ApiOrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
