/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root.tsx";
import { Route as LoginRouteImport } from "./routes/login.tsx";
import { Route as AuthRouteImport } from "./routes/_auth.tsx";
import { Route as AuthIndexRouteImport } from "./routes/_auth/index.tsx";
import { Route as AuthSuperadminRouteImport } from "./routes/_auth/superadmin.tsx";
import { Route as AuthConsentRouteImport } from "./routes/_auth/consent.tsx";
import { Route as AuthSuperadminClientsRouteImport } from "./routes/_auth/superadmin/clients.tsx";

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthRoute,
} as any);
const AuthSuperadminRoute = AuthSuperadminRouteImport.update({
  id: "/superadmin",
  path: "/superadmin",
  getParentRoute: () => AuthRoute,
} as any);
const AuthConsentRoute = AuthConsentRouteImport.update({
  id: "/consent",
  path: "/consent",
  getParentRoute: () => AuthRoute,
} as any);
const AuthSuperadminClientsRoute = AuthSuperadminClientsRouteImport.update({
  id: "/clients",
  path: "/clients",
  getParentRoute: () => AuthSuperadminRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof AuthIndexRoute;
  "/login": typeof LoginRoute;
  "/consent": typeof AuthConsentRoute;
  "/superadmin": typeof AuthSuperadminRouteWithChildren;
  "/superadmin/clients": typeof AuthSuperadminClientsRoute;
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute;
  "/consent": typeof AuthConsentRoute;
  "/superadmin": typeof AuthSuperadminRouteWithChildren;
  "/": typeof AuthIndexRoute;
  "/superadmin/clients": typeof AuthSuperadminClientsRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_auth": typeof AuthRouteWithChildren;
  "/login": typeof LoginRoute;
  "/_auth/consent": typeof AuthConsentRoute;
  "/_auth/superadmin": typeof AuthSuperadminRouteWithChildren;
  "/_auth/": typeof AuthIndexRoute;
  "/_auth/superadmin/clients": typeof AuthSuperadminClientsRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/consent"
    | "/superadmin"
    | "/superadmin/clients";
  fileRoutesByTo: FileRoutesByTo;
  to: "/login" | "/consent" | "/superadmin" | "/" | "/superadmin/clients";
  id:
    | "__root__"
    | "/_auth"
    | "/login"
    | "/_auth/consent"
    | "/_auth/superadmin"
    | "/_auth/"
    | "/_auth/superadmin/clients";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth/": {
      id: "/_auth/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AuthIndexRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/superadmin": {
      id: "/_auth/superadmin";
      path: "/superadmin";
      fullPath: "/superadmin";
      preLoaderRoute: typeof AuthSuperadminRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/consent": {
      id: "/_auth/consent";
      path: "/consent";
      fullPath: "/consent";
      preLoaderRoute: typeof AuthConsentRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/superadmin/clients": {
      id: "/_auth/superadmin/clients";
      path: "/clients";
      fullPath: "/superadmin/clients";
      preLoaderRoute: typeof AuthSuperadminClientsRouteImport;
      parentRoute: typeof AuthSuperadminRoute;
    };
  }
}

interface AuthSuperadminRouteChildren {
  AuthSuperadminClientsRoute: typeof AuthSuperadminClientsRoute;
}

const AuthSuperadminRouteChildren: AuthSuperadminRouteChildren = {
  AuthSuperadminClientsRoute: AuthSuperadminClientsRoute,
};

const AuthSuperadminRouteWithChildren = AuthSuperadminRoute._addFileChildren(
  AuthSuperadminRouteChildren,
);

interface AuthRouteChildren {
  AuthConsentRoute: typeof AuthConsentRoute;
  AuthSuperadminRoute: typeof AuthSuperadminRouteWithChildren;
  AuthIndexRoute: typeof AuthIndexRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthConsentRoute: AuthConsentRoute,
  AuthSuperadminRoute: AuthSuperadminRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
