// Node-side stand-in for `@tanstack/react-start/server-entry`, aliased by core/os/vitest.config.ts
// and test/vitest.config.ts's node project. Start's server entry is generated by the Vite build and does not exist in
// plain node; the edge's routing rows (worker.test.ts) need only an issuer page that answers, with no
// `vi.mock` in the test file (iterate/no-vi-mock). It proves nothing about Start itself: the built
// worker's suites (test/vitest/os-workers/, the browser specs) run the real entry.

export default {
  fetch: () => new Response("<html>Issuer page</html>", { status: 200 }),
};
