import { workflow } from "@jlarky/gha-ts/workflow-types";
import * as utils from "../utils/index.ts";

const workerName = "stream-staging-area-pr-${{ github.event.pull_request.number }}";

export default workflow({
  name: "Streams E2E",
  on: {
    pull_request: {
      types: ["opened", "reopened", "synchronize", "closed"],
      paths: [
        ".github/ts-workflows/workflows/streams-e2e.ts",
        ".github/workflows/streams-e2e.yml",
        "packages/streams/**",
      ],
    },
  },
  permissions: {
    contents: "read",
  },
  concurrency: {
    group: "streams-e2e-pr-${{ github.event.pull_request.number }}",
    "cancel-in-progress": false,
  },
  jobs: {
    "streams-e2e": {
      if: "github.event.action != 'closed'",
      ...utils.runsOnDepotUbuntu,
      env: {
        DOPPLER_TOKEN: "${{ secrets.DOPPLER_TOKEN }}",
        WORKER_NAME: workerName,
        WORKER_URL: `https://${workerName}.iterate-dev-preview.workers.dev`,
        STREAM_STAGING_E2E: "true",
      },
      steps: [
        ...utils.getSetupRepo({ ref: "${{ github.event.pull_request.head.sha }}" }),
        utils.installDopplerCli,
        {
          name: "Destroy existing streams worker",
          "working-directory": "packages/streams/example-app",
          run: 'doppler run --project _shared --config prd -- pnpm exec wrangler delete "$WORKER_NAME" --force || true',
        },
        {
          name: "Build streams example app",
          "working-directory": "packages/streams/example-app",
          run: "pnpm build",
        },
        {
          name: "Deploy streams worker",
          "working-directory": "packages/streams/example-app",
          run: 'doppler run --project _shared --config prd -- pnpm exec wrangler deploy --name "$WORKER_NAME"',
        },
        {
          name: "Wait for streams worker",
          run: [
            "for attempt in {1..30}; do",
            "  if node --input-type=module <<'EOF'",
            'const target = new URL("/api/streams", process.env.WORKER_URL);',
            'target.searchParams.set("path", "/ci-readiness");',
            'target.protocol = target.protocol === "https:" ? "wss:" : "ws:";',
            "",
            "await new Promise((resolve, reject) => {",
            "  const socket = new WebSocket(target);",
            "  let opened = false;",
            "  const timeout = setTimeout(() => {",
            "    socket.close();",
            '    reject(new Error("Timed out connecting to " + target.href));',
            "  }, 5_000);",
            '  socket.addEventListener("open", () => {',
            "    opened = true;",
            "    clearTimeout(timeout);",
            "    socket.close();",
            "    resolve();",
            "  }, { once: true });",
            '  socket.addEventListener("error", () => {',
            "    clearTimeout(timeout);",
            '    reject(new Error("WebSocket failed for " + target.href));',
            "  }, { once: true });",
            '  socket.addEventListener("close", (event) => {',
            "    if (opened) return;",
            "    clearTimeout(timeout);",
            '    reject(new Error("WebSocket closed before open: " + event.code + " " + event.reason));',
            "  }, { once: true });",
            "});",
            "EOF",
            "  then",
            "    exit 0",
            "  fi",
            '  echo "Worker is not ready yet (attempt $attempt/30)."',
            "  sleep 2",
            "done",
            "",
            'echo "Streams worker did not become ready."',
            "exit 1",
          ].join("\n"),
        },
        {
          name: "Run streams Vitest e2e while installing Playwright browser",
          run: [
            "pnpm --dir packages/streams/example-app exec playwright install --with-deps chromium &",
            "playwright_install_pid=$!",
            "vitest_status=1",
            "for attempt in 1 2 3; do",
            "  if pnpm --dir packages/streams/example-app vitest; then",
            "    vitest_status=0",
            "    break",
            "  fi",
            '  echo "Streams Vitest e2e failed (attempt $attempt/3)."',
            '  if [ "$attempt" != "3" ]; then',
            "    sleep 10",
            "  fi",
            "done",
            "",
            "playwright_install_status=0",
            'wait "$playwright_install_pid" || playwright_install_status=$?',
            'if [ "$vitest_status" -ne 0 ]; then',
            '  exit "$vitest_status"',
            "fi",
            'if [ "$playwright_install_status" -ne 0 ]; then',
            '  exit "$playwright_install_status"',
            "fi",
          ].join("\n"),
        },
        {
          name: "Run streams Playwright e2e",
          run: "pnpm --dir packages/streams/example-app playwright",
        },
        {
          name: "Upload Playwright artifacts",
          if: "failure()",
          uses: "actions/upload-artifact@v4",
          with: {
            name: "streams-playwright-test-results",
            path: "packages/streams/example-app/test-results",
            "if-no-files-found": "ignore",
            "retention-days": 7,
          },
        },
      ],
    },
    cleanup: {
      if: "github.event.action == 'closed'",
      ...utils.runsOnDepotUbuntu,
      env: {
        DOPPLER_TOKEN: "${{ secrets.DOPPLER_TOKEN }}",
        WORKER_NAME: workerName,
      },
      steps: [
        ...utils.setupRepo,
        utils.installDopplerCli,
        {
          name: "Destroy streams worker",
          "working-directory": "packages/streams/example-app",
          run: 'doppler run --project _shared --config prd -- pnpm exec wrangler delete "$WORKER_NAME" --force || true',
        },
      ],
    },
  },
});
