#!/bin/bash
set -euo pipefail

# Canonical repo root inside the sandbox image; override only for local debugging.
ITERATE_REPO="${ITERATE_REPO:-/home/iterate/src/github.com/iterate/iterate}"

# Optional Docker host-sync keeps container source aligned to host checkout.
if [[ -n "${DOCKER_HOST_SYNC_ENABLED:-}" ]]; then
  bash "${ITERATE_REPO}/jonasland/sandbox/providers/docker/sync-repo-from-host.sh"
fi

# Refresh home skeleton so shell/tooling config changes are applied on boot.
if [[ -f "${ITERATE_REPO}/jonasland/sandbox/sync-home-skeleton.sh" ]]; then
  bash "${ITERATE_REPO}/jonasland/sandbox/sync-home-skeleton.sh"
fi

# Startup marker consumed by host-sync tooling and readiness/debug checks.
touch /tmp/reached-entrypoint

# Allow overriding the default sandbox process:
#   docker run --rm -it <image> sleep infinity
#   SANDBOX_ENTRY_ARGS="sleep\tinfinity" (tab-delimited, for providers without CMD support)
if [[ $# -gt 0 ]]; then
  exec "$@"
fi

if [[ -n "${SANDBOX_ENTRY_ARGS:-}" ]]; then
  IFS=$'\t' read -r -a env_entry_args <<< "${SANDBOX_ENTRY_ARGS}"
  if [[ ${#env_entry_args[@]} -gt 0 ]]; then
    exec "${env_entry_args[@]}"
  fi
fi

# Start dnsmasq and force local resolver so *.iterate.localhost routes to loopback.
# This must happen at runtime because container runtimes rewrite /etc/resolv.conf.
# See jonasland/hosts-and-routing.md for the full routing model.
sudo dnsmasq --conf-file=/etc/dnsmasq.d/iterate-localhost.conf
printf "nameserver 127.0.0.1\n" | sudo tee /etc/resolv.conf >/dev/null

# `iterate-egress` is created in the Docker image; we rely on that invariant here.
EGRESS_PROXY_UID="$(id -u iterate-egress)"

# Redirect outbound :80/:443 through local Caddy for HTTP(S) egress interception.
# Skip proxying traffic generated by the egress proxy process itself to avoid loops.
for port in 80 443; do
  sudo iptables -t nat -C OUTPUT -p tcp -m owner --uid-owner "${EGRESS_PROXY_UID}" --dport "$port" -j RETURN 2>/dev/null || \
    sudo iptables -t nat -I OUTPUT 1 -p tcp -m owner --uid-owner "${EGRESS_PROXY_UID}" --dport "$port" -j RETURN
  sudo iptables -t nat -C OUTPUT -p tcp --dport "$port" -j REDIRECT --to-ports "$port" 2>/dev/null || \
    sudo iptables -t nat -A OUTPUT -p tcp --dport "$port" -j REDIRECT --to-ports "$port"
done

# Hand off to pidnap, which supervises all sandbox services from one config.
exec "$ITERATE_REPO/packages/pidnap/node_modules/.bin/tsx" \
  "$ITERATE_REPO/packages/pidnap/src/cli.ts" \
  init -c "$ITERATE_REPO/jonasland/sandbox/pidnap.config.ts"
