import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

/**
 * The one observability posture every Iterate worker deploys with: full
 * sampling, persistent logs and traces. Shared by the per-app
 * generate-wrangler-config.ts scripts.
 */
export const OBSERVABILITY = {
  enabled: true,
  head_sampling_rate: 1,
  logs: { enabled: true, head_sampling_rate: 1, persist: true, invocation_logs: true },
  traces: { enabled: true, persist: true, head_sampling_rate: 1 },
};

/**
 * Write an app's generated, gitignored wrangler.jsonc if its content
 * changed, and return the path. The emitted header carries the breadcrumbs
 * a reader needs when they open the file cold (where it came from, how to
 * change it, where to learn more).
 *
 * Each app's generate-wrangler-config.ts wraps this as `writeWranglerConfig()`;
 * vite.config.ts calls that before the cloudflare plugin reads the file (so
 * dev/build can never see a stale config) and `pnpm gen:wrangler` runs it by
 * hand for ad-hoc wrangler commands.
 */
export function writeGeneratedWranglerConfig(input: {
  /** URL of `../wrangler.jsonc` relative to the calling generator module. */
  configUrl: URL;
  /** e.g. "apps/os" — names the app in the emitted header. */
  appLabel: string;
  /** Extra header line(s), e.g. a pointer to the app's topology doc. */
  extraDocs?: string;
  /** The full wrangler config object (top level = local dev, env blocks = deployed). */
  config: unknown;
}): string {
  const configPath = fileURLToPath(input.configUrl);
  const header = `// GENERATED by scripts/generate-wrangler-config.ts — gitignored, do not edit.
//
// This is ${input.appLabel}'s wrangler config, expanded from the root envs.ts
// plus Alchemy's generated data-resource manifest. The top-level block is
// local dev; a deployed build adds only the environment selected through
// CLOUDFLARE_ENV (deploy.ts does this for you).
//
// Regenerate:      pnpm gen:wrangler   (vite dev/build do it automatically)
// Change an env:   edit envs.ts or apps/env-manager/alchemy.run.ts, not this file
// How it all fits: docs/devops-cloudflare-doppler.md${input.extraDocs ? `, ${input.extraDocs}` : ""}
`;
  const rendered = header + JSON.stringify(input.config, null, 2) + "\n";
  const current = (() => {
    try {
      return readFileSync(configPath, "utf8");
    } catch {
      return null;
    }
  })();
  if (current !== rendered) writeFileSync(configPath, rendered);
  return configPath;
}

/** Render only the selected deployed environment; no selection means normal local dev. */
export function selectedDeployedEnvironmentBlock<Environment, Block>(
  environments: Record<string, Environment>,
  render: (name: string, environment: Environment) => Block,
  name: string | undefined,
) {
  if (!name) return {};
  const environment = environments[name];
  if (!environment) {
    throw new Error(
      `Unknown CLOUDFLARE_ENV ${JSON.stringify(name)}. Known: ${Object.keys(environments).join(", ")}.`,
    );
  }
  return { [name]: render(name, environment) };
}
