/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AppRoutesRouteImport } from './routes/_app/routes'
import { Route as AppRoutesIndexRouteImport } from './routes/_app/routes.index'
import { Route as AppRoutesRootHostRouteImport } from './routes/_app/routes.$rootHost'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoutesRoute = AppRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutesIndexRoute = AppRoutesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoutesRoute,
} as any)
const AppRoutesRootHostRoute = AppRoutesRootHostRouteImport.update({
  id: '/$rootHost',
  path: '/$rootHost',
  getParentRoute: () => AppRoutesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/routes': typeof AppRoutesRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/routes/$rootHost': typeof AppRoutesRootHostRoute
  '/routes/': typeof AppRoutesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/api/$': typeof ApiSplatRoute
  '/routes/$rootHost': typeof AppRoutesRootHostRoute
  '/routes': typeof AppRoutesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/health': typeof HealthRoute
  '/_app/routes': typeof AppRoutesRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/_app/routes/$rootHost': typeof AppRoutesRootHostRoute
  '/_app/routes/': typeof AppRoutesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/routes'
    | '/api/$'
    | '/routes/$rootHost'
    | '/routes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/health' | '/api/$' | '/routes/$rootHost' | '/routes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/health'
    | '/_app/routes'
    | '/api/$'
    | '/_app/routes/$rootHost'
    | '/_app/routes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  HealthRoute: typeof HealthRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/routes': {
      id: '/_app/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof AppRoutesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routes/': {
      id: '/_app/routes/'
      path: '/'
      fullPath: '/routes/'
      preLoaderRoute: typeof AppRoutesIndexRouteImport
      parentRoute: typeof AppRoutesRoute
    }
    '/_app/routes/$rootHost': {
      id: '/_app/routes/$rootHost'
      path: '/$rootHost'
      fullPath: '/routes/$rootHost'
      preLoaderRoute: typeof AppRoutesRootHostRouteImport
      parentRoute: typeof AppRoutesRoute
    }
  }
}

interface AppRoutesRouteChildren {
  AppRoutesRootHostRoute: typeof AppRoutesRootHostRoute
  AppRoutesIndexRoute: typeof AppRoutesIndexRoute
}

const AppRoutesRouteChildren: AppRoutesRouteChildren = {
  AppRoutesRootHostRoute: AppRoutesRootHostRoute,
  AppRoutesIndexRoute: AppRoutesIndexRoute,
}

const AppRoutesRouteWithChildren = AppRoutesRoute._addFileChildren(
  AppRoutesRouteChildren,
)

interface AppRouteChildren {
  AppRoutesRoute: typeof AppRoutesRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppRoutesRoute: AppRoutesRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  HealthRoute: HealthRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
