// Generate pinned MediaPipe data assets plus the bundled JavaScript loader.
// Manual, not CI: pnpm exec tsx scripts/generate-mediapipe-assets.ts
// Upload before writing the manifest; old URLs remain available.

import { createHash } from "node:crypto";
import { gzipSync } from "node:zlib";
import { readFileSync, writeFileSync } from "node:fs";

import { mobileWebsiteEnvs } from "../../../envs.ts";
import { resolveEnvContext } from "../../../scripts/lib/env-context.ts";
import { createAssetStore } from "./filter-asset-store.ts";

// The package's exports map hides subpaths from require.resolve; the direct
// node_modules path works because tasks-vision is a direct dependency here.
const resolve = (subpath: string) =>
  new URL(`../node_modules/@mediapipe/tasks-vision/${subpath}`, import.meta.url).pathname;

const version = JSON.parse(readFileSync(resolve("package.json"), "utf8")).version;
const loaderJs = readFileSync(resolve("wasm/vision_wasm_internal.js"));
const wasm = readFileSync(resolve("wasm/vision_wasm_internal.wasm"));
const response = await fetch(
  "https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task",
  { signal: AbortSignal.timeout(30_000) },
);
if (!response.ok) throw new Error(`Model download failed: ${response.status}`);
const model = Buffer.from(await response.arrayBuffer());
const ctx = await resolveEnvContext({ envs: mobileWebsiteEnvs, dopplerProject: "os", env: "prd" });
const store = createAssetStore({
  objectsUrl: `https://api.cloudflare.com/client/v4/accounts/${ctx.env.cloudflareAccountId}/r2/buckets/${ctx.env.workerName}-state/objects`,
  token: ctx.secrets.CLOUDFLARE_API_TOKEN,
});
const remoteEntry = async (name: string, slug: string, buffer: Buffer, extension: string) => {
  const bytes = gzipSync(buffer, { level: 9 });
  const filename = `${slug}-${createHash("sha256").update(bytes).digest("hex")}.${extension}.gz`;
  const url = `https://mobile.iterate.com/filter-assets/${filename}`;
  if (!(await store.exists(url))) await store.upload(slug, `${extension}.gz`, bytes);
  return `export const ${name}_URL = "${url}";`;
};

const entry = (name: string, buffer: Buffer) => {
  const gz = gzipSync(buffer, { level: 9 });
  console.log(
    `${name}: ${Math.round(buffer.length / 1024)}KB -> ${Math.round(gz.length / 1024)}KB gz`,
  );
  return `export const ${name} = "${gz.toString("base64")}";`;
};

const outPath = new URL("../src/lib/filters/mediapipe-assets.generated.ts", import.meta.url)
  .pathname;
writeFileSync(
  outPath,
  `// Generated by scripts/generate-mediapipe-assets.ts — do not edit by hand.
// MediaPipe tasks-vision ${version} wasm runtime + face_landmarker model,
// JavaScript loader bundled; WASM/model fetched as immutable data.

export const MEDIAPIPE_TASKS_VISION_VERSION = "${version}";

${entry("MEDIAPIPE_WASM_LOADER_JS_GZ", loaderJs)}

${await remoteEntry("MEDIAPIPE_WASM_GZ", "mediapipe-vision", wasm, "wasm")}

${await remoteEntry("FACE_LANDMARKER_MODEL_GZ", "face-landmarker", model, "task")}
`,
);
console.log(`wrote ${outPath}`);
