/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotAnAdminRouteImport } from './routes/not-an-admin'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ESplatRouteImport } from './routes/e.$'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AppResourcesRouteImport } from './routes/_app/resources'
import { Route as AppResourcesIndexRouteImport } from './routes/_app/resources.index'
import { Route as ApiOrpcSplatRouteImport } from './routes/api.orpc.$'
import { Route as AppResourcesTypeSlugRouteImport } from './routes/_app/resources.$type.$slug'

const NotAnAdminRoute = NotAnAdminRouteImport.update({
  id: '/not-an-admin',
  path: '/not-an-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ESplatRoute = ESplatRouteImport.update({
  id: '/e/$',
  path: '/e/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesIndexRoute = AppResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppResourcesRoute,
} as any)
const ApiOrpcSplatRoute = ApiOrpcSplatRouteImport.update({
  id: '/api/orpc/$',
  path: '/api/orpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppResourcesTypeSlugRoute = AppResourcesTypeSlugRouteImport.update({
  id: '/$type/$slug',
  path: '/$type/$slug',
  getParentRoute: () => AppResourcesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/not-an-admin': typeof NotAnAdminRoute
  '/resources': typeof AppResourcesRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/e/$': typeof ESplatRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/resources/': typeof AppResourcesIndexRoute
  '/resources/$type/$slug': typeof AppResourcesTypeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/not-an-admin': typeof NotAnAdminRoute
  '/api/$': typeof ApiSplatRoute
  '/e/$': typeof ESplatRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/resources': typeof AppResourcesIndexRoute
  '/resources/$type/$slug': typeof AppResourcesTypeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/health': typeof HealthRoute
  '/not-an-admin': typeof NotAnAdminRoute
  '/_app/resources': typeof AppResourcesRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/e/$': typeof ESplatRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/_app/resources/': typeof AppResourcesIndexRoute
  '/_app/resources/$type/$slug': typeof AppResourcesTypeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/not-an-admin'
    | '/resources'
    | '/api/$'
    | '/e/$'
    | '/api/orpc/$'
    | '/resources/'
    | '/resources/$type/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/not-an-admin'
    | '/api/$'
    | '/e/$'
    | '/api/orpc/$'
    | '/resources'
    | '/resources/$type/$slug'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/health'
    | '/not-an-admin'
    | '/_app/resources'
    | '/api/$'
    | '/e/$'
    | '/api/orpc/$'
    | '/_app/resources/'
    | '/_app/resources/$type/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  HealthRoute: typeof HealthRoute
  NotAnAdminRoute: typeof NotAnAdminRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ESplatRoute: typeof ESplatRoute
  ApiOrpcSplatRoute: typeof ApiOrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-an-admin': {
      id: '/not-an-admin'
      path: '/not-an-admin'
      fullPath: '/not-an-admin'
      preLoaderRoute: typeof NotAnAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$': {
      id: '/e/$'
      path: '/e/$'
      fullPath: '/e/$'
      preLoaderRoute: typeof ESplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/resources': {
      id: '/_app/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources/': {
      id: '/_app/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof AppResourcesIndexRouteImport
      parentRoute: typeof AppResourcesRoute
    }
    '/api/orpc/$': {
      id: '/api/orpc/$'
      path: '/api/orpc/$'
      fullPath: '/api/orpc/$'
      preLoaderRoute: typeof ApiOrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/resources/$type/$slug': {
      id: '/_app/resources/$type/$slug'
      path: '/$type/$slug'
      fullPath: '/resources/$type/$slug'
      preLoaderRoute: typeof AppResourcesTypeSlugRouteImport
      parentRoute: typeof AppResourcesRoute
    }
  }
}

interface AppResourcesRouteChildren {
  AppResourcesIndexRoute: typeof AppResourcesIndexRoute
  AppResourcesTypeSlugRoute: typeof AppResourcesTypeSlugRoute
}

const AppResourcesRouteChildren: AppResourcesRouteChildren = {
  AppResourcesIndexRoute: AppResourcesIndexRoute,
  AppResourcesTypeSlugRoute: AppResourcesTypeSlugRoute,
}

const AppResourcesRouteWithChildren = AppResourcesRoute._addFileChildren(
  AppResourcesRouteChildren,
)

interface AppRouteChildren {
  AppResourcesRoute: typeof AppResourcesRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppResourcesRoute: AppResourcesRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  HealthRoute: HealthRoute,
  NotAnAdminRoute: NotAnAdminRoute,
  ApiSplatRoute: ApiSplatRoute,
  ESplatRoute: ESplatRoute,
  ApiOrpcSplatRoute: ApiOrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
