export const FUNNY_SLUG_WORDS = [
  "amber",
  "brave",
  "bright",
  "brisk",
  "calm",
  "clever",
  "cozy",
  "crisp",
  "dreamy",
  "eager",
  "fancy",
  "gentle",
  "happy",
  "jolly",
  "kind",
  "lucky",
  "merry",
  "noble",
  "quick",
  "sunny",
  "acorn",
  "aspen",
  "berry",
  "bloom",
  "brook",
  "cedar",
  "cloud",
  "clover",
  "comet",
  "coral",
  "dawn",
  "ember",
  "fern",
  "frost",
  "grove",
  "hazel",
  "maple",
  "pebble",
  "river",
  "willow",
  "badger",
  "beaver",
  "bunny",
  "corgi",
  "coyote",
  "cricket",
  "falcon",
  "ferret",
  "fox",
  "gecko",
  "heron",
  "kitten",
  "lark",
  "otter",
  "panda",
  "raven",
  "robin",
  "sparrow",
  "tiger",
  "wren",
  "apple",
  "bagel",
  "basil",
  "biscuit",
  "brownie",
  "cider",
  "cocoa",
  "cookie",
  "donut",
  "ginger",
  "honey",
  "lemon",
  "muffin",
  "noodle",
  "peach",
  "pepper",
  "pickle",
  "pretzel",
  "taco",
  "waffle",
  "alley",
  "attic",
  "cabin",
  "canoe",
  "castle",
  "harbor",
  "hearth",
  "island",
  "lantern",
  "market",
  "orchard",
  "parlor",
  "porch",
  "plaza",
  "ranch",
  "saddle",
  "shore",
  "stable",
  "tavern",
  "wagon",
  "banjo",
  "bingo",
  "chorus",
  "disco",
  "fiddle",
  "glitter",
  "jingle",
  "melody",
  "picnic",
  "pogo",
  "polka",
  "puppet",
  "samba",
  "shimmer",
  "story",
  "sunset",
  "tinsel",
  "whistle",
  "wonder",
  "zigzag",
  "aura",
  "cosmos",
  "eclipse",
  "galaxy",
  "meteor",
  "moon",
  "mystic",
  "nebula",
  "nova",
  "prism",
  "solar",
  "sparkle",
  "starlit",
  "storm",
  "thunder",
  "twilight",
  "velvet",
  "zebra",
  "zodiac",
  "magic",
  "arya",
  "bilbo",
  "frodo",
  "groot",
  "hobbit",
  "leia",
  "loki",
  "luna",
  "mario",
  "moana",
  "pixie",
  "shrek",
  "simba",
  "sonic",
  "spock",
  "sully",
  "thor",
  "wanda",
  "xena",
  "yoda",
  "zelda",
  "yoshi",
  "merlin",
  "banshee",
  "centaur",
  "dragon",
  "fairy",
  "goblin",
  "griffin",
  "mermaid",
  "ogre",
  "phantom",
  "phoenix",
  "spirit",
  "troll",
  "vampire",
  "wizard",
  "yeti",
  "zombie",
  "genie",
  "breeze",
  "candle",
  "cherry",
  "dandy",
  "echo",
  "flame",
  "garden",
  "golden",
  "lilac",
  "marsh",
  "misty",
  "petal",
  "pine",
  "rainbow",
  "silver",
  "sprout",
  "thistle",
  "walnut",
  "winter",
  "butter",
] as const;

const REQUIRED_SLUG_PARTS = 3;

if (FUNNY_SLUG_WORDS.length !== 200) {
  throw new Error(
    `FUNNY_SLUG_WORDS must contain exactly 200 entries, got ${FUNNY_SLUG_WORDS.length}`,
  );
}

export function makeFunnySlug(): string {
  const chosen = new Set<string>();

  while (chosen.size < REQUIRED_SLUG_PARTS) {
    chosen.add(FUNNY_SLUG_WORDS[randomWordIndex()]!);
  }

  return [...chosen].join("-");
}

/**
 * Uniformly-sampled index into `FUNNY_SLUG_WORDS` using Web Crypto (universal
 * across Node ≥16, Cloudflare Workers and browsers, so this module can be
 * imported from the frontend without Node-only deps).
 *
 * Rejection-sampled to avoid modulo bias — the list length (200) doesn't
 * divide 2^32 evenly.
 */
function randomWordIndex(): number {
  const buffer = new Uint32Array(1);
  const cap = Math.floor(0x1_0000_0000 / FUNNY_SLUG_WORDS.length) * FUNNY_SLUG_WORDS.length;
  while (true) {
    crypto.getRandomValues(buffer);
    const value = buffer[0]!;
    if (value < cap) return value % FUNNY_SLUG_WORDS.length;
  }
}
