import { defineConfig } from "tsdown";

export default defineConfig([
  {
    entry: { node: "src/node.ts", "stream/test-support": "src/stream/test-support.ts" },
    format: "esm",
    fixedExtension: true,
    platform: "node",
    target: "node22",
    tsconfig: "tsconfig.node.build.json",
    deps: { neverBundle: ["@cloudflare/workers-types"] },
    dts: true,
    sourcemap: true,
    clean: true,
  },
  {
    entry: {
      sdk: "src/sdk/index.ts",
      app: "src/app.ts",
      "app-server": "src/app-server.ts",
      "app-session": "src/app-session.ts",
      client: "src/client/live-state.ts",
      react: "src/client/react.tsx",
      api: "src/api.ts",
      lib: "src/lib.ts",
      expression: "src/expression.ts",
      principal: "src/principal.ts",
      "stream/processor": "src/stream/processor.ts",
      "stream/contract": "src/stream/contract.ts",
      "stream/run": "src/stream/run.ts",
      email: "src/email.ts",
      "oauth-scopes": "src/oauth-scopes.ts",
      "project-ingress": "src/project-ingress.ts",
      "app-config": "src/app-config.ts",
      "compatibility-date": "src/compatibility-date.ts",
      "pkg-pr-new": "src/pkg-pr-new.ts",
      "platform-retry": "src/platform-retry.ts",
      "config-repo-template": "src/config-repo-template.ts",
      "integration-scopes": "src/integration-scopes.ts",
      oauth: "src/client/oauth.ts",
    },
    format: "esm",
    fixedExtension: true,
    platform: "neutral",
    target: "es2022",
    deps: { neverBundle: ["cloudflare:workers", "node:async_hooks", "@cloudflare/workers-types"] },
    dts: true,
    sourcemap: true,
    clean: false,
  },
  {
    // The `iterate` bin's module (bin/iterate.js imports dist/cli.mjs), with the SDK modules it uses.
    entry: { cli: "src/cli/cli.ts" },
    format: "esm",
    fixedExtension: true,
    platform: "node",
    target: "node22",
    tsconfig: "tsconfig.cli.json",
    dts: false,
    sourcemap: true,
    clean: false,
  },
]);
