// Instructions for the LLM on the other end of the MCP connection. MCP
// clients do not run the platform agent turn loop, but they still need the
// same mental model, discovery workflow, and script examples as an OS agent.
// Keep the essential execution contract in the tool description: clients are
// allowed to ignore the server-level instructions returned by initialize.

export function inboundMcpServerInstructions(input: { withAgent: boolean }): string {
  return [
    "Iterate OS makes each project a programmable workspace. Use exec_typescript to inspect or change the selected project through its itx capability tree.",
    "exec_typescript accepts one TypeScript async arrow function, async (itx) => { ... }, and returns the function's JSON-serializable return value. Use several small data-first calls: inspect, return the result, then decide the next call. Use Promise.all only for independent work inside one call.",
    ...(input.withAgent
      ? [
          "ask_assistant is also available for a plain-language request to the project's own assistant; use exec_typescript when you want direct, inspectable access to project capabilities.",
        ]
      : []),
    'itx contains built-ins plus capabilities mounted by this project. For anything unfamiliar, search with await itx.docs.search({ q: "several related words" }), execute a hit\'s fetchCall with itx.docs.get, or inspect a node with __describe(); never guess a call shape.',
    "One-off work belongs in an exec_typescript script. Lasting behaviour belongs in the project's config repo at itx.repo: worker.ts defines its website, apps, event reactions, and agent configuration; commits land on main and redeploy automatically.",
    "The exec_typescript tool description contains representative scripts, the full discovery sequence, project-repo guidance, and pointers for researching deeper platform documentation.",
  ].join("\n");
}

export const EXEC_TYPESCRIPT_DESCRIPTION = [
  "Execute TypeScript against an Iterate project. Pass exactly one async arrow function as code: async (itx) => { ... }. Its JSON-serializable return value becomes this tool result; a thrown error becomes the tool error.",
  "STANDARD TYPESCRIPT FENCE: open examples with ```ts. Pass only the function inside the fence as exec_typescript.code.",
  "DEEPER DOCS: https://github.com/iterate/iterate — start with apps/os/src/README.md, apps/os/docs/, apps/os/src/itx/examples.ts, and apps/os/src/itx-api.generated.ts.",
  "",
  "QUICK START:",
  "```ts",
  "async (itx) => {",
  "  const project = await itx.__describe();",
  '  const hits = await itx.docs.search({ q: "repo file edit commit write change" });',
  "  return { project, hits };",
  "}",
  "```",
  "Research unfamiliar calls with `itx.docs.search`, run a hit's exact `fetchCall` through `itx.docs.get`, inspect any live node with `__describe()`, and validate consequential scripts with `itx.docs.typecheck({ code })`. Prefer the returned proven examples and TypeScript declarations over guessed APIs.",
  "For deeper platform research, read https://github.com/iterate/iterate: start with `apps/os/src/README.md`, `apps/os/docs/`, `apps/os/src/itx/examples.ts`, and `apps/os/src/itx-api.generated.ts`. Use the built-in Exa search/fetch capabilities to locate and read them.",
  "",
  "MENTAL MODEL",
  "`itx` is the selected project's capability tree, scoped to this MCP session. It includes platform built-ins (docs, streams, repo, agents, files, integrations, sandboxes, scheduler, AI, browser, MCP/OpenAPI clients, and more) plus capabilities mounted by this project. One-off work is an itx script. Lasting behaviour is code in the config repo at `itx.repo` (`/repos/config`): `worker.ts` defines the project's website and apps, event reactions, worker capabilities, and new-agent configuration. Config-repo commits land on main and redeploy automatically.",
  "",
  "Each call runs in a fresh isolate, so local variables do not survive calls. Treat scripts like tool calls, not applications: fetch data and RETURN it, inspect the result, then make the next call. Do not infer response shapes you have not seen or hide useful failures in defensive try/catch. Return only useful fields and slice large arrays. Use Promise.all to fan out independent reads within a call.",
  "",
  "RESEARCH BEFORE GUESSING",
  '1. Search HOW: `await itx.docs.search({ q: "many related words and synonyms" })`. It searches proven example scripts, TypeScript declarations, and this project\'s mounted capabilities — matching is simple word overlap, so `"repo file edit commit write change"` beats `"repo"`. For WHAT the project knows — its conversations, webhooks, events, files, and repo content — `await itx.search.query({ q })`: every hit carries a `ref` expression that fetches the exact source back.',
  "2. Fetch: every search hit has `{ kind, name, summary, fetchCall }`. Run its exact fetchCall next. `itx.docs.get({ name })` returns paste-ready example code, a type declaration with referenced types, or mounted-capability instructions and types. Prefer a proven example over an invented call.",
  "3. Inspect: `await itx.__describe()` returns project identity, built-in children, and mounted capabilities. Every child handle also has `__describe()` with instructions, types, and its member map.",
  "4. Check: `await itx.docs.typecheck({ code })` checks an entire `async (itx) => { ... }` script against this scope without running it. It is advisory, but catches misspelled methods and wrong argument shapes before a consequential call.",
  "",
  "REPRESENTATIVE SCRIPTS (pass the function itself as exec_typescript.code)",
  "",
  "Discover the project and find working code:",
  "```ts",
  "async (itx) => {",
  "  const [project, hits] = await Promise.all([",
  "    itx.__describe(),",
  '    itx.docs.search({ q: "repo file edit commit write change" }),',
  "  ]);",
  "  return {",
  "    project: { name: project.name, projectId: project.projectId, children: project.children },",
  "    mountedCapabilities: project.capabilities,",
  "    hits,",
  "  };",
  "}",
  "```",
  "",
  "Fetch the selected documentation hit (search hits already provide this call):",
  "```ts",
  "async (itx) => {",
  '  return await itx.docs.get({ name: "repo-edit-file" });',
  "}",
  "```",
  "",
  "Read project-specific instructions and code before changing them:",
  "```ts",
  "async (itx) => {",
  "  const [instructions, worker] = await Promise.all([",
  '    itx.repo.readFile({ path: "AGENTS.md" }),',
  '    itx.repo.readFile({ path: "worker.ts" }),',
  "  ]);",
  "  return { instructions, worker };",
  "}",
  "```",
  'After inspecting that result, make a targeted edit with `itx.repo.edit({ path: "worker.ts", message, oldString, newString })`; `oldString` must match exactly once unless `replaceAll: true`. Use `commitFiles` for new files or batch/full-file writes. Use a sandbox only when the work truly needs shell commands, tests, package managers, or a running server.',
  "",
  "Research the web and discover connected services in parallel:",
  "```ts",
  "async (itx) => {",
  "  const [connections, search] = await Promise.all([",
  "    itx.integrations.list(),",
  '    itx.mcp.exa.web_search_exa({ query: "Cloudflare Durable Objects docs", numResults: 5 }),',
  "  ]);",
  "  return { connections, search };",
  "}",
  "```",
  'Read pages with `itx.mcp.exa.web_fetch_exa({ urls, maxCharacters })` or `itx.browser.quickAction("markdown", { url })`. Search docs before using unfamiliar integration methods: each connection and capability can have a project-specific shape.',
  "",
  "DOCUMENTATION LADDER",
  "Use `itx.docs.search/get/typecheck` for executable platform documentation; use `__describe()` for the live tree and project-specific mounts; read the config repo's `AGENTS.md` and relevant source for project-local knowledge. For deeper platform research, Iterate is open source at https://github.com/iterate/iterate: `apps/os/src/README.md` explains itx architecture, `apps/os/docs/` covers platform subsystems, `apps/os/src/itx/examples.ts` is the example catalogue, `apps/os/src/rpc-targets.ts` defines runtime capability behaviour, and `apps/os/src/itx-api.generated.ts` is the generated script-facing type surface. You can locate and read those pages with the built-in Exa tools. Architecture summaries are also available at https://deepwiki.com/iterate/iterate.",
  "",
  "Useful starting points after discovery: create an agent explicitly with `const agent = itx.agents.get(path); await agent.create(); await agent.message(task)` to delegate durable work; `itx.scheduler` runs a stringified itx script later; `itx.files` stores and shares bytes; `itx.mcp.connect` and `itx.openapi.connect` turn external APIs into callable targets. Do not assume their signatures—fetch the matching example or type first. If a pipelined handle call fails oddly, await the handle first and call its method in a second statement.",
].join("\n");
