// module-resolution.ts — a SOURCE as authored (TypeScript or JavaScript files, relative imports with
// or without extensions, bare package imports, an optional package.json) → the module map the Worker
// Loader takes (every name ends in `.js`, every import relative or a workerd builtin) and its main
// module (`readPackage`). No bundler, no build step: each file is type-stripped (sucrase) and its
// import specifiers are rewritten in place (es-module-lexer), so the code that runs is the code that
// was written, line for line.
//
// Where a bare import comes from — every one loads as `node_modules/<specifier>.js`:
// - `iterate/*` and `zod` — THIS deployment's own build of the SDK (platform-modules.js,
//   apps/os/scripts/build.ts): first-party code and user code link the same modules; on a preview,
//   the PR's SDK. A subpath of either that the platform does not ship is refused by name.
// - anything else — esm.sh, from package.json's `dependencies`: an npm range, or a pkg.pr.new URL
//   (`https://pkg.pr.new/<owner>/<repo>/<package>@<sha|pr|branch>`, a vendor's build). The graph is
//   crawled once per dependency set and LOCKED in the module store: every later load of that set, in
//   any project, gets the first resolution — a range, a branch or a PR ref included — and never
//   touches the network. esm.sh keeps the platform packages external, so a library's zod is the SDK's.

import { parse } from "es-module-lexer/js";
import { transform } from "sucrase";
import { z } from "zod";

/** A module map: module name → code. */
export type ModuleMap = Record<string, string>;

/** This deployment's platform packages (generated by apps/os/scripts/build.ts): each entry at
 *  `node_modules/<specifier>.js`, its shared chunks under `node_modules/.platform/`. */
export type PlatformModules = {
  modules: ModuleMap;
  /** Module name → the platform module names it imports (esbuild's metafile). */
  imports: Record<string, string[]>;
};

/** Where resolved dependency graphs are kept (ITX_KV in the platform). Values are immutable. */
export type ModuleStore = {
  get(key: string): Promise<string | null>;
  put(key: string, value: string): Promise<void>;
};

export type ResolveOptions = {
  platform: PlatformModules;
  store: ModuleStore;
  fetch: typeof fetch;
  /** Names the load site in errors. */
  where: string;
};

/** Where an entry is looked for when package.json names no `main`, in order. */
const ENTRY_FILES = ["worker.ts", "worker.js", "index.ts", "index.js"];
const ESM_ORIGIN = "https://esm.sh";

const isRelative = (specifier: string) => specifier.startsWith("./") || specifier.startsWith("../");

/** The package a bare specifier names: `@scope/pkg/sub` → `@scope/pkg`. */
function packageName(specifier: string): string {
  const parts = specifier.split("/");
  return parts.slice(0, specifier.startsWith("@") ? 2 : 1).join("/");
}

/** The relative specifier workerd resolves from module `from` to module `to`. */
function relativeSpecifier(from: string, to: string): string {
  const fromDir = from.split("/").slice(0, -1);
  const toParts = to.split("/");
  let shared = 0;
  while (
    shared < fromDir.length &&
    shared < toParts.length - 1 &&
    fromDir[shared] === toParts[shared]
  )
    shared++;
  const up = fromDir.length - shared;
  return (up === 0 ? "./" : "../".repeat(up)) + toParts.slice(shared).join("/");
}

/** `a/b/../c.ts` → `a/c.ts`, relative to the importing module's directory. */
function joinPath(fromModule: string, specifier: string): string {
  const out = fromModule.split("/").slice(0, -1);
  for (const part of specifier.split("/")) {
    if (part === "..") out.pop();
    else if (part !== "." && part !== "") out.push(part);
  }
  return out.join("/");
}

/** One import of a module: its specifier and where es-module-lexer found its text. */
type SpecifierEdit = { specifier: string; start: number; end: number; dynamic: boolean };

/** Rewrite each import's specifier text (es-module-lexer spans) — static specifiers are unquoted
 *  spans, dynamic ones include their quotes. */
function rewriteSpecifiers(code: string, edits: SpecifierEdit[]): string {
  let out = code;
  for (const edit of [...edits].sort((a, b) => b.start - a.start))
    out =
      out.slice(0, edit.start) +
      (edit.dynamic ? JSON.stringify(edit.specifier) : edit.specifier) +
      out.slice(edit.end);
  return out;
}

/** Imports of one module, with non-literal dynamic imports refused (they cannot be resolved ahead). */
function importsOf(code: string, name: string, where: string): SpecifierEdit[] {
  let imports;
  try {
    [imports] = parse(code, name);
  } catch (error) {
    throw new Error(`${where}: ${name} is not a valid module: ${String(error)}`);
  }
  const out: SpecifierEdit[] = [];
  for (const imp of imports) {
    if (imp.d === -2) continue; // import.meta
    if (!imp.n)
      throw new Error(
        `${where}: ${name} has a dynamic import() of a computed specifier; only string literals can be resolved`,
      );
    out.push({ specifier: imp.n, start: imp.s, end: imp.e, dynamic: imp.d > -1 });
  }
  return out;
}

/** TypeScript with its types stripped (nothing else: `using`, decorators aside, runs as written). */
function stripTypes(code: string, name: string, where: string): string {
  try {
    return transform(code, {
      transforms: ["typescript"],
      disableESTransforms: true,
      filePath: name,
    }).code;
  } catch (error) {
    throw new Error(`${where}: ${name} does not parse as TypeScript: ${String(error)}`);
  }
}

const PackageManifest = z.object({
  main: z.string().optional(),
  dependencies: z.record(z.string(), z.string()).optional(),
});

/** A source's package: its entry — package.json's `main`, else the first of `worker.ts`, `worker.js`,
 *  `index.ts`, `index.js`, as npm and wrangler find it — and its `dependencies`. The loader asks for
 *  it where a literal source is handed in, so a source with no entry is refused there. */
export function readPackage(
  source: ModuleMap,
  where: string,
): { entry: string; dependencies: Record<string, string> } {
  let manifest: z.infer<typeof PackageManifest> = {};
  if (source["package.json"]) {
    let parsed: unknown;
    try {
      parsed = JSON.parse(source["package.json"]);
    } catch (error) {
      throw new Error(`${where}: package.json is not valid JSON: ${String(error)}`);
    }
    const result = PackageManifest.safeParse(parsed);
    if (!result.success)
      throw new Error(
        `${where}: package.json needs "main" to be a path and "dependencies" to map package names to versions`,
      );
    manifest = result.data;
  }
  const { main } = manifest;
  const entry = main ? joinPath("", main) : ENTRY_FILES.find((file) => Object.hasOwn(source, file));
  if (!entry || !Object.hasOwn(source, entry))
    throw new Error(
      `${where}: no entry — ${main ? `package.json's main ${JSON.stringify(main)} is not a file` : `name it in package.json "main", or add one of ${ENTRY_FILES.join(", ")}`}`,
    );
  return { entry, dependencies: manifest.dependencies || {} };
}

/** Every bare import is this module: a platform entry (build.ts names them so) or an npm package's
 *  esm.sh entry (the lock stores it so) — one naming rule, so an import is rewritten as it is read. */
const moduleOfSpecifier = (specifier: string) => `node_modules/${specifier}.js`;

/** The packages the platform ships (`iterate`, `zod`), from its entries' names. */
function platformPackages(platform: PlatformModules): string[] {
  const entries = Object.keys(platform.modules).filter(
    (name) => !name.startsWith("node_modules/."),
  );
  return [
    ...new Set(
      entries.map((name) => packageName(name.slice("node_modules/".length, -".js".length))),
    ),
  ].sort();
}

/** A bare import's platform module, or nothing when the platform does not ship the package; a
 *  subpath of a platform package it does not ship is refused (a second copy would break the one). */
function platformModuleOf(
  specifier: string,
  platform: PlatformModules,
  where: string,
): string | undefined {
  const name = moduleOfSpecifier(specifier);
  if (Object.hasOwn(platform.modules, name)) return name;
  if (platformPackages(platform).includes(packageName(specifier)))
    throw new Error(
      `${where}: ${specifier} is not a module loaded workers have (the platform ships ${Object.keys(
        platform.modules,
      )
        .filter((module) => !module.startsWith("node_modules/."))
        .map((module) => module.slice("node_modules/".length, -".js".length))
        .join(", ")})`,
    );
  return undefined;
}

/**
 * THE resolution: authored source → loader modules and the main module's name. `source` is the files
 * a caller handed the loader (a repo's files, an inline map). Only what the entry reaches is loaded —
 * a test file or a README beside the worker costs nothing.
 */
export async function resolveModules(
  source: ModuleMap,
  opts: ResolveOptions,
): Promise<{ mainModule: string; modules: ModuleMap }> {
  const { where, platform } = opts;
  const { entry, dependencies } = readPackage(source, where);
  const out: ModuleMap = {};
  const outputName = (path: string) => path.replace(/\.(mts|ts|mjs|js)$/, "") + ".js";
  const findSourceFile = (path: string): string | undefined => {
    const candidates = [path, `${path}.ts`, `${path}.js`, `${path}/index.ts`, `${path}/index.js`];
    // `./x.js` may name the author's `x.ts` (TypeScript's own convention).
    if (path.endsWith(".js")) candidates.push(path.replace(/\.js$/, ".ts"));
    return candidates.find(
      (candidate) => Object.hasOwn(source, candidate) && /\.(js|mjs|ts|mts)$/.test(candidate),
    );
  };
  // 1. the author's modules, walked from the entry and rewritten in one pass.
  const platformUsed: string[] = [];
  const npmSpecifiers = new Set<string>();
  const seen = new Set<string>([entry]);
  const queue = [entry];
  while (queue.length) {
    const path = queue.pop()!;
    const name = outputName(path);
    if (Object.hasOwn(out, name))
      throw new Error(`${where}: ${path} and another file both load as ${name}`);
    const code = /\.m?ts$/.test(path) ? stripTypes(source[path]!, path, where) : source[path]!;
    const edits: SpecifierEdit[] = [];
    for (const edit of importsOf(code, name, where)) {
      const { specifier } = edit;
      if (specifier.startsWith("cloudflare:")) continue;
      let target: string;
      if (isRelative(specifier)) {
        const file = findSourceFile(joinPath(path, specifier));
        if (!file)
          throw new Error(`${where}: ${path} imports ${specifier}, and there is no such file`);
        if (!seen.has(file)) {
          seen.add(file);
          queue.push(file);
        }
        target = outputName(file);
      } else if (specifier.startsWith("node:")) {
        throw new Error(
          `${where}: ${path} imports the Node.js builtin ${specifier}, which loaded workers do not have`,
        );
      } else if (specifier.startsWith("/") || /^[a-z]+:/.test(specifier)) {
        throw new Error(
          `${where}: ${path} imports ${specifier}; import packages by name and list them in package.json`,
        );
      } else {
        const platformModule = platformModuleOf(specifier, platform, where);
        if (platformModule) platformUsed.push(platformModule);
        else if (Object.hasOwn(dependencies, packageName(specifier))) npmSpecifiers.add(specifier);
        else
          throw new Error(
            `${where}: ${path} imports ${specifier}; list ${packageName(specifier)} in package.json "dependencies"`,
          );
        target = moduleOfSpecifier(specifier);
      }
      edits.push({ ...edit, specifier: relativeSpecifier(name, target) });
    }
    out[name] = rewriteSpecifiers(code, edits);
  }

  // 2. npm packages: their locked graph, which may itself import platform packages.
  if (npmSpecifiers.size) {
    const graph = await lockedDependencyGraph([...npmSpecifiers].sort(), dependencies, opts);
    Object.assign(out, graph.modules);
    platformUsed.push(...graph.platformModules);
  }

  // 3. the platform modules the worker reaches, and nothing else.
  while (platformUsed.length) {
    const name = platformUsed.pop()!;
    if (Object.hasOwn(out, name)) continue;
    out[name] = platform.modules[name]!;
    platformUsed.push(...(platform.imports[name] ?? []));
  }
  return { mainModule: outputName(entry), modules: out };
}

/** A locked npm graph: every module (each requested specifier's entry under
 *  `node_modules/<specifier>.js`), and the platform modules it imports (esm.sh leaves them external). */
type DependencyGraph = { modules: ModuleMap; platformModules: string[] };

async function sha256(text: string): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
  return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join("");
}

/** The dependency graph for these specifiers under these ranges — from the store when this exact
 *  set was resolved before (by any project), otherwise resolved from esm.sh and stored. */
async function lockedDependencyGraph(
  specifiers: string[],
  dependencies: Record<string, string>,
  opts: ResolveOptions,
): Promise<DependencyGraph> {
  const packages = [...new Set(specifiers.map(packageName))].sort();
  const lockInput = {
    specifiers,
    ranges: Object.fromEntries(packages.map((name) => [name, dependencies[name]!])),
    externals: platformPackages(opts.platform),
  };
  // The prefix names the lock's shape and the rewrite rules: a change to either is a new prefix.
  const key = `module-lock-1/${await sha256(JSON.stringify(lockInput))}`;
  const stored = await opts.store.get(key);
  if (stored) return JSON.parse(stored) as DependencyGraph;
  const graph = await resolveFromEsm(lockInput, opts);
  await opts.store.put(key, JSON.stringify(graph));
  return graph;
}

/** An esm.sh module path → its loader name under `node_modules/.esm/`, readable and ending in `.js`
 *  (`/hono@>=3.9.0/validator?target=es2022` → `node_modules/.esm/hono@>=3.9.0/validator~target=es2022.js`).
 *  Synchronous, so an import is rewritten before its target arrives. */
function esmModuleName(url: URL): string {
  const path = url.pathname.replace(/\.m?js$/, "");
  const query = url.search ? `~${url.search.slice(1).replace(/[^\w.=@-]+/g, "_")}` : "";
  return `node_modules/.esm${path}${query}.js`.replace(/\/+/g, "/");
}

/** esm.sh's URL for a package at a version: `/<name>@<range>` for an npm range, and for a pkg.pr.new
 *  URL (whose package must be the one it is listed under) `/pr/<owner>/<repo>/<name>@<commit>`. A ref
 *  that is not a commit (a PR number, a branch) is pinned to the commit pkg.pr.new serves for it now
 *  (its `x-commit-key` header): esm.sh cannot resolve such a ref for a scoped package. */
async function esmPackageBase(name: string, range: string, opts: ResolveOptions): Promise<string> {
  if (!range.startsWith("https://pkg.pr.new/")) return `${ESM_ORIGIN}/${name}@${range}`;
  const [owner, repo, ...rest] = new URL(range).pathname.slice(1).split("/");
  const listed = rest.join("/");
  if (!owner || !repo || !listed.startsWith(`${name}@`))
    throw new Error(
      `${opts.where}: package.json lists ${name} as ${range}; a pkg.pr.new version is https://pkg.pr.new/<owner>/<repo>/${name}@<sha|pr|branch>`,
    );
  let ref = listed.slice(name.length + 1);
  if (!/^[0-9a-f]{7,40}$/.test(ref)) {
    const head = await opts.fetch(range, { method: "HEAD" });
    const commit = head.headers.get("x-commit-key")?.split(":").at(-1);
    if (!head.ok || !commit)
      throw new Error(`${range} answered ${head.status} without the commit it serves`);
    ref = commit;
  }
  return `${ESM_ORIGIN}/pr/${owner}/${repo}/${name}@${ref}`;
}

/** An esm.sh module's text, read whole; anything but a JavaScript 200 is refused. */
async function fetchModuleText(url: string, fetchFn: typeof fetch): Promise<string> {
  const response = await fetchFn(url, { headers: { "user-agent": "iterate-os" } });
  const text = await response.text();
  if (response.status !== 200) throw new Error(`${url} answered ${response.status}`);
  const type = response.headers.get("content-type") ?? "";
  if (!type.includes("javascript")) throw new Error(`${url} is ${type || "untyped"}, not a module`);
  return text;
}

/** Crawl esm.sh from each specifier's entry, pipelined: a module is rewritten and its own imports
 *  fetched the moment it arrives (module names follow from URLs alone), so wall time is the graph's
 *  depth in round trips, not its size. */
async function resolveFromEsm(
  lock: { specifiers: string[]; ranges: Record<string, string>; externals: string[] },
  opts: ResolveOptions,
): Promise<DependencyGraph> {
  const { where, platform } = opts;
  const query = new URLSearchParams({ target: "es2022", external: lock.externals.join(",") });
  const modules: ModuleMap = {};
  const platformModules = new Set<string>();
  const started = new Set<string>();
  const inFlight = new Set<Promise<void>>();
  const failures: string[] = [];

  /** Load `href` once, under `name`. */
  const load = (href: string, name: string): void => {
    if (started.has(href)) return;
    started.add(href);
    const url = new URL(href);
    const loading = (async () => {
      const code = await fetchModuleText(href, opts.fetch);
      const edits: SpecifierEdit[] = [];
      for (const edit of importsOf(code, href, where)) {
        const { specifier } = edit;
        const builtin = specifier.match(/^\/?(cloudflare:[^?]+)/)?.[1];
        if (builtin) {
          edits.push({ ...edit, specifier: builtin });
        } else if (specifier.startsWith("node:")) {
          // esm.sh's own `/node/*.mjs` polyfills are ordinary modules; a bare `node:` import would
          // need nodejs_compat, which loaded workers run without.
          throw new Error(
            `${url.pathname} needs the Node.js builtin ${specifier}, which loaded workers do not have`,
          );
        } else if (specifier.startsWith("/") || isRelative(specifier)) {
          const child = new URL(specifier, url);
          if (child.origin !== ESM_ORIGIN)
            throw new Error(`${url.pathname} imports ${child.href}, outside esm.sh`);
          const childName = esmModuleName(child);
          load(child.href, childName);
          edits.push({ ...edit, specifier: relativeSpecifier(name, childName) });
        } else {
          // Bare: only the platform packages esm.sh left external.
          const platformModule = platformModuleOf(specifier, platform, url.pathname);
          if (!platformModule)
            throw new Error(`${url.pathname} imports ${specifier}, which esm.sh left unresolved`);
          platformModules.add(platformModule);
          edits.push({ ...edit, specifier: relativeSpecifier(name, platformModule) });
        }
      }
      modules[name] = rewriteSpecifiers(code, edits);
    })().catch((error: Error) => void failures.push(error.message));
    inFlight.add(loading);
    void loading.finally(() => inFlight.delete(loading));
  };

  for (const specifier of lock.specifiers) {
    const name = packageName(specifier);
    const base = await esmPackageBase(name, lock.ranges[name]!, opts);
    load(`${base}${specifier.slice(name.length)}?${query}`, moduleOfSpecifier(specifier));
  }
  while (inFlight.size) await Promise.all(inFlight);
  if (failures.length)
    throw new Error(
      `${where}: resolving ${lock.specifiers.join(", ")} failed: ${failures.join("; ")}`,
    );
  return { modules, platformModules: [...platformModules].sort() };
}
