/**
 * A workspace is its path under /agents/, and that path is also the agent
 * sharing it. Nothing here validates: the platform's agent-path rule
 * (lowercase segments) applies when the workspace's agent is born. The one
 * helper draws a suggestion so nobody has to invent a path.
 */

const WORDS = [
  "acorn",
  "amber",
  "apple",
  "aspen",
  "badger",
  "bamboo",
  "basil",
  "beacon",
  "birch",
  "bison",
  "bramble",
  "breeze",
  "canyon",
  "cedar",
  "cinder",
  "clover",
  "cobalt",
  "comet",
  "coral",
  "cricket",
  "dahlia",
  "delta",
  "dune",
  "ember",
  "falcon",
  "fern",
  "finch",
  "fjord",
  "garnet",
  "ginger",
  "glacier",
  "harbor",
  "hazel",
  "heron",
  "indigo",
  "iris",
  "jade",
  "juniper",
  "kestrel",
  "lagoon",
  "lantern",
  "lark",
  "lilac",
  "lotus",
  "maple",
  "marble",
  "meadow",
  "mesa",
  "moss",
  "nectar",
  "nutmeg",
  "ocean",
  "olive",
  "onyx",
  "orchid",
  "otter",
  "pebble",
  "pepper",
  "pine",
  "plum",
  "poppy",
  "quartz",
  "raven",
  "reef",
  "river",
  "robin",
  "saffron",
  "sage",
  "sequoia",
  "slate",
  "sparrow",
  "spruce",
  "tiger",
  "tulip",
  "violet",
  "walnut",
  "willow",
  "yarrow",
  "zebra",
];

/** A suggested path for a new workspace: three random words under /agents/. */
export function newWorkspacePath(random: () => number = Math.random): string {
  const pick = () => WORDS[Math.floor(random() * WORDS.length)]!;
  return `/agents/${pick()}-${pick()}-${pick()}`;
}
