// module-resolution.ts — a SOURCE as authored (TypeScript or JavaScript files, relative imports with
// or without extensions, bare package imports, a package.json whose `main` names the entry) → the
// module map the Worker Loader takes (every name ends in `.js`, every import relative or a workerd
// builtin) and its main module (`readPackage`). No bundler, no build step: each file is type-stripped (sucrase) and its
// import specifiers are rewritten in place (es-module-lexer), so the code that runs is the code that
// was written, line for line.
//
// Where a bare import comes from — every one loads as `node_modules/<specifier>.js`:
// - `iterate/*` and `zod` — THIS deployment's own build of the SDK (platform-modules.js,
//   core/os/scripts/build.ts): first-party code and user code link the same modules; on a preview,
//   the PR's SDK. A subpath of either that the platform does not ship is refused by name.
// - anything else — esm.sh, from package.json's `dependencies`: an npm version, an npm alias
//   (`"foo": "npm:bar@1.2.3"`: bar, imported as `foo` and `foo/<subpath>`), or a pkg.pr.new URL at
//   a commit (`https://pkg.pr.new/<owner>/<repo>/<package>@<40-hex sha>`, a vendor's build). The
//   graph is crawled once per dependency set, as written, and LOCKED in the module store: every
//   later load of that set, in any project, gets the same modules and never touches the network. An
//   exact version or a commit is one build. A range or a dist-tag (`latest`) keeps its first
//   resolution, as a lockfile keeps it until someone updates it, here by writing another version. A
//   pkg.pr.new ref that is not a full commit (a branch, a PR number, a short sha) is refused: a
//   moving ref asks to follow it, which a lock cannot do without asking pkg.pr.new on every cold
//   start, and a project's builds would then differ by when each host started. Whatever writes a
//   dependency pins it as it writes (iterate/pkg-pr-new `pinPkgPrNewVersion`). esm.sh
//   keeps the platform packages external, so a library's zod is the SDK's. An alias OF a platform
//   package (`"zod3": "npm:zod@3"`) is a second copy its source asked for by another name: its own
//   modules import each other at its version (`npmSelfImportOf`).

import { isPkgPrNewCommit, pkgPrNewBuildOf } from "iterate/pkg-pr-new";
import { failureKind, httpFailureKind, isPlatformFailureKind } from "iterate/platform-retry";
import { parse } from "es-module-lexer/js";
import { transform } from "sucrase";
import { z } from "zod";
import { sha256Hex } from "../caller.ts";
import { unavailableError } from "../unavailable.ts";

/** A module map: module name → code. */
export type ModuleMap = Record<string, string>;

/** This deployment's platform packages (generated by core/os/scripts/build.ts): each entry at
 *  `node_modules/<specifier>.js`, its shared chunks under `node_modules/.platform/`. */
export type PlatformModules = {
  modules: ModuleMap;
  /** Module name → the platform module names it imports (esbuild's metafile). */
  imports: Record<string, string[]>;
};

/** Where resolved dependency graphs are kept (ITX_KV in the platform). Values are immutable. */
export type ModuleStore = {
  get(key: string): Promise<string | null>;
  put(key: string, value: string): Promise<void>;
};

export type ResolveOptions = {
  platform: PlatformModules;
  store: ModuleStore;
  fetch: typeof fetch;
  /** Names the load site in errors. */
  where: string;
  /** The module to load as the entry in place of package.json's `main` — the worker's
   *  `mainModule`, as Cloudflare's Worker Loader names it: a facet whose class lives in `agents.ts`
   *  of a source whose `main` is `worker.ts` loads `agents.ts`'s own graph. Its dependencies are
   *  still package.json's. */
  mainModule?: string;
};

/** Where an entry is looked for when package.json names no `main`, in order. The platform, its
 *  templates and its installers always write `main`; a source that names none still loads through
 *  this list: a config repo seeded without `main`, and packages/agents' AI transport source.
 *  Remove it once no such source remains; the module-resolution.test.ts rows that pin it then
 *  become refusals. */
const ENTRY_FILES = ["worker.ts", "worker.js", "index.ts", "index.js"];
const ESM_ORIGIN = "https://esm.sh";

/** How long one esm.sh module may take to arrive before its resolution is the platform's failure. */
const ESM_FETCH_TIMEOUT_MS = 20_000;
/** The runtime's own modules, external to esm.sh like the platform packages: its bundler cannot
 *  find them, and a package importing one from its entry is refused (404) unless it is named. */
const WORKERD_BUILTINS = ["cloudflare:email", "cloudflare:sockets", "cloudflare:workers"];

const isRelative = (specifier: string) => specifier.startsWith("./") || specifier.startsWith("../");

/** The package a bare specifier names: `@scope/pkg/sub` → `@scope/pkg`. */
function packageName(specifier: string): string {
  const parts = specifier.split("/");
  return parts.slice(0, specifier.startsWith("@") ? 2 : 1).join("/");
}

/** The relative specifier workerd resolves from module `from` to module `to`. */
function relativeSpecifier(from: string, to: string): string {
  const fromDir = from.split("/").slice(0, -1);
  const toParts = to.split("/");
  let shared = 0;
  while (
    shared < fromDir.length &&
    shared < toParts.length - 1 &&
    fromDir[shared] === toParts[shared]
  )
    shared++;
  const up = fromDir.length - shared;
  return (up === 0 ? "./" : "../".repeat(up)) + toParts.slice(shared).join("/");
}

/** `a/b/../c.ts` → `a/c.ts`, relative to the importing module's directory. */
function joinPath(fromModule: string, specifier: string): string {
  const out = fromModule.split("/").slice(0, -1);
  for (const part of specifier.split("/")) {
    if (part === "..") out.pop();
    else if (part !== "." && part !== "") out.push(part);
  }
  return out.join("/");
}

/** One import of a module: its specifier and where es-module-lexer found its text. */
type SpecifierEdit = { specifier: string; start: number; end: number; dynamic: boolean };

/** Rewrite each import's specifier text (es-module-lexer spans) — static specifiers are unquoted
 *  spans, dynamic ones include their quotes. */
function rewriteSpecifiers(code: string, edits: SpecifierEdit[]): string {
  let out = code;
  for (const edit of [...edits].sort((a, b) => b.start - a.start))
    out =
      out.slice(0, edit.start) +
      (edit.dynamic ? JSON.stringify(edit.specifier) : edit.specifier) +
      out.slice(edit.end);
  return out;
}

/** Imports of one module, with non-literal dynamic imports refused (they cannot be resolved ahead). */
function importsOf(code: string, name: string, where: string): SpecifierEdit[] {
  let imports;
  try {
    [imports] = parse(code, name);
  } catch (error) {
    throw new Error(`${where}: ${name} is not a valid module: ${String(error)}`);
  }
  const out: SpecifierEdit[] = [];
  for (const imp of imports) {
    if (imp.d === -2) continue; // import.meta
    if (!imp.n)
      throw new Error(
        `${where}: ${name} has a dynamic import() of a computed specifier; only string literals can be resolved`,
      );
    out.push({ specifier: imp.n, start: imp.s, end: imp.e, dynamic: imp.d > -1 });
  }
  return out;
}

/** TypeScript with its types stripped (nothing else: `using`, decorators aside, runs as written). */
function stripTypes(code: string, name: string, where: string): string {
  try {
    return transform(code, {
      transforms: ["typescript"],
      disableESTransforms: true,
      filePath: name,
    }).code;
  } catch (error) {
    throw new Error(`${where}: ${name} does not parse as TypeScript: ${String(error)}`);
  }
}

const PackageManifest = z.object({
  main: z.string().optional(),
  dependencies: z.record(z.string(), z.string()).optional(),
});

/** A source's package: its entry — package.json's `main` (else `ENTRY_FILES`) — and its
 *  `dependencies`. The loader asks for
 *  it where a literal source is handed in, so a source with no entry is refused there. */
export function readPackage(
  source: ModuleMap,
  where: string,
): { entry: string; dependencies: Record<string, string> } {
  let manifest: z.infer<typeof PackageManifest> = {};
  if (source["package.json"]) {
    let parsed: unknown;
    try {
      parsed = JSON.parse(source["package.json"]);
    } catch (error) {
      throw new Error(`${where}: package.json is not valid JSON: ${String(error)}`);
    }
    const result = PackageManifest.safeParse(parsed);
    if (!result.success)
      throw new Error(
        `${where}: package.json needs "main" to be a path and "dependencies" to map package names to versions`,
      );
    manifest = result.data;
  }
  const { main } = manifest;
  const entry = main ? joinPath("", main) : ENTRY_FILES.find((file) => Object.hasOwn(source, file));
  if (!entry || !Object.hasOwn(source, entry))
    throw new Error(
      `${where}: no entry — ${main ? `package.json's main ${JSON.stringify(main)} is not a file` : `name the entry module in package.json "main"`}`,
    );
  return { entry, dependencies: manifest.dependencies || {} };
}

/** Every bare import is this module: a platform entry (build.ts names them so) or an npm package's
 *  esm.sh entry (the lock stores it so) — one naming rule, so an import is rewritten as it is read. */
const moduleOfSpecifier = (specifier: string) => `node_modules/${specifier}.js`;

/** The packages the platform ships (`iterate`, `zod`), from its entries' names. */
function platformPackages(platform: PlatformModules): string[] {
  const entries = Object.keys(platform.modules).filter(
    (name) => !name.startsWith("node_modules/."),
  );
  return [
    ...new Set(
      entries.map((name) => packageName(name.slice("node_modules/".length, -".js".length))),
    ),
  ].sort();
}

/** A bare import's platform module, or nothing when the platform does not ship the package; a
 *  subpath of a platform package it does not ship is refused (a second copy would break the one). */
function platformModuleOf(
  specifier: string,
  platform: PlatformModules,
  where: string,
): string | undefined {
  const name = moduleOfSpecifier(specifier);
  if (Object.hasOwn(platform.modules, name)) return name;
  if (platformPackages(platform).includes(packageName(specifier)))
    throw new Error(
      `${where}: ${specifier} is not a module loaded workers have (the platform ships ${Object.keys(
        platform.modules,
      )
        .filter((module) => !module.startsWith("node_modules/."))
        .map((module) => module.slice("node_modules/".length, -".js".length))
        .join(", ")})`,
    );
  return undefined;
}

/**
 * THE resolution: authored source → loader modules and the main module's name. `source` is the files
 * a caller handed the loader (a repo's files, an inline map). Only what the entry reaches is loaded —
 * a test file or a README beside the worker costs nothing.
 */
export async function resolveModules(
  source: ModuleMap,
  opts: ResolveOptions,
): Promise<{ mainModule: string; modules: ModuleMap }> {
  const { where, platform } = opts;
  const { entry: main, dependencies } = readPackage(source, where);
  const entry = opts.mainModule ? joinPath("", opts.mainModule) : main;
  if (!Object.hasOwn(source, entry))
    throw new Error(
      `${where}: no module ${JSON.stringify(opts.mainModule)} to load as the main module`,
    );
  const out: ModuleMap = {};
  const outputName = (path: string) => path.replace(/\.(mts|ts|mjs|js)$/, "") + ".js";
  const findSourceFile = (path: string): string | undefined => {
    const candidates = [path, `${path}.ts`, `${path}.js`, `${path}/index.ts`, `${path}/index.js`];
    // `./x.js` may name the author's `x.ts` (TypeScript's own convention).
    if (path.endsWith(".js")) candidates.push(path.replace(/\.js$/, ".ts"));
    return candidates.find(
      (candidate) => Object.hasOwn(source, candidate) && /\.(js|mjs|ts|mts)$/.test(candidate),
    );
  };
  // 1. the author's modules, walked from the entry and rewritten in one pass.
  const platformUsed: string[] = [];
  const npmSpecifiers = new Set<string>();
  const seen = new Set<string>([entry]);
  const queue = [entry];
  while (queue.length) {
    const path = queue.pop()!;
    const name = outputName(path);
    if (Object.hasOwn(out, name))
      throw new Error(`${where}: ${path} and another file both load as ${name}`);
    const code = /\.m?ts$/.test(path) ? stripTypes(source[path]!, path, where) : source[path]!;
    const edits: SpecifierEdit[] = [];
    for (const edit of importsOf(code, name, where)) {
      const { specifier } = edit;
      if (specifier.startsWith("cloudflare:")) continue;
      let target: string;
      if (isRelative(specifier)) {
        const file = findSourceFile(joinPath(path, specifier));
        if (!file)
          throw new Error(`${where}: ${path} imports ${specifier}, and there is no such file`);
        if (!seen.has(file)) {
          seen.add(file);
          queue.push(file);
        }
        target = outputName(file);
      } else if (specifier.startsWith("node:")) {
        throw new Error(
          `${where}: ${path} imports the Node.js builtin ${specifier}, which loaded workers do not have`,
        );
      } else if (specifier.startsWith("/") || /^[a-z]+:/.test(specifier)) {
        throw new Error(
          `${where}: ${path} imports ${specifier}; import packages by name and list them in package.json`,
        );
      } else {
        const platformModule = platformModuleOf(specifier, platform, where);
        if (platformModule) platformUsed.push(platformModule);
        else if (Object.hasOwn(dependencies, packageName(specifier))) npmSpecifiers.add(specifier);
        else
          throw new Error(
            `${where}: ${path} imports ${specifier}; list ${packageName(specifier)} in package.json "dependencies"`,
          );
        target = moduleOfSpecifier(specifier);
      }
      edits.push({ ...edit, specifier: relativeSpecifier(name, target) });
    }
    out[name] = rewriteSpecifiers(code, edits);
  }

  // 2. npm packages: their locked graph, which may itself import platform packages.
  if (npmSpecifiers.size) {
    const graph = await lockedDependencyGraph([...npmSpecifiers].sort(), dependencies, opts);
    Object.assign(out, graph.modules);
    platformUsed.push(...graph.platformModules);
  }

  // 3. the platform modules the worker reaches, and nothing else.
  addPlatformModules(out, platformUsed, platform);
  return { mainModule: outputName(entry), modules: out };
}

/** The platform modules `names` added to `out`, with every platform module they import. */
function addPlatformModules(out: ModuleMap, names: string[], platform: PlatformModules): void {
  while (names.length) {
    const name = names.pop()!;
    if (Object.hasOwn(out, name)) continue;
    out[name] = platform.modules[name]!;
    names.push(...(platform.imports[name] ?? []));
  }
}

/** What every loaded worker evaluates first (iterate src/sdk/loaded-worker.ts), as build.ts names it. */
const LOADED_WORKER_MODULE = "node_modules/.platform/loaded-worker.js";

/** A resolved worker as the loader starts it: its main module imports the platform's
 *  LOADED_WORKER_MODULE before anything of its own — on its first line, so its lines keep their
 *  numbers — and exports what it always did. */
export function enteredThroughPlatform(
  resolved: { mainModule: string; modules: ModuleMap },
  platform: PlatformModules,
): { mainModule: string; modules: ModuleMap } {
  const modules = { ...resolved.modules };
  addPlatformModules(modules, [LOADED_WORKER_MODULE], platform);
  const { mainModule } = resolved;
  const platformFirst = JSON.stringify(relativeSpecifier(mainModule, LOADED_WORKER_MODULE));
  modules[mainModule] = `import ${platformFirst}; ${modules[mainModule]}`;
  return { mainModule, modules };
}

/** A locked npm graph: every module (each requested specifier's entry under
 *  `node_modules/<specifier>.js`), and the platform modules it imports (esm.sh leaves them external). */
type DependencyGraph = { modules: ModuleMap; platformModules: string[] };

/** The dependency graph for these specifiers under these versions — from the store when this exact
 *  set was resolved before (by any project), otherwise resolved from esm.sh and stored. A version
 *  that cannot be locked (`esmPackageBase`) is refused before the store is read, so no lock stored
 *  under a branch's key can load. */
async function lockedDependencyGraph(
  specifiers: string[],
  dependencies: Record<string, string>,
  opts: ResolveOptions,
): Promise<DependencyGraph> {
  const packages = [...new Set(specifiers.map(packageName))].sort();
  const bases = Object.fromEntries(
    packages.map((name) => [name, esmPackageBase(name, dependencies[name]!, opts.where)]),
  );
  const lockInput = {
    specifiers,
    ranges: Object.fromEntries(packages.map((name) => [name, dependencies[name]!])),
    externals: [...WORKERD_BUILTINS, ...platformPackages(opts.platform)],
  };
  // The prefix names the lock's shape and the rewrite rules: a change to either is a new prefix.
  const key = `module-lock-3/${await sha256Hex(JSON.stringify(lockInput))}`;
  const stored = await opts.store.get(key);
  if (stored) return JSON.parse(stored) as DependencyGraph;
  const graph = await resolveFromEsm(lockInput, bases, opts);
  await opts.store.put(key, JSON.stringify(graph));
  return graph;
}

/** An esm.sh module path → its loader name under `node_modules/.esm/`, readable and ending in `.js`
 *  (`/hono@>=3.9.0/validator?target=es2022` → `node_modules/.esm/hono@>=3.9.0/validator~target=es2022.js`).
 *  Synchronous, so an import is rewritten before its target arrives. */
function esmModuleName(url: URL): string {
  const path = url.pathname.replace(/\.m?js$/, "");
  const query = url.search ? `~${url.search.slice(1).replace(/[^\w.=@-]+/g, "_")}` : "";
  return `node_modules/.esm${path}${query}.js`.replace(/\/+/g, "/");
}

/** esm.sh's URL for the package dependency `name` is listed as, at its version. The source imports
 *  it by `name`, whichever package that is (npm installs an alias under the name it is listed by):
 *  - an npm version: `/<name>@<version>`;
 *  - an npm alias, `npm:<package>@<version>`: `/<package>@<version>`, its `latest` when it names no
 *    version. esm.sh does not read an alias itself: asked for `/react@npm:preact@10`, it serves react;
 *  - a pkg.pr.new URL at a full commit, of `name` or of another package (an alias):
 *    `/pr/<owner>/<repo>/<package>@<commit>`. Any other pkg.pr.new URL is refused, naming the fix: a
 *    branch or a PR number moves (this file's header), and esm.sh cannot resolve one for a scoped
 *    package anyway. */
function esmPackageBase(name: string, version: string, where: string): string {
  if (version.startsWith("npm:")) {
    const alias = version.slice("npm:".length).match(/^((?:@[^/@]+\/)?[^/@]+)(?:@([^:/]+))?$/);
    if (!alias)
      throw new Error(
        `${where}: package.json lists ${name} as ${version}; an alias names a package on npm and its version: npm:<package>@<version>`,
      );
    return `${ESM_ORIGIN}/${alias[1]}@${alias[2] || "latest"}`;
  }
  if (!version.startsWith("https://pkg.pr.new/")) return `${ESM_ORIGIN}/${name}@${version}`;
  const build = pkgPrNewBuildOf(version);
  if (!build)
    throw new Error(
      `${where}: package.json lists ${name} as ${version}; pin it as https://pkg.pr.new/<owner>/<repo>/${name}@<40-hex sha>`,
    );
  if (!isPkgPrNewCommit(build.ref))
    throw new Error(
      `${where}: package.json lists ${name} at ${JSON.stringify(build.ref)}, which is not a commit, so it could name another build tomorrow; pin the commit: https://pkg.pr.new/<owner>/<repo>/${build.name}@<40-hex sha> (a HEAD of the URL names it in x-commit-key)`,
    );
  return `${ESM_ORIGIN}/pr/${build.owner}/${build.repo}/${build.name}@${build.ref}`;
}

/** An esm.sh module's text, read whole; anything but a JavaScript 200 is refused. esm.sh out of
 *  reach, too slow (ESM_FETCH_TIMEOUT_MS) or answering 5xx, 429 or 408 is the platform's failure,
 *  code UNAVAILABLE of its kind (iterate/platform-retry `httpFailureKind`): a
 *  publication meets it again rather than refusing the commit. Any other answer is the source's. */
async function fetchModuleText(url: string, fetchFn: typeof fetch): Promise<string> {
  let response: Response;
  try {
    response = await fetchFn(url, {
      headers: { "user-agent": "iterate-os" },
      signal: AbortSignal.timeout(ESM_FETCH_TIMEOUT_MS),
    });
  } catch (error) {
    const timedOut = error instanceof Error && error.name === "TimeoutError";
    throw unavailableError(
      timedOut ? "overloaded" : "disconnected",
      `${url}: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
  const text = await response.text();
  if (response.status !== 200) {
    const kind = httpFailureKind(response);
    const message = `${url} answered ${response.status}`;
    throw isPlatformFailureKind(kind) ? unavailableError(kind, message) : new Error(message);
  }
  const type = response.headers.get("content-type") ?? "";
  if (!type.includes("javascript")) throw new Error(`${url} is ${type || "untyped"}, not a module`);
  return text;
}

/** A bare `<owner>/<repo>/<package>/<subpath>` in a module esm.sh serves under
 *  `/pr/<owner>/<repo>/<package>@<commit>/…`: the path of that subpath at the same commit. */
function prSelfImportOf(specifier: string, importer: URL): string | undefined {
  const pr = importer.pathname.match(/^\/pr\/([^/]+\/[^/]+\/(?:@[^/]+\/)?[^/@]+)@([^/]+)\//);
  if (!pr || !specifier.startsWith(`${pr[1]}/`)) return undefined;
  return `/pr/${pr[1]}@${pr[2]}/${specifier.slice(pr[1]!.length + 1)}`;
}

/** A bare `<package>/<subpath>` in a module esm.sh serves under `/<package>@<version>/…`: the path
 *  of that subpath at the same version. esm.sh spells a package's import of its OWN export bare when
 *  the package is external, so this is a platform package an alias loads from npm
 *  (`"iterate-2026-10-01": "npm:iterate@0.4.0"`): its own modules are the aliased version's, never
 *  the platform's build. */
function npmSelfImportOf(specifier: string, importer: URL): string | undefined {
  const own = importer.pathname.match(/^\/((?:@[^/]+\/)?[^/@]+)@([^/]+)\//);
  if (!own || packageName(specifier) !== own[1]) return undefined;
  return `/${own[1]}@${own[2]}${specifier.slice(own[1].length)}`;
}

/** Crawl esm.sh from each specifier's entry, pipelined: a module is rewritten and its own imports
 *  fetched the moment it arrives (module names follow from URLs alone), so wall time is the graph's
 *  depth in round trips, not its size. */
async function resolveFromEsm(
  lock: { specifiers: string[]; externals: string[] },
  /** Each package's esm.sh URL (`esmPackageBase`). */
  bases: Record<string, string>,
  opts: ResolveOptions,
): Promise<DependencyGraph> {
  const { where, platform } = opts;
  const query = new URLSearchParams({ target: "es2022", external: lock.externals.join(",") });
  const modules: ModuleMap = {};
  const platformModules = new Set<string>();
  /** Each module fetched, by URL → the name it loads under. */
  const started = new Map<string, string>();
  /** A second name a loaded module is wanted under → the name it loads under. */
  const aliases = new Map<string, string>();
  const inFlight = new Set<Promise<void>>();
  const failures: Error[] = [];

  /** Load `href` once, under `name`. ONE MODULE PER URL: wanted again under another name — a
   *  requested subpath's entry that the package's own modules import by their name for it too
   *  (the probe of a config whose `agents.ts` imports `@iterate-com/agents` and whose `worker.ts`
   *  imports its `/install`) — that name re-exports it (`aliasModule`), never a second copy, whose
   *  classes would be other classes. */
  const load = (href: string, name: string): void => {
    const loadedAs = started.get(href);
    if (loadedAs) {
      if (loadedAs !== name) aliases.set(name, loadedAs);
      return;
    }
    started.set(href, name);
    const url = new URL(href);
    const loading = (async () => {
      const code = await fetchModuleText(href, opts.fetch);
      const edits: SpecifierEdit[] = [];
      for (const edit of importsOf(code, href, where)) {
        const { specifier } = edit;
        const builtin = specifier.match(/^\/?(cloudflare:[^?]+)/)?.[1];
        const self = prSelfImportOf(specifier, url) || npmSelfImportOf(specifier, url);
        if (builtin) {
          edits.push({ ...edit, specifier: builtin });
        } else if (specifier.startsWith("node:")) {
          // esm.sh's own `/node/*.mjs` polyfills are ordinary modules; a bare `node:` import would
          // need nodejs_compat, which loaded workers run without.
          throw new Error(
            `${url.pathname} needs the Node.js builtin ${specifier}, which loaded workers do not have`,
          );
        } else if (specifier.startsWith("/") || isRelative(specifier)) {
          const child = new URL(specifier, url);
          if (child.origin !== ESM_ORIGIN)
            throw new Error(`${url.pathname} imports ${child.href}, outside esm.sh`);
          const childName = esmModuleName(child);
          load(child.href, childName);
          edits.push({ ...edit, specifier: relativeSpecifier(name, childName) });
        } else if (self) {
          // esm.sh's `/pr/` route spells a package's import of its OWN exported subpath bare, as
          // `<owner>/<repo>/<package>/<subpath>`, and its npm route as `<package>/<subpath>` for an
          // aliased platform package; the importing module's URL names the commit or version.
          const child = new URL(`${self}?${query}`, ESM_ORIGIN);
          const childName = esmModuleName(child);
          load(child.href, childName);
          edits.push({ ...edit, specifier: relativeSpecifier(name, childName) });
        } else {
          // Bare: only the platform packages esm.sh left external.
          const platformModule = platformModuleOf(specifier, platform, url.pathname);
          if (!platformModule)
            throw new Error(`${url.pathname} imports ${specifier}, which esm.sh left unresolved`);
          platformModules.add(platformModule);
          edits.push({ ...edit, specifier: relativeSpecifier(name, platformModule) });
        }
      }
      modules[name] = rewriteSpecifiers(code, edits);
    })().catch((error: Error) => void failures.push(error));
    inFlight.add(loading);
    void loading.finally(() => inFlight.delete(loading));
  };

  for (const specifier of lock.specifiers) {
    const name = packageName(specifier);
    const base = bases[name]!;
    load(`${base}${specifier.slice(name.length)}?${query}`, moduleOfSpecifier(specifier));
  }
  while (inFlight.size) await Promise.all(inFlight);
  if (failures.length) {
    const message = `${where}: resolving ${lock.specifiers.join(", ")} failed: ${failures.map((failure) => failure.message).join("; ")}`;
    // one module the platform failed makes the whole resolution the platform's to meet again
    const platform = failures.map(failureKind).find(isPlatformFailureKind);
    throw platform ? unavailableError(platform, message) : new Error(message);
  }
  for (const [name, loadedAs] of aliases)
    modules[name] ??= aliasModule(name, loadedAs, modules[loadedAs]!);
  return { modules, platformModules: [...platformModules].sort() };
}

/** Module `name` as another name of module `loadedAs` (`code`): everything it exports, its default
 *  export included when it has one (`export *` leaves a default out). */
function aliasModule(name: string, loadedAs: string, code: string): string {
  const target = JSON.stringify(relativeSpecifier(name, loadedAs));
  const hasDefault = parse(code)[1].some((exported) => exported.n === "default");
  return `export * from ${target};${hasDefault ? ` export { default } from ${target};` : ""}\n`;
}
