// Generated by `sqlfu generate`. Do not edit.
// Row types for every table and view in your project's schema.

export type AccountRow = {
  id: string;
  accountId: string;
  providerId: string;
  userId: string;
  accessToken: string | null;
  refreshToken: string | null;
  idToken: string | null;
  accessTokenExpiresAt: Date | null;
  refreshTokenExpiresAt: Date | null;
  scope: string | null;
  password: string | null;
  createdAt: Date;
  updatedAt: Date;
};

export type DeviceCodeRow = {
  id: string;
  deviceCode: string;
  userCode: string;
  userId: string | null;
  expiresAt: Date;
  status: string;
  lastPolledAt: Date | null;
  pollingInterval: number | null;
  clientId: string | null;
  scope: string | null;
};

export type InvitationRow = {
  id: string;
  organizationId: string;
  email: string;
  role: string | null;
  status: string;
  expiresAt: Date;
  createdAt: Date;
  inviterId: string;
};

export type JwksRow = {
  id: string;
  publicKey: string;
  privateKey: string;
  createdAt: Date;
  expiresAt: Date | null;
};

export type MemberRow = {
  id: string;
  organizationId: string;
  userId: string;
  role: string;
  createdAt: Date;
};

export type OauthAccessTokenRow = {
  id: string;
  token: string;
  clientId: string;
  sessionId: string | null;
  userId: string | null;
  referenceId: string | null;
  refreshId: string | null;
  expiresAt: Date;
  createdAt: Date;
  scopes: string;
};

export type OauthClientRow = {
  id: string;
  clientId: string;
  clientSecret: string | null;
  disabled: number | null;
  skipConsent: number | null;
  enableEndSession: number | null;
  subjectType: string | null;
  scopes: string | null;
  userId: string | null;
  createdAt: Date | null;
  updatedAt: Date | null;
  name: string | null;
  uri: string | null;
  icon: string | null;
  contacts: string | null;
  tos: string | null;
  policy: string | null;
  softwareId: string | null;
  softwareVersion: string | null;
  softwareStatement: string | null;
  redirectUris: string;
  postLogoutRedirectUris: string | null;
  tokenEndpointAuthMethod: string | null;
  grantTypes: string | null;
  responseTypes: string | null;
  public: number | null;
  type: string | null;
  requirePKCE: number | null;
  referenceId: string | null;
  metadata: string | null;
};

export type OauthConsentRow = {
  id: string;
  clientId: string;
  userId: string | null;
  referenceId: string | null;
  scopes: string;
  createdAt: Date;
  updatedAt: Date;
};

export type OauthProjectSelectionRow = {
  session_id: string;
  client_id: string;
  user_id: string;
  project_ids: string;
  created_at: number;
  updated_at: number;
};

export type OauthRefreshTokenRow = {
  id: string;
  token: string;
  clientId: string;
  sessionId: string | null;
  userId: string;
  referenceId: string | null;
  expiresAt: Date;
  createdAt: Date;
  revoked: Date | null;
  authTime: Date | null;
  scopes: string;
};

export type OrganizationRow = {
  id: string;
  name: string;
  slug: string;
  logo: string | null;
  createdAt: Date;
  metadata: string | null;
};

export type ProjectRow = {
  id: string;
  organization_id: string;
  name: string;
  slug: string;
  metadata: string;
  archived_at: number | null;
  created_at: number;
  updated_at: number;
};

export type SessionRow = {
  id: string;
  expiresAt: Date;
  token: string;
  createdAt: Date;
  updatedAt: Date;
  ipAddress: string | null;
  userAgent: string | null;
  userId: string;
  impersonatedBy: string | null;
  activeOrganizationId: string | null;
};

export type UserRow = {
  id: string;
  name: string;
  email: string;
  emailVerified: number;
  image: string | null;
  createdAt: Date;
  updatedAt: Date;
  role: string | null;
  banned: number | null;
  banReason: string | null;
  banExpires: Date | null;
};

export type VerificationRow = {
  id: string;
  identifier: string;
  value: string;
  expiresAt: Date;
  createdAt: Date;
  updatedAt: Date;
};
