import path from "node:path";
import { Miniflare } from "miniflare";
import { createD1Client, defineConfig, type DisposableAsyncClient } from "sqlfu";

const here = import.meta.dirname;

// Local dev D1 lives where the @cloudflare/vite-plugin persists miniflare
// state, keyed by the placeholder database id the top-level wrangler.jsonc
// declares (generated by scripts/generate-wrangler-config.ts). Opening the
// same id under the same persist root reaches the exact database `pnpm dev`
// serves.
const persistRoot = path.join(here, ".wrangler", "state", "v3");
const LOCAL_DEV_DB_ID = "local-dev-resources-db";

async function openLocalDevD1(): Promise<DisposableAsyncClient> {
  const mf = new Miniflare({
    script: "",
    modules: true,
    defaultPersistRoot: persistRoot,
    d1Persist: true,
    d1Databases: { DB: LOCAL_DEV_DB_ID },
  });
  await mf.ready;

  const database = await mf.getD1Database("DB");
  return {
    client: createD1Client(database),
    async [Symbol.asyncDispose]() {
      await mf.dispose();
    },
  };
}

export default defineConfig({
  db: openLocalDevD1,
  migrations: { path: "./migrations", preset: "d1" },
  definitions: "./definitions.sql",
  queries: "./sql",
});
