/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 78344fdc42fe10ad3b9eefbe0420c159)
interface __BaseEnv_Env {
	ARTIFACTS: Artifacts;
	LOADER: WorkerLoader;
	AI: Ai;
	ARTIFACTS_ACCOUNT_ID: "376ef7ed81b0573f93524de763666c15";
	ARTIFACTS_NAMESPACE: "minimal-itx-v3-repos";
	SECRET_ENCRYPTION_KEY: "minimal-itx-v4-secret-encryption-key";
	ITX: DurableObjectNamespace<import("./src/worker").ItxDurableObject>;
	PROJECT: DurableObjectNamespace<import("./src/worker").ProjectDurableObject>;
	AGENT: DurableObjectNamespace<import("./src/worker").AgentDurableObject>;
	REPO: DurableObjectNamespace<import("./src/worker").RepoDurableObject>;
	SECRET: DurableObjectNamespace<import("./src/worker").SecretDurableObject>;
	WORKER: DurableObjectNamespace<import("./src/worker").StatefulWorkerDurableObject>;
	PLAYGROUND_DEMO: DurableObjectNamespace<import("./src/worker").PlaygroundDemoDurableObject>;
	PAGE_DEBUGGING_DEMO: DurableObjectNamespace<import("./src/worker").PageDebuggingDemoDurableObject>;
	STREAM: DurableObjectNamespace<import("./src/worker").StreamDurableObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "ProjectDurableObject" | "StreamDurableObject" | "RepoDurableObject" | "AgentDurableObject" | "ItxDurableObject" | "StatefulWorkerDurableObject" | "SecretDurableObject" | "PlaygroundDemoDurableObject" | "PageDebuggingDemoDurableObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ARTIFACTS_ACCOUNT_ID" | "ARTIFACTS_NAMESPACE" | "SECRET_ENCRYPTION_KEY">> {}
}
