/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime` (hash: 746ecd03e2cf26c227294fbb178ebd49)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		ASSETS: Fetcher;
		ITERATE_OAUTH_ISSUER: string;
		ITERATE_OAUTH_CLIENT_ID: string;
		ITERATE_OAUTH_CLIENT_SECRET: string;
		ITERATE_OAUTH_REDIRECT_URI: string;
	}
}
interface Env extends Cloudflare.Env {}
