// Generated by scripts/generate-filters.ts — do not edit by hand.
// AI-generated backdrop images for the camera filters. Content-hashed files live in website/filter-assets/.
// Deploy the mobile website before publishing an app update with new URLs.

export const FILTER_BACKDROPS: Record<string, string> = {
  "potato-dirt":
    "https://mobile.iterate.com/filter-assets/backdrop-potato-dirt-64d985fc68e74286216268162744a18c1699f95d7cd3efbaf994c06b0073f492.jpeg",
  "potato-farm":
    "https://mobile.iterate.com/filter-assets/backdrop-potato-farm-ccd8783c0d4231d6d2f5b4e5f57319b3612803465fcbc5fae64a9ac2384e941d.jpeg",
  "potato-rain":
    "https://mobile.iterate.com/filter-assets/backdrop-potato-rain-df1492abe847920f683d52278dd3935aa9d0821555ca7103dcba41cc6c862bfd.jpeg",
  "eyes-lips-beach":
    "https://mobile.iterate.com/filter-assets/backdrop-eyes-lips-beach-124e2007f905e936111893125198ae0a93a76d5e25b56492b956c52239a465d3.jpeg",
  "eyes-lips-space":
    "https://mobile.iterate.com/filter-assets/backdrop-eyes-lips-space-5d8b084832fae53147970383f8bd8f4abd4bcb7fed0aa4c72e345670d06b7dbd.jpeg",
  "eyes-lips-sunset":
    "https://mobile.iterate.com/filter-assets/backdrop-eyes-lips-sunset-9784ee95d6744c4030bbcae7c0afafb38a1d38be5f866665797994e903f6a61a.jpeg",
  "cat-study":
    "https://mobile.iterate.com/filter-assets/backdrop-cat-study-e223dee9eccfe0a75a0c2c09915a07bbea1655642199d4901f91e10a52d29c69.jpeg",
  "cat-garden":
    "https://mobile.iterate.com/filter-assets/backdrop-cat-garden-1d730b98fcf72c597a42d92a44cd303ee62133bf2ce08e2acb88741506111cb0.jpeg",
  "cat-livingroom":
    "https://mobile.iterate.com/filter-assets/backdrop-cat-livingroom-a7e4d4f21ada46d8dbd908fafbe793dfe1951cf97a244c01b82ef2894d31cb2c.jpeg",
};
